/**
 * 02 — Permissions Seeder
 *
 * Seeds 60 permissions into public.permissions (tenant-scoped).
 * 9 modules x 6 actions = 54 base permissions + 6 special permissions.
 *
 * Idempotent: uses ON CONFLICT DO NOTHING.
 * Requires a tenant to exist (reads tenant_id from the demo tenant).
 *
 * Run with:
 *   npx ts-node -r tsconfig-paths/register src/database/sql/seeders/02-permissions.seed.ts
 */

import { Sequelize } from 'sequelize-typescript';
import { v7 as uuidv7 } from 'uuid';
import * as dotenv from 'dotenv';
import * as path from 'path';

dotenv.config({ path: path.resolve(__dirname, '../../../../.env') });

const DB_HOST = process.env.DB_HOST || 'localhost';
const DB_PORT = parseInt(process.env.DB_PORT || '5432', 10);
const DB_USERNAME = process.env.DB_USER || 'postgres';
const DB_PASSWORD = process.env.DB_PASS || 'postgres';
const DB_DATABASE = process.env.DB_NAME || 'erp_core';

// ── Module-action matrix ─────────────────────────────────────────────────────
const MODULES = [
  'crm',
  'hr',
  'inventory',
  'sales',
  'purchasing',
  'projects',
  'settings',
  'reports',
  'notifications',
] as const;

const ACTIONS = ['view', 'create', 'update', 'delete', 'approve', 'export'] as const;

// ── Special permissions (not generated by the matrix) ────────────────────────
const SPECIAL_PERMISSIONS = [
  {
    module: 'settings',
    action: 'manage_roles',
    description: 'Manage system roles and their permissions',
  },
  {
    module: 'settings',
    action: 'manage_billing',
    description: 'Manage billing and subscription settings',
  },
  {
    module: 'settings',
    action: 'manage_sequences',
    description: 'Manage document number sequences',
  },
  {
    module: 'hr',
    action: 'approve_leave',
    description: 'Approve or reject employee leave requests',
  },
  { module: 'sales', action: 'approve_order', description: 'Approve sales orders' },
  { module: 'purchasing', action: 'approve_order', description: 'Approve purchase orders' },
];

function describePermission(module: string, action: string): string {
  const actionLabels: Record<string, string> = {
    view: 'View',
    create: 'Create',
    update: 'Update',
    delete: 'Delete',
    approve: 'Approve',
    export: 'Export',
  };
  const moduleLabels: Record<string, string> = {
    crm: 'CRM',
    hr: 'HR',
    inventory: 'Inventory',
    sales: 'Sales',
    purchasing: 'Purchasing',
    projects: 'Projects',
    settings: 'Settings',
    reports: 'Reports',
    notifications: 'Notifications',
  };
  return `${actionLabels[action] || action} ${moduleLabels[module] || module} records`;
}

async function seed() {
  const sequelize = new Sequelize({
    dialect: 'postgres',
    host: DB_HOST,
    port: DB_PORT,
    username: DB_USERNAME,
    password: DB_PASSWORD,
    database: DB_DATABASE,
    logging: false,
  });

  try {
    await sequelize.authenticate();
    console.log('Connected to database.');

    // Resolve demo tenant
    const [tenants] = await sequelize.query(
      `SELECT id FROM public.tenants WHERE slug = 'demo' AND deleted_at IS NULL`,
    );
    if ((tenants as any[]).length === 0) {
      console.error(
        'Demo tenant not found. Run 04-demo-tenant.seed.ts first (tenant creation part).',
      );
      console.log('Skipping permissions seed — will be run as part of 04-demo-tenant.seed.ts.');
      await sequelize.close();
      return;
    }
    const tenantId = (tenants as any[])[0].id;

    // Build full permission list
    const allPermissions: Array<{ module: string; action: string; description: string }> = [];

    // Matrix permissions (9 x 6 = 54)
    for (const module of MODULES) {
      for (const action of ACTIONS) {
        allPermissions.push({
          module,
          action,
          description: describePermission(module, action),
        });
      }
    }

    // Special permissions (6)
    for (const sp of SPECIAL_PERMISSIONS) {
      allPermissions.push(sp);
    }

    console.log(`Seeding ${allPermissions.length} permissions for tenant ${tenantId}...`);

    let created = 0;
    let skipped = 0;

    for (const perm of allPermissions) {
      const permName = `${perm.module}:${perm.action}`;
      const [result] = await sequelize.query(
        `INSERT INTO public.permissions (id, tenant_id, module, action, description, created_at, updated_at)
         VALUES (:id, :tenantId, :module, :action, :description, NOW(), NOW())
         ON CONFLICT (tenant_id, module, action) DO NOTHING
         RETURNING id`,
        {
          replacements: {
            id: uuidv7(),
            tenantId,
            module: perm.module,
            action: perm.action,
            description: perm.description,
          },
        },
      );
      if ((result as any[]).length > 0) {
        created++;
      } else {
        skipped++;
      }
    }

    console.log(`Permissions seed complete: ${created} created, ${skipped} already existed.`);
    console.log(`Total permissions: ${allPermissions.length}`);
  } catch (error) {
    console.error('Permissions seed failed:', error);
    process.exit(1);
  } finally {
    await sequelize.close();
  }
}

seed();

// Export for use by other seeders
export { MODULES, ACTIONS, SPECIAL_PERMISSIONS, describePermission };
