import { Sequelize } from 'sequelize';
import { v7 as uuidv7 } from 'uuid';

const TENANT_ID = '10000000-0000-0000-0000-000000000001';
const CATEGORY_1_ID = '70000000-0000-0000-0000-000000000001';
const CATEGORY_2_ID = '70000000-0000-0000-0000-000000000002';
const CATEGORY_3_ID = '70000000-0000-0000-0000-000000000003';
const CATEGORY_4_ID = '70000000-0000-0000-0000-000000000004';
const CATEGORY_5_ID = '70000000-0000-0000-0000-000000000005';
const BRAND_1_ID = '70100000-0000-0000-0000-000000000001';
const BRAND_2_ID = '70100000-0000-0000-0000-000000000002';
const BRAND_3_ID = '70100000-0000-0000-0000-000000000003';
const BRAND_4_ID = '70100000-0000-0000-0000-000000000004';
const PRODUCT_1_ID = '71000000-0000-0000-0000-000000000001';
const PRODUCT_2_ID = '71000000-0000-0000-0000-000000000002';
const PRODUCT_3_ID = '71000000-0000-0000-0000-000000000003';
const PRODUCT_4_ID = '71000000-0000-0000-0000-000000000004';
const PRODUCT_5_ID = '71000000-0000-0000-0000-000000000005';
const PRODUCT_6_ID = '71000000-0000-0000-0000-000000000006';
const PRODUCT_7_ID = '71000000-0000-0000-0000-000000000007';
const PRODUCT_8_ID = '71000000-0000-0000-0000-000000000008';
const PRODUCT_9_ID = '71000000-0000-0000-0000-000000000009';
const PRODUCT_10_ID = '71000000-0000-0000-0000-000000000010';
const WAREHOUSE_1_ID = '40000000-0000-0000-0000-000000000001';
const WAREHOUSE_2_ID = '40000000-0000-0000-0000-000000000002';
const CURRENCY_SAR_ID = '60000000-0000-0000-0000-000000000001';

export async function seed(sequelize: Sequelize): Promise<void> {
  const qi = sequelize.getQueryInterface();
  const now = new Date();

  // Product Categories
  await qi.bulkInsert('product_categories', [
    {
      id: CATEGORY_1_ID,
      tenantId: TENANT_ID,
      nameEn: 'Food',
      nameAr: 'طعام',
      descriptionEn: 'Food products and meals',
      descriptionAr: 'منتجات غذائية ووجبات',
      parentId: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: CATEGORY_2_ID,
      tenantId: TENANT_ID,
      nameEn: 'Beverages',
      nameAr: 'مشروبات',
      descriptionEn: 'Drinks and beverages',
      descriptionAr: 'مشروبات متنوعة',
      parentId: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: CATEGORY_3_ID,
      tenantId: TENANT_ID,
      nameEn: 'Electronics',
      nameAr: 'إلكترونيات',
      descriptionEn: 'Electronic devices and accessories',
      descriptionAr: 'أجهزة إلكترونية وملحقاتها',
      parentId: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: CATEGORY_4_ID,
      tenantId: TENANT_ID,
      nameEn: 'Office Supplies',
      nameAr: 'مستلزمات مكتبية',
      descriptionEn: 'Office supplies and stationery',
      descriptionAr: 'مستلزمات مكتبية وقرطاسية',
      parentId: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: CATEGORY_5_ID,
      tenantId: TENANT_ID,
      nameEn: 'Desserts',
      nameAr: 'حلويات',
      descriptionEn: 'Desserts and sweets',
      descriptionAr: 'حلويات ومعجنات',
      parentId: CATEGORY_1_ID,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);

  // Product Brands
  await qi.bulkInsert('product_brands', [
    {
      id: BRAND_1_ID,
      tenantId: TENANT_ID,
      nameEn: 'Premium Brand',
      nameAr: 'علامة مميزة',
      descriptionEn: 'Premium quality products',
      descriptionAr: 'منتجات بجودة عالية',
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: BRAND_2_ID,
      tenantId: TENANT_ID,
      nameEn: 'Standard Brand',
      nameAr: 'علامة عادية',
      descriptionEn: 'Standard quality products',
      descriptionAr: 'منتجات بجودة عادية',
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: BRAND_3_ID,
      tenantId: TENANT_ID,
      nameEn: 'Samsung',
      nameAr: 'سامسونج',
      descriptionEn: 'Samsung electronics and devices',
      descriptionAr: 'إلكترونيات وأجهزة سامسونج',
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: BRAND_4_ID,
      tenantId: TENANT_ID,
      nameEn: 'Local Harvest',
      nameAr: 'الحصاد المحلي',
      descriptionEn: 'Locally sourced food products',
      descriptionAr: 'منتجات غذائية محلية المصدر',
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);

  // Products
  await qi.bulkInsert('products', [
    {
      id: PRODUCT_1_ID,
      tenantId: TENANT_ID,
      nameEn: 'Chicken Shawarma',
      nameAr: 'شاورما دجاج',
      descriptionEn: 'Grilled chicken shawarma wrap',
      descriptionAr: 'لفة شاورما دجاج مشوية',
      sku: 'FOOD-001',
      barcode: null,
      categoryId: CATEGORY_1_ID,
      unitPrice: 25,
      costPrice: 12,
      currency: 'SAR',
      unitOfMeasure: 'pcs',
      reorderPoint: 0,
      taxRate: 15,
      isActive: true,
      images: null,
      productType: 'consumable',
      invoicePolicy: 'ordered',
      canBeSold: true,
      canBePurchased: true,
      hasVariants: false,
      hasSerialTracking: false,
      hasLotTracking: false,
      hasExpiryDate: false,
      reorderMinQty: null,
      reorderQty: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: PRODUCT_2_ID,
      tenantId: TENANT_ID,
      nameEn: 'Arabic Coffee',
      nameAr: 'قهوة عربية',
      descriptionEn: 'Traditional Arabic coffee with cardamom',
      descriptionAr: 'قهوة عربية تقليدية بالهيل',
      sku: 'BEV-001',
      barcode: null,
      categoryId: CATEGORY_2_ID,
      unitPrice: 15,
      costPrice: 5,
      currency: 'SAR',
      unitOfMeasure: 'pcs',
      reorderPoint: 0,
      taxRate: 15,
      isActive: true,
      images: null,
      productType: 'consumable',
      invoicePolicy: 'ordered',
      canBeSold: true,
      canBePurchased: true,
      hasVariants: false,
      hasSerialTracking: false,
      hasLotTracking: false,
      hasExpiryDate: false,
      reorderMinQty: null,
      reorderQty: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: PRODUCT_3_ID,
      tenantId: TENANT_ID,
      nameEn: 'Samsung Galaxy S24',
      nameAr: 'سامسونج جالكسي S24',
      descriptionEn: 'Samsung Galaxy S24 smartphone',
      descriptionAr: 'هاتف سامسونج جالكسي S24',
      sku: 'ELEC-001',
      barcode: '6281234567890',
      categoryId: CATEGORY_3_ID,
      unitPrice: 3999,
      costPrice: 3200,
      currency: 'SAR',
      unitOfMeasure: 'pcs',
      reorderPoint: 5,
      taxRate: 15,
      isActive: true,
      images: null,
      productType: 'storable',
      invoicePolicy: 'ordered',
      canBeSold: true,
      canBePurchased: true,
      hasVariants: false,
      hasSerialTracking: true,
      hasLotTracking: false,
      hasExpiryDate: false,
      reorderMinQty: 5,
      reorderQty: 20,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: PRODUCT_4_ID,
      tenantId: TENANT_ID,
      nameEn: 'Wireless Mouse',
      nameAr: 'ماوس لاسلكي',
      descriptionEn: 'Ergonomic wireless mouse',
      descriptionAr: 'ماوس لاسلكي مريح',
      sku: 'ELEC-002',
      barcode: null,
      categoryId: CATEGORY_3_ID,
      unitPrice: 89,
      costPrice: 45,
      currency: 'SAR',
      unitOfMeasure: 'pcs',
      reorderPoint: 10,
      taxRate: 15,
      isActive: true,
      images: null,
      productType: 'storable',
      invoicePolicy: 'ordered',
      canBeSold: true,
      canBePurchased: true,
      hasVariants: false,
      hasSerialTracking: false,
      hasLotTracking: true,
      hasExpiryDate: false,
      reorderMinQty: 10,
      reorderQty: 50,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: PRODUCT_5_ID,
      tenantId: TENANT_ID,
      nameEn: 'Consulting Service',
      nameAr: 'خدمة استشارية',
      descriptionEn: 'Professional consulting service per hour',
      descriptionAr: 'خدمة استشارية احترافية بالساعة',
      sku: 'SRV-001',
      barcode: null,
      categoryId: null,
      unitPrice: 500,
      costPrice: null,
      currency: 'SAR',
      unitOfMeasure: 'hrs',
      reorderPoint: 0,
      taxRate: 15,
      isActive: true,
      images: null,
      productType: 'service',
      invoicePolicy: 'delivered',
      canBeSold: true,
      canBePurchased: false,
      hasVariants: false,
      hasSerialTracking: false,
      hasLotTracking: false,
      hasExpiryDate: false,
      reorderMinQty: null,
      reorderQty: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: PRODUCT_6_ID,
      tenantId: TENANT_ID,
      nameEn: 'Beef Burger',
      nameAr: 'برجر لحم',
      descriptionEn: 'Grilled beef burger with fresh ingredients',
      descriptionAr: 'برجر لحم مشوي بمكونات طازجة',
      sku: 'FOOD-002',
      barcode: null,
      categoryId: CATEGORY_1_ID,
      unitPrice: 35,
      costPrice: 18,
      currency: 'SAR',
      unitOfMeasure: 'pcs',
      reorderPoint: 0,
      taxRate: 15,
      isActive: true,
      images: null,
      productType: 'consumable',
      invoicePolicy: 'ordered',
      canBeSold: true,
      canBePurchased: true,
      hasVariants: false,
      hasSerialTracking: false,
      hasLotTracking: false,
      hasExpiryDate: false,
      reorderMinQty: null,
      reorderQty: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: PRODUCT_7_ID,
      tenantId: TENANT_ID,
      nameEn: 'Fresh Orange Juice',
      nameAr: 'عصير برتقال طازج',
      descriptionEn: 'Freshly squeezed orange juice',
      descriptionAr: 'عصير برتقال طازج معصور',
      sku: 'BEV-002',
      barcode: null,
      categoryId: CATEGORY_2_ID,
      unitPrice: 20,
      costPrice: 8,
      currency: 'SAR',
      unitOfMeasure: 'pcs',
      reorderPoint: 0,
      taxRate: 15,
      isActive: true,
      images: null,
      productType: 'consumable',
      invoicePolicy: 'ordered',
      canBeSold: true,
      canBePurchased: true,
      hasVariants: false,
      hasSerialTracking: false,
      hasLotTracking: false,
      hasExpiryDate: false,
      reorderMinQty: null,
      reorderQty: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: PRODUCT_8_ID,
      tenantId: TENANT_ID,
      nameEn: 'iPhone 15 Pro',
      nameAr: 'آيفون 15 برو',
      descriptionEn: 'Apple iPhone 15 Pro smartphone',
      descriptionAr: 'هاتف آبل آيفون 15 برو',
      sku: 'ELEC-003',
      barcode: '6281234567891',
      categoryId: CATEGORY_3_ID,
      unitPrice: 4499,
      costPrice: 3800,
      currency: 'SAR',
      unitOfMeasure: 'pcs',
      reorderPoint: 5,
      taxRate: 15,
      isActive: true,
      images: null,
      productType: 'storable',
      invoicePolicy: 'ordered',
      canBeSold: true,
      canBePurchased: true,
      hasVariants: false,
      hasSerialTracking: true,
      hasLotTracking: false,
      hasExpiryDate: false,
      reorderMinQty: 5,
      reorderQty: 20,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: PRODUCT_9_ID,
      tenantId: TENANT_ID,
      nameEn: 'A4 Paper Box',
      nameAr: 'كرتون ورق A4',
      descriptionEn: 'A4 size paper box - 5 reams',
      descriptionAr: 'كرتون ورق مقاس A4 - 5 رزم',
      sku: 'OFF-001',
      barcode: null,
      categoryId: CATEGORY_4_ID,
      unitPrice: 45,
      costPrice: 30,
      currency: 'SAR',
      unitOfMeasure: 'pcs',
      reorderPoint: 20,
      taxRate: 15,
      isActive: true,
      images: null,
      productType: 'storable',
      invoicePolicy: 'ordered',
      canBeSold: true,
      canBePurchased: true,
      hasVariants: false,
      hasSerialTracking: false,
      hasLotTracking: true,
      hasExpiryDate: false,
      reorderMinQty: 20,
      reorderQty: 100,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: PRODUCT_10_ID,
      tenantId: TENANT_ID,
      nameEn: 'Kunafa',
      nameAr: 'كنافة',
      descriptionEn: 'Traditional Middle Eastern kunafa dessert',
      descriptionAr: 'كنافة شرقية تقليدية',
      sku: 'FOOD-003',
      barcode: null,
      categoryId: CATEGORY_5_ID,
      unitPrice: 30,
      costPrice: 15,
      currency: 'SAR',
      unitOfMeasure: 'pcs',
      reorderPoint: 0,
      taxRate: 15,
      isActive: true,
      images: null,
      productType: 'consumable',
      invoicePolicy: 'ordered',
      canBeSold: true,
      canBePurchased: true,
      hasVariants: false,
      hasSerialTracking: false,
      hasLotTracking: false,
      hasExpiryDate: false,
      reorderMinQty: null,
      reorderQty: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);

  // Stock levels for storable products (BIGINT PK)
  await qi.bulkInsert('stock_levels', [
    {
      tenantId: TENANT_ID,
      productId: PRODUCT_3_ID,
      warehouseId: WAREHOUSE_1_ID,
      quantity: 50,
      reservedQuantity: 0,
      averageCost: 3200.0,
      lastCostPrice: 3200.0,
      currencyId: CURRENCY_SAR_ID,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      tenantId: TENANT_ID,
      productId: PRODUCT_3_ID,
      warehouseId: WAREHOUSE_2_ID,
      quantity: 20,
      reservedQuantity: 0,
      averageCost: 3200.0,
      lastCostPrice: 3200.0,
      currencyId: CURRENCY_SAR_ID,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      tenantId: TENANT_ID,
      productId: PRODUCT_4_ID,
      warehouseId: WAREHOUSE_1_ID,
      quantity: 100,
      reservedQuantity: 5,
      averageCost: 45.0,
      lastCostPrice: 45.0,
      currencyId: CURRENCY_SAR_ID,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      tenantId: TENANT_ID,
      productId: PRODUCT_4_ID,
      warehouseId: WAREHOUSE_2_ID,
      quantity: 30,
      reservedQuantity: 0,
      averageCost: 45.0,
      lastCostPrice: 45.0,
      currencyId: CURRENCY_SAR_ID,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      tenantId: TENANT_ID,
      productId: PRODUCT_8_ID,
      warehouseId: WAREHOUSE_1_ID,
      quantity: 25,
      reservedQuantity: 0,
      averageCost: 3800.0,
      lastCostPrice: 3800.0,
      currencyId: CURRENCY_SAR_ID,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      tenantId: TENANT_ID,
      productId: PRODUCT_8_ID,
      warehouseId: WAREHOUSE_2_ID,
      quantity: 10,
      reservedQuantity: 0,
      averageCost: 3800.0,
      lastCostPrice: 3800.0,
      currencyId: CURRENCY_SAR_ID,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      tenantId: TENANT_ID,
      productId: PRODUCT_9_ID,
      warehouseId: WAREHOUSE_1_ID,
      quantity: 200,
      reservedQuantity: 0,
      averageCost: 30.0,
      lastCostPrice: 30.0,
      currencyId: CURRENCY_SAR_ID,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      tenantId: TENANT_ID,
      productId: PRODUCT_9_ID,
      warehouseId: WAREHOUSE_2_ID,
      quantity: 80,
      reservedQuantity: 0,
      averageCost: 30.0,
      lastCostPrice: 30.0,
      currencyId: CURRENCY_SAR_ID,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
  ]);

  // Stock movements for storable products
  await qi.bulkInsert('stock_movements', [
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      productId: PRODUCT_3_ID,
      warehouseId: WAREHOUSE_1_ID,
      movementType: 'purchase_receipt',
      quantity: 50,
      quantityBefore: 0,
      quantityAfter: 50,
      unitCost: 3200.0,
      totalCost: 160000.0,
      currencyId: CURRENCY_SAR_ID,
      lotNumber: null,
      serialNumber: null,
      expiryDate: null,
      branchId: null,
      notes: null,
      referenceId: null,
      referenceType: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      productId: PRODUCT_3_ID,
      warehouseId: WAREHOUSE_2_ID,
      movementType: 'purchase_receipt',
      quantity: 20,
      quantityBefore: 0,
      quantityAfter: 20,
      unitCost: 3200.0,
      totalCost: 64000.0,
      currencyId: CURRENCY_SAR_ID,
      lotNumber: null,
      serialNumber: null,
      expiryDate: null,
      branchId: null,
      notes: null,
      referenceId: null,
      referenceType: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      productId: PRODUCT_4_ID,
      warehouseId: WAREHOUSE_1_ID,
      movementType: 'purchase_receipt',
      quantity: 100,
      quantityBefore: 0,
      quantityAfter: 100,
      unitCost: 45.0,
      totalCost: 4500.0,
      currencyId: CURRENCY_SAR_ID,
      lotNumber: 'LOT-MOUSE-2026-001',
      serialNumber: null,
      expiryDate: null,
      branchId: null,
      notes: null,
      referenceId: null,
      referenceType: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      productId: PRODUCT_4_ID,
      warehouseId: WAREHOUSE_2_ID,
      movementType: 'internal',
      quantity: 30,
      quantityBefore: 0,
      quantityAfter: 30,
      unitCost: 45.0,
      totalCost: 1350.0,
      currencyId: CURRENCY_SAR_ID,
      lotNumber: null,
      serialNumber: null,
      expiryDate: null,
      branchId: null,
      notes: null,
      referenceId: null,
      referenceType: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      productId: PRODUCT_8_ID,
      warehouseId: WAREHOUSE_1_ID,
      movementType: 'purchase_receipt',
      quantity: 25,
      quantityBefore: 0,
      quantityAfter: 25,
      unitCost: 3800.0,
      totalCost: 95000.0,
      currencyId: CURRENCY_SAR_ID,
      lotNumber: null,
      serialNumber: null,
      expiryDate: null,
      branchId: null,
      notes: null,
      referenceId: null,
      referenceType: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      productId: PRODUCT_8_ID,
      warehouseId: WAREHOUSE_2_ID,
      movementType: 'purchase_receipt',
      quantity: 10,
      quantityBefore: 0,
      quantityAfter: 10,
      unitCost: 3800.0,
      totalCost: 38000.0,
      currencyId: CURRENCY_SAR_ID,
      lotNumber: null,
      serialNumber: null,
      expiryDate: null,
      branchId: null,
      notes: null,
      referenceId: null,
      referenceType: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      productId: PRODUCT_9_ID,
      warehouseId: WAREHOUSE_1_ID,
      movementType: 'purchase_receipt',
      quantity: 200,
      quantityBefore: 0,
      quantityAfter: 200,
      unitCost: 30.0,
      totalCost: 6000.0,
      currencyId: CURRENCY_SAR_ID,
      lotNumber: 'LOT-PAPER-2026-001',
      serialNumber: null,
      expiryDate: null,
      branchId: null,
      notes: null,
      referenceId: null,
      referenceType: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      productId: PRODUCT_9_ID,
      warehouseId: WAREHOUSE_2_ID,
      movementType: 'purchase_receipt',
      quantity: 80,
      quantityBefore: 0,
      quantityAfter: 80,
      unitCost: 30.0,
      totalCost: 2400.0,
      currencyId: CURRENCY_SAR_ID,
      lotNumber: 'LOT-PAPER-2026-002',
      serialNumber: null,
      expiryDate: null,
      branchId: null,
      notes: null,
      referenceId: null,
      referenceType: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
  ]);

  console.log(
    '[06-products] Seeded 5 categories, 4 brands, 10 products, 8 stock levels, and 8 stock movements.',
  );
}
