import { Sequelize } from 'sequelize';
import { v7 as uuidv7 } from 'uuid';

const TENANT_ID = '10000000-0000-0000-0000-000000000001';
const CONTACT_1_ID = '80000000-0000-0000-0000-000000000001';
const CONTACT_2_ID = '80000000-0000-0000-0000-000000000002';
const CONTACT_3_ID = '80000000-0000-0000-0000-000000000003';
const CONTACT_4_ID = '80000000-0000-0000-0000-000000000004';
const CONTACT_5_ID = '80000000-0000-0000-0000-000000000005';
const VENDOR_1_ID = '81000000-0000-0000-0000-000000000001';
const VENDOR_2_ID = '81000000-0000-0000-0000-000000000002';
const VENDOR_3_ID = '81000000-0000-0000-0000-000000000003';
const VENDOR_4_ID = '81000000-0000-0000-0000-000000000004';
const USER_1_ID = '20000000-0000-0000-0000-000000000001';
const BRANCH_1_ID = '30000000-0000-0000-0000-000000000001';
const CURRENCY_SAR_ID = '60000000-0000-0000-0000-000000000001';
const PRODUCT_1_ID = '71000000-0000-0000-0000-000000000001';
const PRODUCT_2_ID = '71000000-0000-0000-0000-000000000002';
const PRODUCT_3_ID = '71000000-0000-0000-0000-000000000003';
const PRODUCT_4_ID = '71000000-0000-0000-0000-000000000004';
const PRODUCT_5_ID = '71000000-0000-0000-0000-000000000005';
const PRODUCT_6_ID = '71000000-0000-0000-0000-000000000006';
const PRODUCT_7_ID = '71000000-0000-0000-0000-000000000007';
const PO_1_ID = '82000000-0000-0000-0000-000000000001';
const PO_2_ID = '82000000-0000-0000-0000-000000000002';
const SO_1_ID = '83000000-0000-0000-0000-000000000001';
const SO_2_ID = '83000000-0000-0000-0000-000000000002';
const SO_3_ID = '83000000-0000-0000-0000-000000000003';
const LEAD_1_ID = '84000000-0000-0000-0000-000000000001';
const LEAD_2_ID = '84000000-0000-0000-0000-000000000002';
const LEAD_3_ID = '84000000-0000-0000-0000-000000000003';
const LEAD_4_ID = '84000000-0000-0000-0000-000000000004';
const LEAD_5_ID = '84000000-0000-0000-0000-000000000005';

export async function seed(sequelize: Sequelize): Promise<void> {
  const qi = sequelize.getQueryInterface();
  const now = new Date();

  // Contacts
  await qi.bulkInsert('contacts', [
    {
      id: CONTACT_1_ID,
      tenantId: TENANT_ID,
      firstName: 'Khalid',
      lastName: 'Al-Saud',
      email: 'khalid@example.com',
      phone: '+966551234567',
      company: 'Saudi Enterprises',
      position: 'CEO',
      notes: null,
      status: 'active',
      assignedTo: USER_1_ID,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: CONTACT_2_ID,
      tenantId: TENANT_ID,
      firstName: 'Fatima',
      lastName: 'Al-Harbi',
      email: 'fatima@example.com',
      phone: '+966559876543',
      company: 'Harbi Trading',
      position: 'Procurement Manager',
      notes: null,
      status: 'active',
      assignedTo: USER_1_ID,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: CONTACT_3_ID,
      tenantId: TENANT_ID,
      firstName: 'Omar',
      lastName: 'Al-Qahtani',
      email: 'omar@example.com',
      phone: '+966552223333',
      company: 'Qahtani Group',
      position: 'CTO',
      notes: null,
      status: 'active',
      assignedTo: USER_1_ID,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: CONTACT_4_ID,
      tenantId: TENANT_ID,
      firstName: 'Nora',
      lastName: 'Al-Dosari',
      email: 'nora@example.com',
      phone: '+966553334444',
      company: 'Dosari Retail',
      position: 'Store Manager',
      notes: null,
      status: 'active',
      assignedTo: USER_1_ID,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: CONTACT_5_ID,
      tenantId: TENANT_ID,
      firstName: 'Youssef',
      lastName: 'Mansour',
      email: 'youssef@example.com',
      phone: '+966554445555',
      company: 'Mansour Holdings',
      position: 'VP Operations',
      notes: null,
      status: 'inactive',
      assignedTo: USER_1_ID,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);

  // Vendors
  await qi.bulkInsert('vendors', [
    {
      id: VENDOR_1_ID,
      tenantId: TENANT_ID,
      nameEn: 'Tech Supplies Co',
      nameAr: 'شركة التوريدات التقنية',
      email: 'info@techsupplies.com',
      phone: '+966112223333',
      address: 'Riyadh, King Abdullah Road',
      taxNumber: '300123456789012',
      isActive: true,
      notes: null,
      currencyId: CURRENCY_SAR_ID,
      paymentTermsDays: 30,
      vatNumber: '300123456789012',
      crNumber: '1010123456',
      bankName: 'Al Rajhi Bank',
      bankIban: 'SA0380000000608010167519',
      rating: 5,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: VENDOR_2_ID,
      tenantId: TENANT_ID,
      nameEn: 'Food Distributors',
      nameAr: 'موزعو الأغذية',
      email: 'orders@fooddist.com',
      phone: '+966113334444',
      address: 'Jeddah, Palestine Street',
      taxNumber: null,
      isActive: true,
      notes: null,
      currencyId: CURRENCY_SAR_ID,
      paymentTermsDays: 15,
      vatNumber: null,
      crNumber: null,
      bankName: 'SNB',
      bankIban: 'SA4420000001234567891234',
      rating: 4,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: VENDOR_3_ID,
      tenantId: TENANT_ID,
      nameEn: 'Office World',
      nameAr: 'عالم المكاتب',
      email: 'sales@officeworld.com',
      phone: '+966114445555',
      address: 'Riyadh, Olaya Street',
      taxNumber: '300987654321098',
      isActive: true,
      notes: null,
      currencyId: CURRENCY_SAR_ID,
      paymentTermsDays: 45,
      vatNumber: '300987654321098',
      crNumber: '1010654321',
      bankName: null,
      bankIban: null,
      rating: 3,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: VENDOR_4_ID,
      tenantId: TENANT_ID,
      nameEn: 'Saudi Paper Co',
      nameAr: 'شركة الورق السعودية',
      email: 'info@saudipaper.com',
      phone: '+966135556666',
      address: 'Dammam, King Fahd Road',
      taxNumber: '300456789012345',
      isActive: true,
      notes: null,
      currencyId: CURRENCY_SAR_ID,
      paymentTermsDays: 30,
      vatNumber: '300456789012345',
      crNumber: '2050987654',
      bankName: 'Alinma Bank',
      bankIban: 'SA0510000000012345678901',
      rating: 4,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);

  // Leads
  await qi.bulkInsert('leads', [
    {
      id: LEAD_1_ID,
      tenantId: TENANT_ID,
      title: 'Enterprise Software Deal',
      contactId: CONTACT_1_ID,
      value: 50000,
      currency: 'SAR',
      currencyId: CURRENCY_SAR_ID,
      valueBase: 50000,
      status: 'qualified',
      priority: 'high',
      assignedTo: USER_1_ID,
      expectedCloseDate: '2026-06-30',
      notes: 'Large enterprise client interested in full ERP suite',
      lostReason: null,
      wonAt: null,
      lostAt: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: LEAD_2_ID,
      tenantId: TENANT_ID,
      title: 'POS System Sale',
      contactId: CONTACT_2_ID,
      value: 15000,
      currency: 'SAR',
      currencyId: CURRENCY_SAR_ID,
      valueBase: 15000,
      status: 'new',
      priority: 'medium',
      assignedTo: USER_1_ID,
      expectedCloseDate: '2026-04-30',
      notes: 'Small retailer looking for POS solution',
      lostReason: null,
      wonAt: null,
      lostAt: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: LEAD_3_ID,
      tenantId: TENANT_ID,
      title: 'Cloud Infrastructure Upgrade',
      contactId: CONTACT_3_ID,
      value: 75000,
      currency: 'SAR',
      currencyId: CURRENCY_SAR_ID,
      valueBase: 75000,
      status: 'proposition',
      priority: 'high',
      assignedTo: USER_1_ID,
      expectedCloseDate: '2026-08-15',
      notes: 'CTO interested in migrating on-premise systems to cloud ERP',
      lostReason: null,
      wonAt: null,
      lostAt: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: LEAD_4_ID,
      tenantId: TENANT_ID,
      title: 'Retail POS Expansion',
      contactId: CONTACT_4_ID,
      value: 8000,
      currency: 'SAR',
      currencyId: CURRENCY_SAR_ID,
      valueBase: 8000,
      status: 'new',
      priority: 'low',
      assignedTo: USER_1_ID,
      expectedCloseDate: '2026-05-15',
      notes: 'Store manager exploring POS options for a new branch',
      lostReason: null,
      wonAt: null,
      lostAt: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: LEAD_5_ID,
      tenantId: TENANT_ID,
      title: 'Supply Chain Automation',
      contactId: CONTACT_5_ID,
      value: 120000,
      currency: 'SAR',
      currencyId: CURRENCY_SAR_ID,
      valueBase: 120000,
      status: 'lost',
      priority: 'high',
      assignedTo: USER_1_ID,
      expectedCloseDate: '2026-03-01',
      notes: 'Lost to competitor — client chose a different vendor',
      lostReason: 'Client chose a competing vendor with lower pricing',
      wonAt: null,
      lostAt: new Date('2026-03-01'),
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);

  // Lead Activities
  await qi.bulkInsert('lead_activities', [
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      leadId: LEAD_1_ID,
      userId: USER_1_ID,
      activityType: 'status_change',
      fromStatus: 'new',
      toStatus: 'qualified',
      notes: 'Initial qualification completed',
      createdBy: USER_1_ID,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      leadId: LEAD_3_ID,
      userId: USER_1_ID,
      activityType: 'status_change',
      fromStatus: 'new',
      toStatus: 'qualified',
      notes: 'Qualified after discovery call',
      createdBy: USER_1_ID,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      leadId: LEAD_3_ID,
      userId: USER_1_ID,
      activityType: 'status_change',
      fromStatus: 'qualified',
      toStatus: 'proposition',
      notes: 'Proposal sent to CTO',
      createdBy: USER_1_ID,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      leadId: LEAD_5_ID,
      userId: USER_1_ID,
      activityType: 'status_change',
      fromStatus: 'qualified',
      toStatus: 'lost',
      notes: 'Client chose a competing vendor with lower pricing',
      createdBy: USER_1_ID,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      leadId: LEAD_1_ID,
      userId: USER_1_ID,
      activityType: 'call',
      fromStatus: null,
      toStatus: null,
      notes: 'Follow-up call with Khalid to discuss pricing options',
      createdBy: USER_1_ID,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      leadId: LEAD_2_ID,
      userId: USER_1_ID,
      activityType: 'meeting',
      fromStatus: null,
      toStatus: null,
      notes: 'On-site demo scheduled at Harbi Trading office',
      createdBy: USER_1_ID,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);

  // Purchase Orders
  await qi.bulkInsert('purchase_orders', [
    {
      id: PO_1_ID,
      tenantId: TENANT_ID,
      orderNumber: 'PO-MAIN-00001',
      vendorId: VENDOR_1_ID,
      branchId: BRANCH_1_ID,
      subtotal: 34250.0,
      taxAmount: 5137.5,
      totalAmount: 39387.5,
      currency: 'SAR',
      currencyId: CURRENCY_SAR_ID,
      exchangeRate: 1,
      totalAmountBase: 39387.5,
      discountAmount: 0,
      status: 'confirmed',
      expectedDeliveryDate: '2026-04-15',
      receivedAt: null,
      invoiceNumber: null,
      notes: null,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: PO_2_ID,
      tenantId: TENANT_ID,
      orderNumber: 'PO-MAIN-00002',
      vendorId: VENDOR_2_ID,
      branchId: BRANCH_1_ID,
      subtotal: 5600.0,
      taxAmount: 840.0,
      totalAmount: 6440.0,
      currency: 'SAR',
      currencyId: CURRENCY_SAR_ID,
      exchangeRate: 1,
      totalAmountBase: 6440.0,
      discountAmount: 0,
      status: 'received',
      expectedDeliveryDate: '2026-03-01',
      receivedAt: new Date('2026-03-01'),
      invoiceNumber: 'INV-FD-2026-001',
      notes: null,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);

  // Purchase Order Lines
  await qi.bulkInsert('purchase_order_lines', [
    {
      tenantId: TENANT_ID,
      orderId: PO_1_ID,
      productId: PRODUCT_3_ID,
      description: 'Product 3 - Bulk Purchase',
      quantity: 10,
      unitPrice: 3200.0,
      taxAmount: 4800.0,
      lineTotal: 36800.0,
      currencyId: CURRENCY_SAR_ID,
      lineTotalBase: 36800.0,
      receivedQuantity: 0,
      discountAmount: 0,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      tenantId: TENANT_ID,
      orderId: PO_1_ID,
      productId: PRODUCT_4_ID,
      description: 'Product 4 - Accessories',
      quantity: 50,
      unitPrice: 45.0,
      taxAmount: 337.5,
      lineTotal: 2587.5,
      currencyId: CURRENCY_SAR_ID,
      lineTotalBase: 2587.5,
      receivedQuantity: 0,
      discountAmount: 0,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      tenantId: TENANT_ID,
      orderId: PO_2_ID,
      productId: PRODUCT_1_ID,
      description: 'Product 1 - Bulk Food Order',
      quantity: 200,
      unitPrice: 12.0,
      taxAmount: 360.0,
      lineTotal: 2760.0,
      currencyId: CURRENCY_SAR_ID,
      lineTotalBase: 2760.0,
      receivedQuantity: 200,
      discountAmount: 0,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      tenantId: TENANT_ID,
      orderId: PO_2_ID,
      productId: PRODUCT_2_ID,
      description: 'Product 2 - Condiments',
      quantity: 100,
      unitPrice: 5.0,
      taxAmount: 75.0,
      lineTotal: 575.0,
      currencyId: CURRENCY_SAR_ID,
      lineTotalBase: 575.0,
      receivedQuantity: 100,
      discountAmount: 0,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      tenantId: TENANT_ID,
      orderId: PO_2_ID,
      productId: PRODUCT_6_ID,
      description: 'Product 6 - Specialty Items',
      quantity: 150,
      unitPrice: 18.0,
      taxAmount: 405.0,
      lineTotal: 3105.0,
      currencyId: CURRENCY_SAR_ID,
      lineTotalBase: 3105.0,
      receivedQuantity: 150,
      discountAmount: 0,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
  ]);

  // Sales Orders
  await qi.bulkInsert('sales_orders', [
    {
      id: SO_1_ID,
      tenantId: TENANT_ID,
      orderNumber: 'SO-MAIN-00001',
      contactId: CONTACT_1_ID,
      branchId: BRANCH_1_ID,
      subtotal: 10498.0,
      discountAmount: 0,
      taxAmount: 1574.7,
      totalAmount: 12072.7,
      currency: 'SAR',
      currencyId: CURRENCY_SAR_ID,
      exchangeRate: 1,
      totalAmountBase: 12072.7,
      discountType: null,
      discountValue: null,
      status: 'confirmed',
      notes: null,
      zatcaUUID: null,
      zatcaInvoiceCounter: null,
      zatcaHash: null,
      zatcaQRCode: null,
      zatcaSignature: null,
      zatcaSubmittedAt: null,
      zatcaClearedAt: null,
      zatcaStatus: null,
      invoiceType: 'standard',
      transactionType: 'invoice',
      supplyType: 'goods',
      taxCategory: 'S',
      taxExemptionCode: null,
      taxExemptionReason: null,
      originalInvoiceId: null,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: SO_2_ID,
      tenantId: TENANT_ID,
      orderNumber: 'SO-MAIN-00002',
      contactId: CONTACT_3_ID,
      branchId: BRANCH_1_ID,
      subtotal: 2390.0,
      discountAmount: 0,
      taxAmount: 358.5,
      totalAmount: 2748.5,
      currency: 'SAR',
      currencyId: CURRENCY_SAR_ID,
      exchangeRate: 1,
      totalAmountBase: 2748.5,
      discountType: null,
      discountValue: null,
      status: 'draft',
      notes: null,
      zatcaUUID: null,
      zatcaInvoiceCounter: null,
      zatcaHash: null,
      zatcaQRCode: null,
      zatcaSignature: null,
      zatcaSubmittedAt: null,
      zatcaClearedAt: null,
      zatcaStatus: null,
      invoiceType: 'standard',
      transactionType: 'invoice',
      supplyType: 'goods',
      taxCategory: 'S',
      taxExemptionCode: null,
      taxExemptionReason: null,
      originalInvoiceId: null,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: SO_3_ID,
      tenantId: TENANT_ID,
      orderNumber: 'SO-MAIN-00003',
      contactId: CONTACT_4_ID,
      branchId: BRANCH_1_ID,
      subtotal: 21000.0,
      discountAmount: 0,
      taxAmount: 3150.0,
      totalAmount: 24150.0,
      currency: 'SAR',
      currencyId: CURRENCY_SAR_ID,
      exchangeRate: 1,
      totalAmountBase: 24150.0,
      discountType: null,
      discountValue: null,
      status: 'invoiced',
      notes: null,
      zatcaUUID: null,
      zatcaInvoiceCounter: null,
      zatcaHash: null,
      zatcaQRCode: null,
      zatcaSignature: null,
      zatcaSubmittedAt: null,
      zatcaClearedAt: null,
      zatcaStatus: null,
      invoiceType: 'standard',
      transactionType: 'invoice',
      supplyType: 'goods',
      taxCategory: 'S',
      taxExemptionCode: null,
      taxExemptionReason: null,
      originalInvoiceId: null,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);

  // Sales Order Lines (BIGINT auto-increment PK — no id)
  await qi.bulkInsert('sales_order_lines', [
    {
      tenantId: TENANT_ID,
      orderId: SO_1_ID,
      productId: PRODUCT_3_ID,
      description: 'Product 3 - Retail Sale',
      quantity: 2,
      unitPrice: 3999.0,
      discountAmount: 0,
      taxRate: 15,
      taxAmount: 1199.7,
      lineTotal: 9197.7,
      currencyId: CURRENCY_SAR_ID,
      lineTotalBase: 9197.7,
      discountType: null,
      discountValue: null,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      tenantId: TENANT_ID,
      orderId: SO_1_ID,
      productId: PRODUCT_5_ID,
      description: 'Product 5 - Service',
      quantity: 5,
      unitPrice: 500.0,
      discountAmount: 0,
      taxRate: 15,
      taxAmount: 375.0,
      lineTotal: 2875.0,
      currencyId: CURRENCY_SAR_ID,
      lineTotalBase: 2875.0,
      discountType: null,
      discountValue: null,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      tenantId: TENANT_ID,
      orderId: SO_2_ID,
      productId: PRODUCT_4_ID,
      description: 'Product 4 - Tech Accessories',
      quantity: 10,
      unitPrice: 89.0,
      discountAmount: 0,
      taxRate: 15,
      taxAmount: 133.5,
      lineTotal: 1023.5,
      currencyId: CURRENCY_SAR_ID,
      lineTotalBase: 1023.5,
      discountType: null,
      discountValue: null,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      tenantId: TENANT_ID,
      orderId: SO_2_ID,
      productId: PRODUCT_5_ID,
      description: 'Product 5 - Consulting Service',
      quantity: 3,
      unitPrice: 500.0,
      discountAmount: 0,
      taxRate: 15,
      taxAmount: 225.0,
      lineTotal: 1725.0,
      currencyId: CURRENCY_SAR_ID,
      lineTotalBase: 1725.0,
      discountType: null,
      discountValue: null,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      tenantId: TENANT_ID,
      orderId: SO_3_ID,
      productId: PRODUCT_1_ID,
      description: 'Product 1 - Wholesale Order',
      quantity: 500,
      unitPrice: 25.0,
      discountAmount: 0,
      taxRate: 15,
      taxAmount: 1875.0,
      lineTotal: 14375.0,
      currencyId: CURRENCY_SAR_ID,
      lineTotalBase: 14375.0,
      discountType: null,
      discountValue: null,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      tenantId: TENANT_ID,
      orderId: SO_3_ID,
      productId: PRODUCT_2_ID,
      description: 'Product 2 - Bulk Retail',
      quantity: 300,
      unitPrice: 15.0,
      discountAmount: 0,
      taxRate: 15,
      taxAmount: 675.0,
      lineTotal: 5175.0,
      currencyId: CURRENCY_SAR_ID,
      lineTotalBase: 5175.0,
      discountType: null,
      discountValue: null,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      tenantId: TENANT_ID,
      orderId: SO_3_ID,
      productId: PRODUCT_7_ID,
      description: 'Product 7 - Premium Items',
      quantity: 200,
      unitPrice: 20.0,
      discountAmount: 0,
      taxRate: 15,
      taxAmount: 600.0,
      lineTotal: 4600.0,
      currencyId: CURRENCY_SAR_ID,
      lineTotalBase: 4600.0,
      discountType: null,
      discountValue: null,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
  ]);

  console.log(
    '[07-crm] Seeded 5 contacts, 4 vendors, 5 leads, 6 lead activities, 2 purchase orders (5 lines), and 3 sales orders (7 lines).',
  );
}
