import { Sequelize } from 'sequelize';
import { v7 as uuidv7 } from 'uuid';

const TENANT_ID = '10000000-0000-0000-0000-000000000001';
const USER_1_ID = '20000000-0000-0000-0000-000000000001';
const USER_2_ID = '20000000-0000-0000-0000-000000000002';
const CURRENCY_SAR_ID = '60000000-0000-0000-0000-000000000001';

// ── Stable Partner IDs ──────────────────────────────────────────────────────
const PARTNER_1_ID = '80000000-0000-0000-0000-000000000001'; // Saudi Enterprises (customer)
const PARTNER_2_ID = '80000000-0000-0000-0000-000000000002'; // Harbi Trading (customer)
const PARTNER_3_ID = '80000000-0000-0000-0000-000000000003'; // Qahtani Group (customer)
const PARTNER_4_ID = '80000000-0000-0000-0000-000000000004'; // Dosari Retail (customer)
const PARTNER_5_ID = '80000000-0000-0000-0000-000000000005'; // Mansour Holdings (customer)
const PARTNER_6_ID = '80000000-0000-0000-0000-000000000006'; // Tech Supplies Co (supplier)
const PARTNER_7_ID = '80000000-0000-0000-0000-000000000007'; // Food Distributors (supplier)
const PARTNER_8_ID = '80000000-0000-0000-0000-000000000008'; // Office World (supplier)
const PARTNER_9_ID = '80000000-0000-0000-0000-000000000009'; // Saudi Paper Co (supplier)
const PARTNER_10_ID = '80000000-0000-0000-0000-00000000000A'; // Al Rajhi Group (both)
const PARTNER_11_ID = '80000000-0000-0000-0000-00000000000B'; // Gulf Logistics (both)
const PARTNER_12_ID = '80000000-0000-0000-0000-00000000000C'; // Nasser Electronics (customer)

// ── Stable CRM Stage IDs ────────────────────────────────────────────────────
const STAGE_NEW_ID = '85000000-0000-0000-0000-000000000001';
const STAGE_CONTACTED_ID = '85000000-0000-0000-0000-000000000002';
const STAGE_QUALIFIED_ID = '85000000-0000-0000-0000-000000000003';
const STAGE_PROPOSAL_ID = '85000000-0000-0000-0000-000000000004';
const STAGE_NEGOTIATION_ID = '85000000-0000-0000-0000-000000000005';
const STAGE_WON_ID = '85000000-0000-0000-0000-000000000006';
const STAGE_LOST_ID = '85000000-0000-0000-0000-000000000007';

// ── Stable Lead IDs ─────────────────────────────────────────────────────────
const LEAD_1_ID = '84000000-0000-0000-0000-000000000001';
const LEAD_2_ID = '84000000-0000-0000-0000-000000000002';
const LEAD_3_ID = '84000000-0000-0000-0000-000000000003';
const LEAD_4_ID = '84000000-0000-0000-0000-000000000004';
const LEAD_5_ID = '84000000-0000-0000-0000-000000000005';
const LEAD_6_ID = '84000000-0000-0000-0000-000000000006';
const LEAD_7_ID = '84000000-0000-0000-0000-000000000007';

export async function seed(sequelize: Sequelize): Promise<void> {
  const qi = sequelize.getQueryInterface();
  const now = new Date();

  // ═══════════════════════════════════════════════════════════════════════════
  // PARTNERS
  // ═══════════════════════════════════════════════════════════════════════════
  await qi.bulkInsert('partners', [
    // Customers
    {
      id: PARTNER_1_ID,
      tenantId: TENANT_ID,
      nameEn: 'Saudi Enterprises',
      nameAr: 'المؤسسات السعودية',
      type: 'customer',
      isCustomer: true,
      isSupplier: false,
      taxNumber: '300111222333012',
      vatNumber: '300111222333012',
      phone: '+966112001001',
      mobile: null,
      email: 'info@saudi-enterprises.com',
      website: 'https://saudi-enterprises.com',
      street: 'King Fahd Road, Al-Olaya District',
      city: 'Riyadh',
      state: 'Riyadh Region',
      country: 'Saudi Arabia',
      zip: '11564',
      creditLimit: 100000,
      paymentTermId: null,
      pricelistId: null,
      arAccountId: null,
      apAccountId: null,
      fiscalPositionId: null,
      bankIban: 'SA0380000000608010167519',
      bankName: 'Al Rajhi Bank',
      notes: 'Flagship client — enterprise ERP suite',
      isActive: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: PARTNER_2_ID,
      tenantId: TENANT_ID,
      nameEn: 'Harbi Trading',
      nameAr: 'حربي للتجارة',
      type: 'customer',
      isCustomer: true,
      isSupplier: false,
      taxNumber: null,
      vatNumber: null,
      phone: '+966112002002',
      mobile: '+966559876543',
      email: 'orders@harbi-trading.com',
      website: null,
      street: 'Palestine Street',
      city: 'Jeddah',
      state: 'Makkah Region',
      country: 'Saudi Arabia',
      zip: '23411',
      creditLimit: 50000,
      paymentTermId: null,
      pricelistId: null,
      arAccountId: null,
      apAccountId: null,
      fiscalPositionId: null,
      bankIban: null,
      bankName: null,
      notes: null,
      isActive: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: PARTNER_3_ID,
      tenantId: TENANT_ID,
      nameEn: 'Qahtani Group',
      nameAr: 'مجموعة القحطاني',
      type: 'customer',
      isCustomer: true,
      isSupplier: false,
      taxNumber: '300444555666012',
      vatNumber: '300444555666012',
      phone: '+966132003003',
      mobile: null,
      email: 'procurement@qahtani-group.com',
      website: 'https://qahtani-group.com',
      street: 'King Abdullah Road',
      city: 'Dammam',
      state: 'Eastern Province',
      country: 'Saudi Arabia',
      zip: '31411',
      creditLimit: 200000,
      paymentTermId: null,
      pricelistId: null,
      arAccountId: null,
      apAccountId: null,
      fiscalPositionId: null,
      bankIban: 'SA4420000001234567891234',
      bankName: 'SNB',
      notes: 'CTO interested in cloud ERP migration',
      isActive: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: PARTNER_4_ID,
      tenantId: TENANT_ID,
      nameEn: 'Dosari Retail',
      nameAr: 'الدوسري للتجزئة',
      type: 'customer',
      isCustomer: true,
      isSupplier: false,
      taxNumber: null,
      vatNumber: null,
      phone: '+966112004004',
      mobile: '+966553334444',
      email: 'manager@dosari-retail.com',
      website: null,
      street: 'Al-Batha Street',
      city: 'Riyadh',
      state: 'Riyadh Region',
      country: 'Saudi Arabia',
      zip: '11564',
      creditLimit: 30000,
      paymentTermId: null,
      pricelistId: null,
      arAccountId: null,
      apAccountId: null,
      fiscalPositionId: null,
      bankIban: null,
      bankName: null,
      notes: null,
      isActive: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: PARTNER_5_ID,
      tenantId: TENANT_ID,
      nameEn: 'Mansour Holdings',
      nameAr: 'منصور القابضة',
      type: 'customer',
      isCustomer: true,
      isSupplier: false,
      taxNumber: '300777888999012',
      vatNumber: '300777888999012',
      phone: '+966112005005',
      mobile: '+966554445555',
      email: 'ops@mansour-holdings.com',
      website: 'https://mansour-holdings.com',
      street: 'Tahlia Street',
      city: 'Jeddah',
      state: 'Makkah Region',
      country: 'Saudi Arabia',
      zip: '23437',
      creditLimit: 150000,
      paymentTermId: null,
      pricelistId: null,
      arAccountId: null,
      apAccountId: null,
      fiscalPositionId: null,
      bankIban: 'SA0510000000012345678901',
      bankName: 'Alinma Bank',
      notes: 'Lost to competitor — may re-engage',
      isActive: false,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    // Suppliers
    {
      id: PARTNER_6_ID,
      tenantId: TENANT_ID,
      nameEn: 'Tech Supplies Co',
      nameAr: 'شركة التوريدات التقنية',
      type: 'supplier',
      isCustomer: false,
      isSupplier: true,
      taxNumber: '300123456789012',
      vatNumber: '300123456789012',
      phone: '+966112223333',
      mobile: null,
      email: 'info@techsupplies.com',
      website: 'https://techsupplies.com',
      street: 'King Abdullah Road',
      city: 'Riyadh',
      state: 'Riyadh Region',
      country: 'Saudi Arabia',
      zip: '11564',
      creditLimit: 0,
      paymentTermId: null,
      pricelistId: null,
      arAccountId: null,
      apAccountId: null,
      fiscalPositionId: null,
      bankIban: 'SA0380000000608010167519',
      bankName: 'Al Rajhi Bank',
      notes: 'Primary IT hardware supplier',
      isActive: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: PARTNER_7_ID,
      tenantId: TENANT_ID,
      nameEn: 'Food Distributors',
      nameAr: 'موزعو الأغذية',
      type: 'supplier',
      isCustomer: false,
      isSupplier: true,
      taxNumber: null,
      vatNumber: null,
      phone: '+966113334444',
      mobile: null,
      email: 'orders@fooddist.com',
      website: null,
      street: 'Palestine Street',
      city: 'Jeddah',
      state: 'Makkah Region',
      country: 'Saudi Arabia',
      zip: '23411',
      creditLimit: 0,
      paymentTermId: null,
      pricelistId: null,
      arAccountId: null,
      apAccountId: null,
      fiscalPositionId: null,
      bankIban: 'SA4420000001234567891234',
      bankName: 'SNB',
      notes: null,
      isActive: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: PARTNER_8_ID,
      tenantId: TENANT_ID,
      nameEn: 'Office World',
      nameAr: 'عالم المكاتب',
      type: 'supplier',
      isCustomer: false,
      isSupplier: true,
      taxNumber: '300987654321098',
      vatNumber: '300987654321098',
      phone: '+966114445555',
      mobile: null,
      email: 'sales@officeworld.com',
      website: 'https://officeworld.com.sa',
      street: 'Olaya Street',
      city: 'Riyadh',
      state: 'Riyadh Region',
      country: 'Saudi Arabia',
      zip: '11564',
      creditLimit: 0,
      paymentTermId: null,
      pricelistId: null,
      arAccountId: null,
      apAccountId: null,
      fiscalPositionId: null,
      bankIban: null,
      bankName: null,
      notes: null,
      isActive: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: PARTNER_9_ID,
      tenantId: TENANT_ID,
      nameEn: 'Saudi Paper Co',
      nameAr: 'شركة الورق السعودية',
      type: 'supplier',
      isCustomer: false,
      isSupplier: true,
      taxNumber: '300456789012345',
      vatNumber: '300456789012345',
      phone: '+966135556666',
      mobile: null,
      email: 'info@saudipaper.com',
      website: null,
      street: 'King Fahd Road',
      city: 'Dammam',
      state: 'Eastern Province',
      country: 'Saudi Arabia',
      zip: '31411',
      creditLimit: 0,
      paymentTermId: null,
      pricelistId: null,
      arAccountId: null,
      apAccountId: null,
      fiscalPositionId: null,
      bankIban: 'SA0510000000012345678901',
      bankName: 'Alinma Bank',
      notes: null,
      isActive: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    // Both (customer + supplier)
    {
      id: PARTNER_10_ID,
      tenantId: TENANT_ID,
      nameEn: 'Al Rajhi Group',
      nameAr: 'مجموعة الراجحي',
      type: 'both',
      isCustomer: true,
      isSupplier: true,
      taxNumber: '300222333444012',
      vatNumber: '300222333444012',
      phone: '+966116667777',
      mobile: null,
      email: 'contact@alrajhi-group.com',
      website: 'https://alrajhi-group.com',
      street: 'King Abdulaziz Road',
      city: 'Riyadh',
      state: 'Riyadh Region',
      country: 'Saudi Arabia',
      zip: '11564',
      creditLimit: 500000,
      paymentTermId: null,
      pricelistId: null,
      arAccountId: null,
      apAccountId: null,
      fiscalPositionId: null,
      bankIban: 'SA0380000000608010167520',
      bankName: 'Al Rajhi Bank',
      notes: 'Strategic partner — both buyer and supplier of IT services',
      isActive: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: PARTNER_11_ID,
      tenantId: TENANT_ID,
      nameEn: 'Gulf Logistics',
      nameAr: 'الخليج للخدمات اللوجستية',
      type: 'both',
      isCustomer: true,
      isSupplier: true,
      taxNumber: '300555666777012',
      vatNumber: '300555666777012',
      phone: '+966138889999',
      mobile: null,
      email: 'ops@gulf-logistics.com',
      website: 'https://gulf-logistics.com',
      street: 'Prince Mohammed Bin Fahd Road',
      city: 'Khobar',
      state: 'Eastern Province',
      country: 'Saudi Arabia',
      zip: '31952',
      creditLimit: 250000,
      paymentTermId: null,
      pricelistId: null,
      arAccountId: null,
      apAccountId: null,
      fiscalPositionId: null,
      bankIban: 'SA4430000001234567891234',
      bankName: 'SABB',
      notes: 'Provides logistics services and also purchases from us',
      isActive: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: PARTNER_12_ID,
      tenantId: TENANT_ID,
      nameEn: 'Nasser Electronics',
      nameAr: 'ناصر للإلكترونيات',
      type: 'customer',
      isCustomer: true,
      isSupplier: false,
      taxNumber: null,
      vatNumber: null,
      phone: '+966112010010',
      mobile: '+966556667777',
      email: 'info@nasser-electronics.com',
      website: null,
      street: 'Al-Khobar Corniche',
      city: 'Khobar',
      state: 'Eastern Province',
      country: 'Saudi Arabia',
      zip: '31952',
      creditLimit: 75000,
      paymentTermId: null,
      pricelistId: null,
      arAccountId: null,
      apAccountId: null,
      fiscalPositionId: null,
      bankIban: null,
      bankName: null,
      notes: null,
      isActive: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);

  // ═══════════════════════════════════════════════════════════════════════════
  // PARTNER CONTACTS
  // ═══════════════════════════════════════════════════════════════════════════
  await qi.bulkInsert('partner_contacts', [
    // Saudi Enterprises contacts
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      partnerId: PARTNER_1_ID,
      firstName: 'Khalid',
      lastName: 'Al-Saud',
      phone: '+966551234567',
      mobile: null,
      email: 'khalid@saudi-enterprises.com',
      position: 'CEO',
      isMain: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      partnerId: PARTNER_1_ID,
      firstName: 'Saleh',
      lastName: 'Al-Otaibi',
      phone: '+966551234568',
      mobile: null,
      email: 'saleh@saudi-enterprises.com',
      position: 'Procurement Director',
      isMain: false,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    // Harbi Trading contacts
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      partnerId: PARTNER_2_ID,
      firstName: 'Fatima',
      lastName: 'Al-Harbi',
      phone: '+966559876543',
      mobile: null,
      email: 'fatima@harbi-trading.com',
      position: 'Procurement Manager',
      isMain: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      partnerId: PARTNER_2_ID,
      firstName: 'Ahmad',
      lastName: 'Al-Harbi',
      phone: '+966559876544',
      mobile: null,
      email: 'ahmad@harbi-trading.com',
      position: 'Operations Manager',
      isMain: false,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    // Qahtani Group contacts
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      partnerId: PARTNER_3_ID,
      firstName: 'Omar',
      lastName: 'Al-Qahtani',
      phone: '+966552223333',
      mobile: null,
      email: 'omar@qahtani-group.com',
      position: 'CTO',
      isMain: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      partnerId: PARTNER_3_ID,
      firstName: 'Layla',
      lastName: 'Al-Qahtani',
      phone: '+966552223334',
      mobile: null,
      email: 'layla@qahtani-group.com',
      position: 'IT Manager',
      isMain: false,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      partnerId: PARTNER_3_ID,
      firstName: 'Majid',
      lastName: 'Al-Qahtani',
      phone: '+966552223335',
      mobile: null,
      email: 'majid@qahtani-group.com',
      position: 'CFO',
      isMain: false,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    // Tech Supplies contacts
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      partnerId: PARTNER_6_ID,
      firstName: 'Hassan',
      lastName: 'Al-Bakr',
      phone: '+966551112222',
      mobile: null,
      email: 'hassan@techsupplies.com',
      position: 'Sales Director',
      isMain: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      partnerId: PARTNER_6_ID,
      firstName: 'Nadia',
      lastName: 'Al-Bakr',
      phone: '+966551112223',
      mobile: null,
      email: 'nadia@techsupplies.com',
      position: 'Account Manager',
      isMain: false,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    // Al Rajhi Group contacts
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      partnerId: PARTNER_10_ID,
      firstName: 'Abdullah',
      lastName: 'Al-Rajhi',
      phone: '+966556667777',
      mobile: null,
      email: 'abdullah@alrajhi-group.com',
      position: 'Managing Director',
      isMain: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      partnerId: PARTNER_10_ID,
      firstName: 'Mona',
      lastName: 'Al-Rajhi',
      phone: '+966556667778',
      mobile: null,
      email: 'mona@alrajhi-group.com',
      position: 'Chief Procurement Officer',
      isMain: false,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);

  // ═══════════════════════════════════════════════════════════════════════════
  // CRM STAGES
  // ═══════════════════════════════════════════════════════════════════════════
  await qi.bulkInsert('crm_stages', [
    {
      id: STAGE_NEW_ID,
      tenantId: TENANT_ID,
      nameEn: 'New',
      nameAr: 'جديد',
      sequence: 1,
      probability: 10,
      isWon: false,
      isFolded: false,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: STAGE_CONTACTED_ID,
      tenantId: TENANT_ID,
      nameEn: 'Contacted',
      nameAr: 'تم التواصل',
      sequence: 2,
      probability: 20,
      isWon: false,
      isFolded: false,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: STAGE_QUALIFIED_ID,
      tenantId: TENANT_ID,
      nameEn: 'Qualified',
      nameAr: 'مؤهل',
      sequence: 3,
      probability: 40,
      isWon: false,
      isFolded: false,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: STAGE_PROPOSAL_ID,
      tenantId: TENANT_ID,
      nameEn: 'Proposal',
      nameAr: 'عرض سعر',
      sequence: 4,
      probability: 60,
      isWon: false,
      isFolded: false,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: STAGE_NEGOTIATION_ID,
      tenantId: TENANT_ID,
      nameEn: 'Negotiation',
      nameAr: 'تفاوض',
      sequence: 5,
      probability: 80,
      isWon: false,
      isFolded: false,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: STAGE_WON_ID,
      tenantId: TENANT_ID,
      nameEn: 'Won',
      nameAr: 'فوز',
      sequence: 6,
      probability: 100,
      isWon: true,
      isFolded: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: STAGE_LOST_ID,
      tenantId: TENANT_ID,
      nameEn: 'Lost',
      nameAr: 'خسارة',
      sequence: 7,
      probability: 0,
      isWon: false,
      isFolded: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);

  // ═══════════════════════════════════════════════════════════════════════════
  // LEADS (using new schema: stageId, partnerId, type)
  // ═══════════════════════════════════════════════════════════════════════════
  await qi.bulkInsert('leads', [
    {
      id: LEAD_1_ID,
      tenantId: TENANT_ID,
      title: 'Enterprise Software Deal',
      stageId: STAGE_QUALIFIED_ID,
      partnerId: PARTNER_1_ID,
      type: 'opportunity',
      probability: 40,
      expectedRevenue: 50000,
      currencyId: CURRENCY_SAR_ID,
      expectedRevenueBase: 50000,
      priority: 'high',
      assignedTo: USER_1_ID,
      expectedCloseDate: '2026-06-30',
      source: 'website',
      campaign: null,
      medium: null,
      tags: null,
      notes: 'Large enterprise client interested in full ERP suite',
      isWon: false,
      isLost: false,
      lostReason: null,
      wonAt: null,
      lostAt: null,
      saleOrderId: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: LEAD_2_ID,
      tenantId: TENANT_ID,
      title: 'POS System Sale',
      stageId: STAGE_NEW_ID,
      partnerId: PARTNER_2_ID,
      type: 'lead',
      probability: 10,
      expectedRevenue: 15000,
      currencyId: CURRENCY_SAR_ID,
      expectedRevenueBase: 15000,
      priority: 'medium',
      assignedTo: USER_1_ID,
      expectedCloseDate: '2026-04-30',
      source: 'referral',
      campaign: null,
      medium: null,
      tags: null,
      notes: 'Small retailer looking for POS solution',
      isWon: false,
      isLost: false,
      lostReason: null,
      wonAt: null,
      lostAt: null,
      saleOrderId: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: LEAD_3_ID,
      tenantId: TENANT_ID,
      title: 'Cloud Infrastructure Upgrade',
      stageId: STAGE_PROPOSAL_ID,
      partnerId: PARTNER_3_ID,
      type: 'opportunity',
      probability: 60,
      expectedRevenue: 75000,
      currencyId: CURRENCY_SAR_ID,
      expectedRevenueBase: 75000,
      priority: 'high',
      assignedTo: USER_1_ID,
      expectedCloseDate: '2026-08-15',
      source: 'website',
      campaign: null,
      medium: null,
      tags: null,
      notes: 'CTO interested in migrating on-premise systems to cloud ERP',
      isWon: false,
      isLost: false,
      lostReason: null,
      wonAt: null,
      lostAt: null,
      saleOrderId: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: LEAD_4_ID,
      tenantId: TENANT_ID,
      title: 'Retail POS Expansion',
      stageId: STAGE_CONTACTED_ID,
      partnerId: PARTNER_4_ID,
      type: 'lead',
      probability: 20,
      expectedRevenue: 8000,
      currencyId: CURRENCY_SAR_ID,
      expectedRevenueBase: 8000,
      priority: 'low',
      assignedTo: USER_2_ID,
      expectedCloseDate: '2026-05-15',
      source: 'cold_call',
      campaign: null,
      medium: null,
      tags: null,
      notes: 'Store manager exploring POS options for a new branch',
      isWon: false,
      isLost: false,
      lostReason: null,
      wonAt: null,
      lostAt: null,
      saleOrderId: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: LEAD_5_ID,
      tenantId: TENANT_ID,
      title: 'Supply Chain Automation',
      stageId: STAGE_LOST_ID,
      partnerId: PARTNER_5_ID,
      type: 'opportunity',
      probability: 0,
      expectedRevenue: 120000,
      currencyId: CURRENCY_SAR_ID,
      expectedRevenueBase: 120000,
      priority: 'high',
      assignedTo: USER_1_ID,
      expectedCloseDate: '2026-03-01',
      source: 'social_media',
      campaign: null,
      medium: null,
      tags: null,
      notes: 'Lost to competitor — client chose a different vendor',
      isWon: false,
      isLost: true,
      lostReason: 'Client chose a competing vendor with lower pricing',
      wonAt: null,
      lostAt: new Date('2026-03-01'),
      saleOrderId: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: LEAD_6_ID,
      tenantId: TENANT_ID,
      title: 'IT Infrastructure Consultation',
      stageId: STAGE_WON_ID,
      partnerId: PARTNER_10_ID,
      type: 'opportunity',
      probability: 100,
      expectedRevenue: 35000,
      currencyId: CURRENCY_SAR_ID,
      expectedRevenueBase: 35000,
      priority: 'high',
      assignedTo: USER_1_ID,
      expectedCloseDate: '2026-02-15',
      source: 'referral',
      campaign: null,
      medium: null,
      tags: null,
      notes: 'Successfully closed — signed annual contract',
      isWon: true,
      isLost: false,
      lostReason: null,
      wonAt: new Date('2026-02-14'),
      lostAt: null,
      saleOrderId: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: LEAD_7_ID,
      tenantId: TENANT_ID,
      title: 'Logistics Software Integration',
      stageId: STAGE_NEGOTIATION_ID,
      partnerId: PARTNER_11_ID,
      type: 'opportunity',
      probability: 80,
      expectedRevenue: 95000,
      currencyId: CURRENCY_SAR_ID,
      expectedRevenueBase: 95000,
      priority: 'high',
      assignedTo: USER_2_ID,
      expectedCloseDate: '2026-04-30',
      source: 'website',
      campaign: null,
      medium: null,
      tags: null,
      notes: 'In final price negotiation — contract terms being reviewed',
      isWon: false,
      isLost: false,
      lostReason: null,
      wonAt: null,
      lostAt: null,
      saleOrderId: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);

  // ═══════════════════════════════════════════════════════════════════════════
  // LEAD ACTIVITIES (using stageId references)
  // ═══════════════════════════════════════════════════════════════════════════
  await qi.bulkInsert('lead_activities', [
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      leadId: LEAD_1_ID,
      userId: USER_1_ID,
      activityType: 'stage_change',
      fromStageId: STAGE_NEW_ID,
      toStageId: STAGE_QUALIFIED_ID,
      notes: 'Initial qualification completed',
      createdBy: USER_1_ID,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      leadId: LEAD_3_ID,
      userId: USER_1_ID,
      activityType: 'stage_change',
      fromStageId: STAGE_NEW_ID,
      toStageId: STAGE_QUALIFIED_ID,
      notes: 'Qualified after discovery call',
      createdBy: USER_1_ID,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      leadId: LEAD_3_ID,
      userId: USER_1_ID,
      activityType: 'stage_change',
      fromStageId: STAGE_QUALIFIED_ID,
      toStageId: STAGE_PROPOSAL_ID,
      notes: 'Proposal sent to CTO',
      createdBy: USER_1_ID,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      leadId: LEAD_5_ID,
      userId: USER_1_ID,
      activityType: 'stage_change',
      fromStageId: STAGE_QUALIFIED_ID,
      toStageId: STAGE_LOST_ID,
      notes: 'Client chose a competing vendor with lower pricing',
      createdBy: USER_1_ID,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      leadId: LEAD_6_ID,
      userId: USER_1_ID,
      activityType: 'stage_change',
      fromStageId: STAGE_NEGOTIATION_ID,
      toStageId: STAGE_WON_ID,
      notes: 'Contract signed — annual deal',
      createdBy: USER_1_ID,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      leadId: LEAD_1_ID,
      userId: USER_1_ID,
      activityType: 'call',
      fromStageId: null,
      toStageId: null,
      notes: 'Follow-up call with Khalid to discuss pricing options',
      createdBy: USER_1_ID,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      leadId: LEAD_2_ID,
      userId: USER_1_ID,
      activityType: 'meeting',
      fromStageId: null,
      toStageId: null,
      notes: 'On-site demo scheduled at Harbi Trading office',
      createdBy: USER_1_ID,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      leadId: LEAD_7_ID,
      userId: USER_2_ID,
      activityType: 'email',
      fromStageId: null,
      toStageId: null,
      notes: 'Sent revised pricing proposal to Gulf Logistics team',
      createdBy: USER_2_ID,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);

  // NOTE: Sales orders and purchase orders are seeded in 23-sales-orders.seed.ts
  // and 24-purchase-orders.seed.ts respectively.

  console.log(
    '[07-crm] Seeded 12 partners, 11 partner contacts, 7 CRM stages, 7 leads, 8 lead activities.',
  );
}

// Re-export IDs for downstream seeders
export {
  PARTNER_1_ID,
  PARTNER_2_ID,
  PARTNER_3_ID,
  PARTNER_4_ID,
  PARTNER_5_ID,
  PARTNER_6_ID,
  PARTNER_7_ID,
  PARTNER_8_ID,
  PARTNER_9_ID,
  PARTNER_10_ID,
  PARTNER_11_ID,
  PARTNER_12_ID,
  STAGE_NEW_ID,
  STAGE_CONTACTED_ID,
  STAGE_QUALIFIED_ID,
  STAGE_PROPOSAL_ID,
  STAGE_NEGOTIATION_ID,
  STAGE_WON_ID,
  STAGE_LOST_ID,
  LEAD_1_ID,
  LEAD_2_ID,
  LEAD_3_ID,
  LEAD_4_ID,
  LEAD_5_ID,
  LEAD_6_ID,
  LEAD_7_ID,
};
