import { Sequelize } from 'sequelize';
import { v7 as uuidv7 } from 'uuid';

const TENANT_ID = '10000000-0000-0000-0000-000000000001';
const USER_1_ID = '20000000-0000-0000-0000-000000000001';
const USER_2_ID = '20000000-0000-0000-0000-000000000002';
const USER_3_ID = '20000000-0000-0000-0000-000000000003';
const BRANCH_1_ID = '30000000-0000-0000-0000-000000000001';
const BRANCH_2_ID = '30000000-0000-0000-0000-000000000002';
const DEPT_1_ID = '50000000-0000-0000-0000-000000000001';
const DEPT_3_ID = '50000000-0000-0000-0000-000000000003';

const EMPLOYEE_1_ID = '90000000-0000-0000-0000-000000000001';
const EMPLOYEE_2_ID = '90000000-0000-0000-0000-000000000002';
const EMPLOYEE_3_ID = '90000000-0000-0000-0000-000000000003';

const SHIFT_1_ID = 'F0000000-0000-0000-0000-000000000001';
const SHIFT_2_ID = 'F0000000-0000-0000-0000-000000000002';

const CONTRACT_1_ID = '91000000-0000-0000-0000-000000000001';
const CONTRACT_2_ID = '91000000-0000-0000-0000-000000000002';
const CONTRACT_3_ID = '91000000-0000-0000-0000-000000000003';

const PAYROLL_RUN_ID = '92000000-0000-0000-0000-000000000001';
const PAYROLL_RUN_2_ID = '92000000-0000-0000-0000-000000000002';

const LEAVE_1_ID = '93000000-0000-0000-0000-000000000001';
const LEAVE_2_ID = '93000000-0000-0000-0000-000000000002';
const LEAVE_3_ID = '93000000-0000-0000-0000-000000000003';

// Job Positions
const JOB_POS_1_ID = '90300000-0000-0000-0000-000000000001'; // Sales Manager
const JOB_POS_2_ID = '90300000-0000-0000-0000-000000000002'; // Cashier
const JOB_POS_3_ID = '90300000-0000-0000-0000-000000000003'; // IT Specialist

// Salary Structures
const SALARY_STRUCT_SAUDI_ID = '90400000-0000-0000-0000-000000000001';
const SALARY_STRUCT_NON_SAUDI_ID = '90400000-0000-0000-0000-000000000002';

// Leave Types
const LEAVE_TYPE_ANNUAL_ID = '90500000-0000-0000-0000-000000000001';
const LEAVE_TYPE_SICK_ID = '90500000-0000-0000-0000-000000000002';
const LEAVE_TYPE_EMERGENCY_ID = '90500000-0000-0000-0000-000000000003';
const LEAVE_TYPE_MATERNITY_ID = '90500000-0000-0000-0000-000000000004';
const LEAVE_TYPE_UNPAID_ID = '90500000-0000-0000-0000-000000000005';

// Payslips
const PAYSLIP_1_ID = '94000000-0000-0000-0000-000000000001';
const PAYSLIP_2_ID = '94000000-0000-0000-0000-000000000002';

export async function seed(sequelize: Sequelize): Promise<void> {
  const qi = sequelize.getQueryInterface();
  const now = new Date();

  // ═══════════════════════════════════════════════════════════════════════════
  // JOB POSITIONS
  // ═══════════════════════════════════════════════════════════════════════════
  await qi.bulkInsert('job_positions', [
    {
      id: JOB_POS_1_ID,
      tenantId: TENANT_ID,
      nameEn: 'Sales Manager',
      nameAr: 'مدير مبيعات',
      departmentId: DEPT_1_ID,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: JOB_POS_2_ID,
      tenantId: TENANT_ID,
      nameEn: 'Cashier',
      nameAr: 'كاشير',
      departmentId: DEPT_1_ID,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: JOB_POS_3_ID,
      tenantId: TENANT_ID,
      nameEn: 'IT Specialist',
      nameAr: 'أخصائي تقنية',
      departmentId: DEPT_3_ID,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);

  // ═══════════════════════════════════════════════════════════════════════════
  // EMPLOYEES (new schema: nameEn, nameAr, employeeCode, jobPositionId — no salary fields)
  // ═══════════════════════════════════════════════════════════════════════════
  await qi.bulkInsert('employees', [
    {
      id: EMPLOYEE_1_ID,
      tenantId: TENANT_ID,
      userId: USER_1_ID,
      departmentId: DEPT_1_ID,
      branchId: BRANCH_1_ID,
      nameEn: 'Ahmed Al-Rashid',
      nameAr: 'أحمد الراشد',
      employeeCode: 'EMP-001',
      jobPositionId: JOB_POS_1_ID,
      positionEn: 'Sales Manager',
      positionAr: 'مدير مبيعات',
      employmentType: 'full-time',
      hireDate: '2024-01-15',
      terminationDate: null,
      salaryCurrency: 'SAR',
      employeeNumber: 'EMP-001',
      managerId: null,
      nationality: 'SA',
      isSaudi: true,
      nationalId: '1098765432',
      birthDate: '1990-05-15',
      gender: 'male',
      maritalStatus: 'married',
      emergencyContact: 'Mohammed Al-Rashid',
      emergencyPhone: '+966501234567',
      bankAccount: 'SA0380000000608010167519',
      bankName: 'Al Rajhi Bank',
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: EMPLOYEE_2_ID,
      tenantId: TENANT_ID,
      userId: USER_2_ID,
      departmentId: DEPT_1_ID,
      branchId: BRANCH_1_ID,
      nameEn: 'Sara Al-Otaibi',
      nameAr: 'سارة العتيبي',
      employeeCode: 'EMP-002',
      jobPositionId: JOB_POS_2_ID,
      positionEn: 'Cashier',
      positionAr: 'كاشير',
      employmentType: 'full-time',
      hireDate: '2024-03-01',
      terminationDate: null,
      salaryCurrency: 'SAR',
      employeeNumber: 'EMP-002',
      managerId: EMPLOYEE_1_ID,
      nationality: 'SA',
      isSaudi: true,
      nationalId: '1087654321',
      birthDate: '1995-08-20',
      gender: 'female',
      maritalStatus: 'single',
      emergencyContact: 'Fatima Al-Otaibi',
      emergencyPhone: '+966509876543',
      bankAccount: 'SA4420000001234567891234',
      bankName: 'SNB',
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: EMPLOYEE_3_ID,
      tenantId: TENANT_ID,
      userId: USER_3_ID,
      departmentId: DEPT_3_ID,
      branchId: BRANCH_2_ID,
      nameEn: 'Ali Khan',
      nameAr: 'علي خان',
      employeeCode: 'EMP-003',
      jobPositionId: JOB_POS_3_ID,
      positionEn: 'IT Specialist',
      positionAr: 'أخصائي تقنية',
      employmentType: 'full-time',
      hireDate: '2024-06-01',
      terminationDate: null,
      salaryCurrency: 'SAR',
      employeeNumber: 'EMP-003',
      managerId: null,
      nationality: 'PK',
      isSaudi: false,
      nationalId: '2398765432',
      birthDate: '1988-11-10',
      gender: 'male',
      maritalStatus: 'married',
      emergencyContact: 'Hassan Khan',
      emergencyPhone: '+966551234567',
      bankAccount: 'SA5510000000123456789012',
      bankName: 'Riyad Bank',
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);

  // ═══════════════════════════════════════════════════════════════════════════
  // SHIFTS
  // ═══════════════════════════════════════════════════════════════════════════
  await qi.bulkInsert('shifts', [
    {
      id: SHIFT_1_ID,
      tenantId: TENANT_ID,
      nameEn: 'Morning Shift',
      nameAr: 'دوام صباحي',
      descriptionEn: 'Standard morning work shift',
      descriptionAr: 'دوام صباحي عادي',
      startTime: '08:00',
      endTime: '16:00',
      breakMinutes: 60,
      isOvernight: false,
      workingDays: JSON.stringify([0, 1, 2, 3, 4]),
      isActive: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: SHIFT_2_ID,
      tenantId: TENANT_ID,
      nameEn: 'Evening Shift',
      nameAr: 'دوام مسائي',
      descriptionEn: 'Standard evening work shift',
      descriptionAr: 'دوام مسائي عادي',
      startTime: '16:00',
      endTime: '00:00',
      breakMinutes: 30,
      isOvernight: false,
      workingDays: JSON.stringify([0, 1, 2, 3, 4]),
      isActive: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);

  // ═══════════════════════════════════════════════════════════════════════════
  // SHIFT WORKING DAYS (Sun=0, Mon=1, Tue=2, Wed=3, Thu=4 for both shifts)
  // ═══════════════════════════════════════════════════════════════════════════
  const shiftWorkingDays = [];
  for (const shiftId of [SHIFT_1_ID, SHIFT_2_ID]) {
    for (const dayOfWeek of [0, 1, 2, 3, 4]) {
      shiftWorkingDays.push({
        id: uuidv7(),
        tenantId: TENANT_ID,
        shiftId,
        dayOfWeek,
        createdBy: null,
        updatedBy: null,
        version: 0,
        createdAt: now,
        updatedAt: now,
        deletedAt: null,
      });
    }
  }
  await qi.bulkInsert('shift_working_days', shiftWorkingDays);

  // ═══════════════════════════════════════════════════════════════════════════
  // SALARY STRUCTURES
  // ═══════════════════════════════════════════════════════════════════════════
  await qi.bulkInsert('salary_structures', [
    {
      id: SALARY_STRUCT_SAUDI_ID,
      tenantId: TENANT_ID,
      nameEn: 'Saudi Standard',
      nameAr: 'الهيكل السعودي القياسي',
      type: 'employee',
      parentId: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: SALARY_STRUCT_NON_SAUDI_ID,
      tenantId: TENANT_ID,
      nameEn: 'Non-Saudi Standard',
      nameAr: 'هيكل غير السعوديين القياسي',
      type: 'employee',
      parentId: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);

  // ═══════════════════════════════════════════════════════════════════════════
  // SALARY RULES — Saudi Standard Structure
  // BASIC, HRA, TRANS, GROSS, GOSI_EMP (9.75%), GOSI_EMPLOYER (11.75%), NET
  // ═══════════════════════════════════════════════════════════════════════════
  await qi.bulkInsert('salary_rules', [
    // --- Saudi Structure Rules ---
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      structureId: SALARY_STRUCT_SAUDI_ID,
      sequence: 10,
      code: 'BASIC',
      nameEn: 'Basic Salary',
      nameAr: 'الراتب الأساسي',
      category: 'earnings',
      conditionType: 'always',
      conditionPython: null,
      computationType: 'contract',
      amount: null,
      percentBase: null,
      percentValue: null,
      codePython: null,
      appearsOnPayslip: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      structureId: SALARY_STRUCT_SAUDI_ID,
      sequence: 20,
      code: 'HRA',
      nameEn: 'Housing Allowance',
      nameAr: 'بدل سكن',
      category: 'earnings',
      conditionType: 'always',
      conditionPython: null,
      computationType: 'percentage',
      amount: null,
      percentBase: 'BASIC',
      percentValue: 25.0,
      codePython: null,
      appearsOnPayslip: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      structureId: SALARY_STRUCT_SAUDI_ID,
      sequence: 30,
      code: 'TRANS',
      nameEn: 'Transportation Allowance',
      nameAr: 'بدل نقل',
      category: 'earnings',
      conditionType: 'always',
      conditionPython: null,
      computationType: 'percentage',
      amount: null,
      percentBase: 'BASIC',
      percentValue: 10.0,
      codePython: null,
      appearsOnPayslip: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      structureId: SALARY_STRUCT_SAUDI_ID,
      sequence: 100,
      code: 'GROSS',
      nameEn: 'Gross Salary',
      nameAr: 'إجمالي الراتب',
      category: 'gross',
      conditionType: 'always',
      conditionPython: null,
      computationType: 'code',
      amount: null,
      percentBase: null,
      percentValue: null,
      codePython: 'result = BASIC + HRA + TRANS',
      appearsOnPayslip: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      structureId: SALARY_STRUCT_SAUDI_ID,
      sequence: 200,
      code: 'GOSI_EMP',
      nameEn: 'GOSI (Employee)',
      nameAr: 'التأمينات الاجتماعية (الموظف)',
      category: 'deductions',
      conditionType: 'always',
      conditionPython: null,
      computationType: 'percentage',
      amount: null,
      percentBase: 'BASIC',
      percentValue: 9.75,
      codePython: null,
      appearsOnPayslip: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      structureId: SALARY_STRUCT_SAUDI_ID,
      sequence: 210,
      code: 'GOSI_ER',
      nameEn: 'GOSI (Employer)',
      nameAr: 'التأمينات الاجتماعية (صاحب العمل)',
      category: 'employer',
      conditionType: 'always',
      conditionPython: null,
      computationType: 'percentage',
      amount: null,
      percentBase: 'BASIC',
      percentValue: 11.75,
      codePython: null,
      appearsOnPayslip: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      structureId: SALARY_STRUCT_SAUDI_ID,
      sequence: 999,
      code: 'NET',
      nameEn: 'Net Salary',
      nameAr: 'صافي الراتب',
      category: 'net',
      conditionType: 'always',
      conditionPython: null,
      computationType: 'code',
      amount: null,
      percentBase: null,
      percentValue: null,
      codePython: 'result = GROSS - GOSI_EMP',
      appearsOnPayslip: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },

    // --- Non-Saudi Structure Rules ---
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      structureId: SALARY_STRUCT_NON_SAUDI_ID,
      sequence: 10,
      code: 'BASIC',
      nameEn: 'Basic Salary',
      nameAr: 'الراتب الأساسي',
      category: 'earnings',
      conditionType: 'always',
      conditionPython: null,
      computationType: 'contract',
      amount: null,
      percentBase: null,
      percentValue: null,
      codePython: null,
      appearsOnPayslip: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      structureId: SALARY_STRUCT_NON_SAUDI_ID,
      sequence: 20,
      code: 'HRA',
      nameEn: 'Housing Allowance',
      nameAr: 'بدل سكن',
      category: 'earnings',
      conditionType: 'always',
      conditionPython: null,
      computationType: 'percentage',
      amount: null,
      percentBase: 'BASIC',
      percentValue: 25.0,
      codePython: null,
      appearsOnPayslip: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      structureId: SALARY_STRUCT_NON_SAUDI_ID,
      sequence: 30,
      code: 'TRANS',
      nameEn: 'Transportation Allowance',
      nameAr: 'بدل نقل',
      category: 'earnings',
      conditionType: 'always',
      conditionPython: null,
      computationType: 'percentage',
      amount: null,
      percentBase: 'BASIC',
      percentValue: 10.0,
      codePython: null,
      appearsOnPayslip: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      structureId: SALARY_STRUCT_NON_SAUDI_ID,
      sequence: 100,
      code: 'GROSS',
      nameEn: 'Gross Salary',
      nameAr: 'إجمالي الراتب',
      category: 'gross',
      conditionType: 'always',
      conditionPython: null,
      computationType: 'code',
      amount: null,
      percentBase: null,
      percentValue: null,
      codePython: 'result = BASIC + HRA + TRANS',
      appearsOnPayslip: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      structureId: SALARY_STRUCT_NON_SAUDI_ID,
      sequence: 200,
      code: 'GOSI_EMP',
      nameEn: 'GOSI (Employee)',
      nameAr: 'التأمينات الاجتماعية (الموظف)',
      category: 'deductions',
      conditionType: 'always',
      conditionPython: null,
      computationType: 'fixed',
      amount: 0,
      percentBase: null,
      percentValue: null,
      codePython: null,
      appearsOnPayslip: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      structureId: SALARY_STRUCT_NON_SAUDI_ID,
      sequence: 210,
      code: 'GOSI_ER',
      nameEn: 'GOSI (Employer)',
      nameAr: 'التأمينات الاجتماعية (صاحب العمل)',
      category: 'employer',
      conditionType: 'always',
      conditionPython: null,
      computationType: 'percentage',
      amount: null,
      percentBase: 'BASIC',
      percentValue: 11.75,
      codePython: null,
      appearsOnPayslip: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      structureId: SALARY_STRUCT_NON_SAUDI_ID,
      sequence: 999,
      code: 'NET',
      nameEn: 'Net Salary',
      nameAr: 'صافي الراتب',
      category: 'net',
      conditionType: 'always',
      conditionPython: null,
      computationType: 'code',
      amount: null,
      percentBase: null,
      percentValue: null,
      codePython: 'result = GROSS - GOSI_EMP',
      appearsOnPayslip: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);

  // ═══════════════════════════════════════════════════════════════════════════
  // EMPLOYEE CONTRACTS (with salary fields, salaryStructureId, wageType, workingScheduleId)
  // ═══════════════════════════════════════════════════════════════════════════
  await qi.bulkInsert('employee_contracts', [
    {
      id: CONTRACT_1_ID,
      tenantId: TENANT_ID,
      employeeId: EMPLOYEE_1_ID,
      contractType: 'full_time',
      startDate: '2024-01-15',
      endDate: '2026-01-14',
      basicSalary: 15000,
      housingAllowance: 3750,
      transportationAllowance: 1500,
      salaryStructureId: SALARY_STRUCT_SAUDI_ID,
      wageType: 'monthly',
      wage: 20250,
      workingScheduleId: SHIFT_1_ID,
      status: 'active',
      notes: 'Initial employment contract',
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: CONTRACT_2_ID,
      tenantId: TENANT_ID,
      employeeId: EMPLOYEE_2_ID,
      contractType: 'full_time',
      startDate: '2024-03-01',
      endDate: '2026-02-28',
      basicSalary: 5000,
      housingAllowance: 1250,
      transportationAllowance: 500,
      salaryStructureId: SALARY_STRUCT_SAUDI_ID,
      wageType: 'monthly',
      wage: 6750,
      workingScheduleId: SHIFT_1_ID,
      status: 'active',
      notes: null,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: CONTRACT_3_ID,
      tenantId: TENANT_ID,
      employeeId: EMPLOYEE_3_ID,
      contractType: 'full_time',
      startDate: '2024-06-01',
      endDate: '2026-05-31',
      basicSalary: 10000,
      housingAllowance: 2500,
      transportationAllowance: 1000,
      salaryStructureId: SALARY_STRUCT_NON_SAUDI_ID,
      wageType: 'monthly',
      wage: 13500,
      workingScheduleId: SHIFT_1_ID,
      status: 'active',
      notes: null,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);

  // ═══════════════════════════════════════════════════════════════════════════
  // LEAVE TYPES
  // ═══════════════════════════════════════════════════════════════════════════
  await qi.bulkInsert('leave_types', [
    {
      id: LEAVE_TYPE_ANNUAL_ID,
      tenantId: TENANT_ID,
      nameEn: 'Annual Leave',
      nameAr: 'إجازة سنوية',
      color: '#4CAF50',
      requiresApproval: true,
      allowNegative: false,
      isActive: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: LEAVE_TYPE_SICK_ID,
      tenantId: TENANT_ID,
      nameEn: 'Sick Leave',
      nameAr: 'إجازة مرضية',
      color: '#F44336',
      requiresApproval: true,
      allowNegative: false,
      isActive: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: LEAVE_TYPE_EMERGENCY_ID,
      tenantId: TENANT_ID,
      nameEn: 'Emergency Leave',
      nameAr: 'إجازة طوارئ',
      color: '#FF9800',
      requiresApproval: false,
      allowNegative: true,
      isActive: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: LEAVE_TYPE_MATERNITY_ID,
      tenantId: TENANT_ID,
      nameEn: 'Maternity Leave',
      nameAr: 'إجازة أمومة',
      color: '#E91E63',
      requiresApproval: true,
      allowNegative: false,
      isActive: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: LEAVE_TYPE_UNPAID_ID,
      tenantId: TENANT_ID,
      nameEn: 'Unpaid Leave',
      nameAr: 'إجازة بدون راتب',
      color: '#9E9E9E',
      requiresApproval: true,
      allowNegative: false,
      isActive: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);

  // ═══════════════════════════════════════════════════════════════════════════
  // LEAVE ALLOCATIONS (annual allocation per employee per leave type, 2026)
  // ═══════════════════════════════════════════════════════════════════════════
  const leaveAllocations = [];
  const allocationConfig = [
    { leaveTypeId: LEAVE_TYPE_ANNUAL_ID, days: 21 },
    { leaveTypeId: LEAVE_TYPE_SICK_ID, days: 30 },
    { leaveTypeId: LEAVE_TYPE_EMERGENCY_ID, days: 5 },
  ];
  const employees = [
    { id: EMPLOYEE_1_ID, branchId: BRANCH_1_ID },
    { id: EMPLOYEE_2_ID, branchId: BRANCH_1_ID },
    { id: EMPLOYEE_3_ID, branchId: BRANCH_2_ID },
  ];

  for (const emp of employees) {
    for (const alloc of allocationConfig) {
      leaveAllocations.push({
        id: uuidv7(),
        tenantId: TENANT_ID,
        branchId: emp.branchId,
        employeeId: emp.id,
        leaveTypeId: alloc.leaveTypeId,
        year: 2026,
        numberOfDays: alloc.days,
        mode: 'manual',
        status: 'approved',
        approvedById: USER_1_ID,
        approvedAt: '2026-01-01T00:00:00+03:00',
        createdBy: USER_1_ID,
        updatedBy: USER_1_ID,
        version: 0,
        createdAt: now,
        updatedAt: now,
        deletedAt: null,
      });
    }
  }
  await qi.bulkInsert('leave_allocations', leaveAllocations);

  // ═══════════════════════════════════════════════════════════════════════════
  // ATTENDANCE RECORDS (3 employees x 3 days = 9 records)
  // ═══════════════════════════════════════════════════════════════════════════
  await qi.bulkInsert('attendance_records', [
    // === 2026-03-13 ===
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      employeeId: EMPLOYEE_1_ID,
      date: '2026-03-13',
      clockIn: '2026-03-13T08:00:00+03:00',
      clockOut: '2026-03-13T16:05:00+03:00',
      status: 'present',
      lateMinutes: 0,
      overtimeMinutes: 5,
      workingHours: 8.08,
      notes: null,
      source: 'manual',
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      employeeId: EMPLOYEE_2_ID,
      date: '2026-03-13',
      clockIn: '2026-03-13T08:12:00+03:00',
      clockOut: '2026-03-13T16:00:00+03:00',
      status: 'late',
      lateMinutes: 12,
      overtimeMinutes: 0,
      workingHours: 7.8,
      notes: 'Traffic delay',
      source: 'manual',
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      employeeId: EMPLOYEE_3_ID,
      date: '2026-03-13',
      clockIn: '2026-03-13T07:55:00+03:00',
      clockOut: '2026-03-13T16:00:00+03:00',
      status: 'present',
      lateMinutes: 0,
      overtimeMinutes: 0,
      workingHours: 8.08,
      notes: null,
      source: 'device',
      createdBy: USER_3_ID,
      updatedBy: USER_3_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    // === 2026-03-12 ===
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      employeeId: EMPLOYEE_1_ID,
      date: '2026-03-12',
      clockIn: '2026-03-12T08:00:00+03:00',
      clockOut: '2026-03-12T16:10:00+03:00',
      status: 'present',
      lateMinutes: 0,
      overtimeMinutes: 10,
      workingHours: 8.17,
      notes: null,
      source: 'manual',
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      employeeId: EMPLOYEE_2_ID,
      date: '2026-03-12',
      clockIn: null,
      clockOut: null,
      status: 'absent',
      lateMinutes: 0,
      overtimeMinutes: 0,
      workingHours: 0,
      notes: null,
      source: 'manual',
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      employeeId: EMPLOYEE_3_ID,
      date: '2026-03-12',
      clockIn: '2026-03-12T07:50:00+03:00',
      clockOut: '2026-03-12T16:00:00+03:00',
      status: 'present',
      lateMinutes: 0,
      overtimeMinutes: 0,
      workingHours: 8.17,
      notes: null,
      source: 'device',
      createdBy: USER_3_ID,
      updatedBy: USER_3_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    // === 2026-03-11 ===
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      employeeId: EMPLOYEE_1_ID,
      date: '2026-03-11',
      clockIn: '2026-03-11T08:05:00+03:00',
      clockOut: '2026-03-11T16:30:00+03:00',
      status: 'late',
      lateMinutes: 5,
      overtimeMinutes: 25,
      workingHours: 8.42,
      notes: null,
      source: 'manual',
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      employeeId: EMPLOYEE_2_ID,
      date: '2026-03-11',
      clockIn: '2026-03-11T08:00:00+03:00',
      clockOut: '2026-03-11T16:00:00+03:00',
      status: 'present',
      lateMinutes: 0,
      overtimeMinutes: 0,
      workingHours: 8.0,
      notes: null,
      source: 'manual',
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      employeeId: EMPLOYEE_3_ID,
      date: '2026-03-11',
      clockIn: '2026-03-11T08:20:00+03:00',
      clockOut: '2026-03-11T16:00:00+03:00',
      status: 'late',
      lateMinutes: 20,
      overtimeMinutes: 0,
      workingHours: 7.67,
      notes: null,
      source: 'device',
      createdBy: USER_3_ID,
      updatedBy: USER_3_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
  ]);

  // ═══════════════════════════════════════════════════════════════════════════
  // LEAVE REQUESTS (now with leaveTypeId)
  // ═══════════════════════════════════════════════════════════════════════════
  await qi.bulkInsert('leave_requests', [
    {
      id: LEAVE_1_ID,
      tenantId: TENANT_ID,
      employeeId: EMPLOYEE_2_ID,
      leaveType: 'annual',
      leaveTypeId: LEAVE_TYPE_ANNUAL_ID,
      startDate: '2026-03-20',
      endDate: '2026-03-24',
      daysRequested: 3,
      reason: 'Family vacation',
      status: 'approved',
      approvedBy: USER_1_ID,
      approvedAt: '2026-03-10T10:30:00+03:00',
      rejectionReason: null,
      isHalfDay: false,
      halfDayPeriod: null,
      refusalReason: null,
      createdBy: USER_2_ID,
      updatedBy: USER_1_ID,
      version: 1,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: LEAVE_2_ID,
      tenantId: TENANT_ID,
      employeeId: EMPLOYEE_3_ID,
      leaveType: 'sick',
      leaveTypeId: LEAVE_TYPE_SICK_ID,
      startDate: '2026-03-05',
      endDate: '2026-03-06',
      daysRequested: 2,
      reason: 'Medical appointment and recovery',
      status: 'approved',
      approvedBy: USER_1_ID,
      approvedAt: '2026-03-04T14:00:00+03:00',
      rejectionReason: null,
      isHalfDay: false,
      halfDayPeriod: null,
      refusalReason: null,
      createdBy: USER_3_ID,
      updatedBy: USER_1_ID,
      version: 1,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: LEAVE_3_ID,
      tenantId: TENANT_ID,
      employeeId: EMPLOYEE_1_ID,
      leaveType: 'emergency',
      leaveTypeId: LEAVE_TYPE_EMERGENCY_ID,
      startDate: '2026-04-10',
      endDate: '2026-04-10',
      daysRequested: 1,
      reason: 'Personal errand',
      status: 'pending',
      approvedBy: null,
      approvedAt: null,
      rejectionReason: null,
      isHalfDay: false,
      halfDayPeriod: null,
      refusalReason: null,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);

  // ═══════════════════════════════════════════════════════════════════════════
  // PAYROLL RUNS (kept from existing seed)
  // ═══════════════════════════════════════════════════════════════════════════
  // Employee 1 (Saudi): gross=20250, gosiEmp=1462.50 (9.75% of 15000), gosiEr=1762.50 (11.75% of 15000), net=18787.50
  // Employee 2 (Saudi): gross=6750, gosiEmp=487.50 (9.75% of 5000), gosiEr=587.50 (11.75% of 5000), net=6262.50
  // Employee 3 (Non-Saudi): gross=13500, gosiEmp=0, gosiEr=1175 (11.75% of 10000), net=13500
  // Totals: gross=40500, deductions=1950, net=38550, gosiEmployer=3525
  await qi.bulkInsert('payroll_runs', [
    {
      id: PAYROLL_RUN_ID,
      tenantId: TENANT_ID,
      periodStart: '2026-01-01',
      periodEnd: '2026-01-31',
      status: 'approved',
      totalEmployees: 3,
      totalGross: 40500,
      totalDeductions: 1950,
      totalNet: 38550,
      totalGosiEmployer: 3525,
      currency: 'SAR',
      notes: 'January 2026 payroll',
      processedBy: USER_1_ID,
      approvedBy: USER_1_ID,
      processedAt: '2026-02-01T09:00:00+03:00',
      approvedAt: '2026-02-01T11:00:00+03:00',
      journalEntryId: null,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 2,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: PAYROLL_RUN_2_ID,
      tenantId: TENANT_ID,
      periodStart: '2026-02-01',
      periodEnd: '2026-02-28',
      status: 'processed',
      totalEmployees: 3,
      totalGross: 40500,
      totalDeductions: 2117,
      totalNet: 38383,
      totalGosiEmployer: 3525,
      currency: 'SAR',
      notes: 'February 2026 payroll',
      processedBy: USER_1_ID,
      approvedBy: null,
      processedAt: '2026-03-01T09:00:00+03:00',
      approvedAt: null,
      journalEntryId: null,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 1,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);

  // ═══════════════════════════════════════════════════════════════════════════
  // PAYROLL ITEMS — January 2026 run
  // ═══════════════════════════════════════════════════════════════════════════
  await qi.bulkInsert('payroll_items', [
    {
      id: uuidv7(),
      runId: PAYROLL_RUN_ID,
      employeeId: EMPLOYEE_1_ID,
      basicSalary: 15000,
      housingAllowance: 3750,
      transportationAllowance: 1500,
      otherAllowances: 0,
      allowancesDetail: null,
      grossSalary: 20250,
      lateDeductions: 0,
      absenceDeductions: 0,
      loanDeductions: 0,
      gosiEmployee: 1462.5,
      otherDeductions: 0,
      deductionsDetail: null,
      totalDeductions: 1462.5,
      netPay: 18787.5,
      gosiEmployer: 1762.5,
      paymentStatus: 'paid',
      paymentDate: '2026-02-02',
      paymentReference: 'PAY-2026-01-001',
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      runId: PAYROLL_RUN_ID,
      employeeId: EMPLOYEE_2_ID,
      basicSalary: 5000,
      housingAllowance: 1250,
      transportationAllowance: 500,
      otherAllowances: 0,
      allowancesDetail: null,
      grossSalary: 6750,
      lateDeductions: 0,
      absenceDeductions: 0,
      loanDeductions: 0,
      gosiEmployee: 487.5,
      otherDeductions: 0,
      deductionsDetail: null,
      totalDeductions: 487.5,
      netPay: 6262.5,
      gosiEmployer: 587.5,
      paymentStatus: 'paid',
      paymentDate: '2026-02-02',
      paymentReference: 'PAY-2026-01-002',
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      runId: PAYROLL_RUN_ID,
      employeeId: EMPLOYEE_3_ID,
      basicSalary: 10000,
      housingAllowance: 2500,
      transportationAllowance: 1000,
      otherAllowances: 0,
      allowancesDetail: null,
      grossSalary: 13500,
      lateDeductions: 0,
      absenceDeductions: 0,
      loanDeductions: 0,
      gosiEmployee: 0,
      otherDeductions: 0,
      deductionsDetail: null,
      totalDeductions: 0,
      netPay: 13500,
      gosiEmployer: 1175,
      paymentStatus: 'paid',
      paymentDate: '2026-02-02',
      paymentReference: 'PAY-2026-01-003',
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    // Payroll Items — February 2026 run
    {
      id: uuidv7(),
      runId: PAYROLL_RUN_2_ID,
      employeeId: EMPLOYEE_1_ID,
      basicSalary: 15000,
      housingAllowance: 3750,
      transportationAllowance: 1500,
      otherAllowances: 0,
      allowancesDetail: null,
      grossSalary: 20250,
      lateDeductions: 0,
      absenceDeductions: 0,
      loanDeductions: 0,
      gosiEmployee: 1462.5,
      otherDeductions: 0,
      deductionsDetail: null,
      totalDeductions: 1462.5,
      netPay: 18787.5,
      gosiEmployer: 1762.5,
      paymentStatus: 'pending',
      paymentDate: null,
      paymentReference: 'PAY-2026-02-001',
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      runId: PAYROLL_RUN_2_ID,
      employeeId: EMPLOYEE_2_ID,
      basicSalary: 5000,
      housingAllowance: 1250,
      transportationAllowance: 500,
      otherAllowances: 0,
      allowancesDetail: null,
      grossSalary: 6750,
      lateDeductions: 0,
      absenceDeductions: 167,
      loanDeductions: 0,
      gosiEmployee: 487.5,
      otherDeductions: 0,
      deductionsDetail: null,
      totalDeductions: 654.5,
      netPay: 6095.5,
      gosiEmployer: 587.5,
      paymentStatus: 'pending',
      paymentDate: null,
      paymentReference: 'PAY-2026-02-002',
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      runId: PAYROLL_RUN_2_ID,
      employeeId: EMPLOYEE_3_ID,
      basicSalary: 10000,
      housingAllowance: 2500,
      transportationAllowance: 1000,
      otherAllowances: 0,
      allowancesDetail: null,
      grossSalary: 13500,
      lateDeductions: 0,
      absenceDeductions: 0,
      loanDeductions: 0,
      gosiEmployee: 0,
      otherDeductions: 0,
      deductionsDetail: null,
      totalDeductions: 0,
      netPay: 13500,
      gosiEmployer: 1175,
      paymentStatus: 'pending',
      paymentDate: null,
      paymentReference: 'PAY-2026-02-003',
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);

  // ═══════════════════════════════════════════════════════════════════════════
  // PAYSLIPS (2: 1 confirmed for Jan, 1 draft for Feb)
  // ═══════════════════════════════════════════════════════════════════════════
  // Payslip 1: Employee 1, Jan 2026, confirmed
  // Gross=20250, GOSI_EMP=1462.50, GOSI_ER=1762.50, Net=18787.50
  await qi.bulkInsert('payslips', [
    {
      id: PAYSLIP_1_ID,
      tenantId: TENANT_ID,
      branchId: BRANCH_1_ID,
      employeeId: EMPLOYEE_1_ID,
      contractId: CONTRACT_1_ID,
      structureId: SALARY_STRUCT_SAUDI_ID,
      reference: 'SLIP-2026-01-001',
      periodStart: '2026-01-01',
      periodEnd: '2026-01-31',
      status: 'confirmed',
      grossSalary: 20250,
      totalDeductions: 1462.5,
      netSalary: 18787.5,
      gosiEmployee: 1462.5,
      gosiEmployer: 1762.5,
      incomeTax: 0,
      journalEntryId: null,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 1,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: PAYSLIP_2_ID,
      tenantId: TENANT_ID,
      branchId: BRANCH_1_ID,
      employeeId: EMPLOYEE_2_ID,
      contractId: CONTRACT_2_ID,
      structureId: SALARY_STRUCT_SAUDI_ID,
      reference: 'SLIP-2026-02-002',
      periodStart: '2026-02-01',
      periodEnd: '2026-02-28',
      status: 'draft',
      grossSalary: 6750,
      totalDeductions: 487.5,
      netSalary: 6262.5,
      gosiEmployee: 487.5,
      gosiEmployer: 587.5,
      incomeTax: 0,
      journalEntryId: null,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);

  // ═══════════════════════════════════════════════════════════════════════════
  // PAYSLIP LINES — Payslip 1 (Employee 1, Jan 2026, Saudi structure)
  // ═══════════════════════════════════════════════════════════════════════════
  await qi.bulkInsert('payslip_lines', [
    // --- Payslip 1 lines (Employee 1 — Saudi, confirmed) ---
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      branchId: BRANCH_1_ID,
      payslipId: PAYSLIP_1_ID,
      ruleId: null,
      code: 'BASIC',
      nameEn: 'Basic Salary',
      nameAr: 'الراتب الأساسي',
      category: 'earnings',
      sequence: 10,
      quantity: 1,
      rate: 1,
      amount: 15000,
      appearsOnPayslip: true,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      branchId: BRANCH_1_ID,
      payslipId: PAYSLIP_1_ID,
      ruleId: null,
      code: 'HRA',
      nameEn: 'Housing Allowance',
      nameAr: 'بدل سكن',
      category: 'earnings',
      sequence: 20,
      quantity: 1,
      rate: 1,
      amount: 3750,
      appearsOnPayslip: true,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      branchId: BRANCH_1_ID,
      payslipId: PAYSLIP_1_ID,
      ruleId: null,
      code: 'TRANS',
      nameEn: 'Transportation Allowance',
      nameAr: 'بدل نقل',
      category: 'earnings',
      sequence: 30,
      quantity: 1,
      rate: 1,
      amount: 1500,
      appearsOnPayslip: true,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      branchId: BRANCH_1_ID,
      payslipId: PAYSLIP_1_ID,
      ruleId: null,
      code: 'GROSS',
      nameEn: 'Gross Salary',
      nameAr: 'إجمالي الراتب',
      category: 'gross',
      sequence: 100,
      quantity: 1,
      rate: 1,
      amount: 20250,
      appearsOnPayslip: true,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      branchId: BRANCH_1_ID,
      payslipId: PAYSLIP_1_ID,
      ruleId: null,
      code: 'GOSI_EMP',
      nameEn: 'GOSI (Employee)',
      nameAr: 'التأمينات الاجتماعية (الموظف)',
      category: 'deductions',
      sequence: 200,
      quantity: 1,
      rate: 0.0975,
      amount: -1462.5,
      appearsOnPayslip: true,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      branchId: BRANCH_1_ID,
      payslipId: PAYSLIP_1_ID,
      ruleId: null,
      code: 'GOSI_ER',
      nameEn: 'GOSI (Employer)',
      nameAr: 'التأمينات الاجتماعية (صاحب العمل)',
      category: 'employer',
      sequence: 210,
      quantity: 1,
      rate: 0.1175,
      amount: -1762.5,
      appearsOnPayslip: true,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      branchId: BRANCH_1_ID,
      payslipId: PAYSLIP_1_ID,
      ruleId: null,
      code: 'NET',
      nameEn: 'Net Salary',
      nameAr: 'صافي الراتب',
      category: 'net',
      sequence: 999,
      quantity: 1,
      rate: 1,
      amount: 18787.5,
      appearsOnPayslip: true,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },

    // --- Payslip 2 lines (Employee 2 — Saudi, draft) ---
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      branchId: BRANCH_1_ID,
      payslipId: PAYSLIP_2_ID,
      ruleId: null,
      code: 'BASIC',
      nameEn: 'Basic Salary',
      nameAr: 'الراتب الأساسي',
      category: 'earnings',
      sequence: 10,
      quantity: 1,
      rate: 1,
      amount: 5000,
      appearsOnPayslip: true,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      branchId: BRANCH_1_ID,
      payslipId: PAYSLIP_2_ID,
      ruleId: null,
      code: 'HRA',
      nameEn: 'Housing Allowance',
      nameAr: 'بدل سكن',
      category: 'earnings',
      sequence: 20,
      quantity: 1,
      rate: 1,
      amount: 1250,
      appearsOnPayslip: true,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      branchId: BRANCH_1_ID,
      payslipId: PAYSLIP_2_ID,
      ruleId: null,
      code: 'TRANS',
      nameEn: 'Transportation Allowance',
      nameAr: 'بدل نقل',
      category: 'earnings',
      sequence: 30,
      quantity: 1,
      rate: 1,
      amount: 500,
      appearsOnPayslip: true,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      branchId: BRANCH_1_ID,
      payslipId: PAYSLIP_2_ID,
      ruleId: null,
      code: 'GROSS',
      nameEn: 'Gross Salary',
      nameAr: 'إجمالي الراتب',
      category: 'gross',
      sequence: 100,
      quantity: 1,
      rate: 1,
      amount: 6750,
      appearsOnPayslip: true,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      branchId: BRANCH_1_ID,
      payslipId: PAYSLIP_2_ID,
      ruleId: null,
      code: 'GOSI_EMP',
      nameEn: 'GOSI (Employee)',
      nameAr: 'التأمينات الاجتماعية (الموظف)',
      category: 'deductions',
      sequence: 200,
      quantity: 1,
      rate: 0.0975,
      amount: -487.5,
      appearsOnPayslip: true,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      branchId: BRANCH_1_ID,
      payslipId: PAYSLIP_2_ID,
      ruleId: null,
      code: 'GOSI_ER',
      nameEn: 'GOSI (Employer)',
      nameAr: 'التأمينات الاجتماعية (صاحب العمل)',
      category: 'employer',
      sequence: 210,
      quantity: 1,
      rate: 0.1175,
      amount: -587.5,
      appearsOnPayslip: true,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      branchId: BRANCH_1_ID,
      payslipId: PAYSLIP_2_ID,
      ruleId: null,
      code: 'NET',
      nameEn: 'Net Salary',
      nameAr: 'صافي الراتب',
      category: 'net',
      sequence: 999,
      quantity: 1,
      rate: 1,
      amount: 6262.5,
      appearsOnPayslip: true,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);

  // ═══════════════════════════════════════════════════════════════════════════
  // TRAINING RECORDS
  // ═══════════════════════════════════════════════════════════════════════════
  await qi.bulkInsert('training_records', [
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      employeeId: EMPLOYEE_3_ID,
      courseName: 'IT Security Fundamentals',
      provider: 'SANS Institute',
      trainingType: 'external',
      startDate: '2026-02-01',
      endDate: '2026-02-05',
      durationHours: 40,
      status: 'completed',
      score: 92.5,
      passed: true,
      certificateNumber: 'SANS-SEC-2026-4871',
      certificateUrl: null,
      certificateExpiry: '2028-02-05',
      cost: 5500,
      notes: 'Sponsored by company as part of annual IT training plan',
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      employeeId: EMPLOYEE_1_ID,
      courseName: 'Leadership Development',
      provider: 'Internal Training Department',
      trainingType: 'internal',
      startDate: '2026-01-15',
      endDate: '2026-01-16',
      durationHours: 16,
      status: 'completed',
      score: 88,
      passed: true,
      certificateNumber: null,
      certificateUrl: null,
      certificateExpiry: null,
      cost: 0,
      notes: null,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      employeeId: EMPLOYEE_2_ID,
      courseName: 'Customer Service Excellence',
      provider: 'Dale Carnegie',
      trainingType: 'external',
      startDate: '2026-02-10',
      endDate: '2026-02-11',
      durationHours: 12,
      status: 'completed',
      score: 95,
      passed: true,
      certificateNumber: 'CSEP-2026-1234',
      certificateUrl: null,
      certificateExpiry: null,
      cost: 3200,
      notes: null,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);

  console.log(
    '[08-hr] Seeded 3 job positions, 3 employees, 2 shifts, 10 shift working days, ' +
      '2 salary structures, 14 salary rules, 3 contracts, 5 leave types, 9 leave allocations, ' +
      '9 attendance records, 3 leave requests, 2 payroll runs, 6 payroll items, ' +
      '2 payslips, 14 payslip lines, 3 training records.',
  );
}
