import { Sequelize } from 'sequelize';
import { v7 as uuidv7 } from 'uuid';

const TENANT_ID = '10000000-0000-0000-0000-000000000001';
const BRANCH_1_ID = '30000000-0000-0000-0000-000000000001';
const COA_CASH_ID = 'B0000000-0000-0000-0000-000000000001';
const COA_BANK_ID = 'B0000000-0000-0000-0000-000000000002';
const COA_AR_ID = 'B0000000-0000-0000-0000-000000000003';
const COA_REVENUE_ID = 'B0000000-0000-0000-0000-000000000004';
const COA_EXPENSE_ID = 'B0000000-0000-0000-0000-000000000005';
const COA_AP_ID = 'B0000000-0000-0000-0000-000000000006';
const COA_VAT_ID = 'B0000000-0000-0000-0000-000000000007';
const COA_GOSI_ID = 'B0000000-0000-0000-0000-000000000008';
const COA_SALARY_ID = 'B0000000-0000-0000-0000-000000000009';
const COA_INVENTORY_ID = 'B0000000-0000-0000-0000-000000000010';
const TREASURY_1_ID = 'B1000000-0000-0000-0000-000000000001';
const TREASURY_2_ID = 'B1000000-0000-0000-0000-000000000002';
const COST_CENTER_1_ID = 'B2000000-0000-0000-0000-000000000001';
const COST_CENTER_2_ID = 'B2000000-0000-0000-0000-000000000002';
const USER_1_ID = '20000000-0000-0000-0000-000000000001';
const CONTACT_1_ID = '80000000-0000-0000-0000-000000000001';

const JE_1_ID = 'B3000000-0000-0000-0000-000000000001';
const JE_2_ID = 'B3000000-0000-0000-0000-000000000002';
const JE_3_ID = 'B3000000-0000-0000-0000-000000000003';
const JE_4_ID = 'B3000000-0000-0000-0000-000000000004';
const JE_5_ID = 'B3000000-0000-0000-0000-000000000005';
const RECON_1_ID = 'B4000000-0000-0000-0000-000000000001';

export async function seed(sequelize: Sequelize): Promise<void> {
  const qi = sequelize.getQueryInterface();
  const now = new Date();

  // Chart of Accounts
  await qi.bulkInsert('chart_of_accounts', [
    {
      id: COA_CASH_ID,
      tenantId: TENANT_ID,
      code: '1101',
      nameEn: 'Cash',
      nameAr: 'نقد',
      descriptionEn: 'Cash on hand',
      descriptionAr: 'النقد في الصندوق',
      type: 'asset',
      subType: 'current_asset',
      parentId: null,
      normalBalance: 'debit',
      isActive: true,
      allowDirectPosting: true,
      openingBalance: 0,
      openingBalanceDate: null,
      currency: 'SAR',
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: COA_BANK_ID,
      tenantId: TENANT_ID,
      code: '1102',
      nameEn: 'Bank',
      nameAr: 'بنك',
      descriptionEn: 'Bank accounts',
      descriptionAr: 'الحسابات البنكية',
      type: 'asset',
      subType: 'current_asset',
      parentId: null,
      normalBalance: 'debit',
      isActive: true,
      allowDirectPosting: true,
      openingBalance: 0,
      openingBalanceDate: null,
      currency: 'SAR',
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: COA_AR_ID,
      tenantId: TENANT_ID,
      code: '1201',
      nameEn: 'Accounts Receivable',
      nameAr: 'ذمم مدينة',
      descriptionEn: 'Amounts owed by customers',
      descriptionAr: 'المبالغ المستحقة من العملاء',
      type: 'asset',
      subType: 'current_asset',
      parentId: null,
      normalBalance: 'debit',
      isActive: true,
      allowDirectPosting: true,
      openingBalance: 0,
      openingBalanceDate: null,
      currency: 'SAR',
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: COA_REVENUE_ID,
      tenantId: TENANT_ID,
      code: '4101',
      nameEn: 'Sales Revenue',
      nameAr: 'إيرادات المبيعات',
      descriptionEn: 'Revenue from product and service sales',
      descriptionAr: 'الإيرادات من مبيعات المنتجات والخدمات',
      type: 'revenue',
      subType: null,
      parentId: null,
      normalBalance: 'credit',
      isActive: true,
      allowDirectPosting: true,
      openingBalance: 0,
      openingBalanceDate: null,
      currency: 'SAR',
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: COA_EXPENSE_ID,
      tenantId: TENANT_ID,
      code: '5101',
      nameEn: 'General Expenses',
      nameAr: 'مصاريف عامة',
      descriptionEn: 'General operating expenses',
      descriptionAr: 'المصاريف التشغيلية العامة',
      type: 'expense',
      subType: null,
      parentId: null,
      normalBalance: 'debit',
      isActive: true,
      allowDirectPosting: true,
      openingBalance: 0,
      openingBalanceDate: null,
      currency: 'SAR',
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: COA_AP_ID,
      tenantId: TENANT_ID,
      code: '2101',
      nameEn: 'Accounts Payable',
      nameAr: 'ذمم دائنة',
      descriptionEn: 'Amounts owed to vendors',
      descriptionAr: 'المبالغ المستحقة للموردين',
      type: 'liability',
      subType: 'current_liability',
      parentId: null,
      normalBalance: 'credit',
      isActive: true,
      allowDirectPosting: true,
      openingBalance: 0,
      openingBalanceDate: null,
      currency: 'SAR',
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: COA_VAT_ID,
      tenantId: TENANT_ID,
      code: '2105',
      nameEn: 'VAT Payable',
      nameAr: 'ضريبة القيمة المضافة المستحقة',
      descriptionEn: 'Value Added Tax payable to ZATCA',
      descriptionAr: 'ضريبة القيمة المضافة المستحقة لهيئة الزكاة والضريبة والجمارك',
      type: 'liability',
      subType: 'current_liability',
      parentId: null,
      normalBalance: 'credit',
      isActive: true,
      allowDirectPosting: true,
      openingBalance: 0,
      openingBalanceDate: null,
      currency: 'SAR',
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: COA_GOSI_ID,
      tenantId: TENANT_ID,
      code: '2106',
      nameEn: 'GOSI Payable',
      nameAr: 'التأمينات الاجتماعية المستحقة',
      descriptionEn: 'GOSI contributions payable',
      descriptionAr: 'اشتراكات التأمينات الاجتماعية المستحقة',
      type: 'liability',
      subType: 'current_liability',
      parentId: null,
      normalBalance: 'credit',
      isActive: true,
      allowDirectPosting: false,
      openingBalance: 0,
      openingBalanceDate: null,
      currency: 'SAR',
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: COA_SALARY_ID,
      tenantId: TENANT_ID,
      code: '5201',
      nameEn: 'Salaries & Wages',
      nameAr: 'رواتب وأجور',
      descriptionEn: 'Employee salaries and wages expense',
      descriptionAr: 'مصاريف رواتب وأجور الموظفين',
      type: 'expense',
      subType: null,
      parentId: null,
      normalBalance: 'debit',
      isActive: true,
      allowDirectPosting: true,
      openingBalance: 0,
      openingBalanceDate: null,
      currency: 'SAR',
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: COA_INVENTORY_ID,
      tenantId: TENANT_ID,
      code: '1301',
      nameEn: 'Inventory',
      nameAr: 'المخزون',
      descriptionEn: 'Inventory of goods held for sale',
      descriptionAr: 'مخزون البضائع المعدة للبيع',
      type: 'asset',
      subType: 'current_asset',
      parentId: null,
      normalBalance: 'debit',
      isActive: true,
      allowDirectPosting: true,
      openingBalance: 0,
      openingBalanceDate: null,
      currency: 'SAR',
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);

  // Cost Center
  await qi.bulkInsert('cost_centers', [
    {
      id: COST_CENTER_1_ID,
      tenantId: TENANT_ID,
      code: 'CC01',
      nameEn: 'Main Operations',
      nameAr: 'العمليات الرئيسية',
      descriptionEn: 'Main operational cost center',
      descriptionAr: 'مركز تكلفة العمليات الرئيسية',
      parentId: null,
      isActive: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: COST_CENTER_2_ID,
      tenantId: TENANT_ID,
      code: 'CC02',
      nameEn: 'Retail Operations',
      nameAr: 'عمليات البيع بالتجزئة',
      descriptionEn: 'Retail and store operations cost center',
      descriptionAr: 'مركز تكلفة عمليات البيع بالتجزئة',
      parentId: null,
      isActive: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);

  // Treasury Accounts
  await qi.bulkInsert('treasury_accounts', [
    {
      id: TREASURY_1_ID,
      tenantId: TENANT_ID,
      branchId: BRANCH_1_ID,
      nameEn: 'Main Cash',
      nameAr: 'صندوق رئيسي',
      descriptionEn: 'Main cash treasury for daily operations',
      descriptionAr: 'الصندوق الرئيسي للعمليات اليومية',
      type: 'cash',
      bankName: null,
      accountNumber: null,
      iban: null,
      swiftCode: null,
      currency: 'SAR',
      currentBalance: 0,
      coaAccountId: COA_CASH_ID,
      isActive: true,
      isDefault: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: TREASURY_2_ID,
      tenantId: TENANT_ID,
      branchId: BRANCH_1_ID,
      nameEn: 'Company Bank Account',
      nameAr: 'حساب الشركة البنكي',
      descriptionEn: 'Al Rajhi Bank company account',
      descriptionAr: 'حساب الشركة في مصرف الراجحي',
      type: 'bank',
      bankName: 'Al Rajhi Bank',
      accountNumber: '1234567890',
      iban: 'SA0380000000608010167519',
      swiftCode: 'RJHISARI',
      currency: 'SAR',
      currentBalance: 0,
      coaAccountId: COA_BANK_ID,
      isActive: true,
      isDefault: false,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);

  // Fiscal Period (BIGINT PK)
  await qi.bulkInsert('fiscal_periods', [
    {
      tenantId: TENANT_ID,
      fiscalYear: 2026,
      periodNumber: 1,
      periodType: 'monthly',
      nameEn: 'January 2026',
      nameAr: 'يناير 2026',
      startDate: '2026-01-01',
      endDate: '2026-01-31',
      status: 'open',
      closedBy: null,
      closedAt: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      tenantId: TENANT_ID,
      fiscalYear: 2026,
      periodNumber: 2,
      periodType: 'monthly',
      nameEn: 'February 2026',
      nameAr: 'فبراير 2026',
      startDate: '2026-02-01',
      endDate: '2026-02-28',
      status: 'open',
      closedBy: null,
      closedAt: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
  ]);

  // Journal Entries
  const postedAt = new Date('2026-01-15T10:00:00Z');

  await qi.bulkInsert('journal_entries', [
    {
      id: JE_1_ID,
      tenantId: TENANT_ID,
      entryNumber: 'JE-0001',
      date: '2026-01-10',
      type: 'manual',
      description: 'Cash sale - revenue recognition',
      referenceId: null,
      referenceType: null,
      reversedBy: null,
      reversalOf: null,
      isPosted: true,
      postedBy: USER_1_ID,
      postedAt,
      periodId: 1,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: JE_2_ID,
      tenantId: TENANT_ID,
      entryNumber: 'JE-0002',
      date: '2026-01-12',
      type: 'manual',
      description: 'Expense payment - office supplies',
      referenceId: null,
      referenceType: null,
      reversedBy: null,
      reversalOf: null,
      isPosted: true,
      postedBy: USER_1_ID,
      postedAt,
      periodId: 1,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: JE_3_ID,
      tenantId: TENANT_ID,
      entryNumber: 'JE-0003',
      date: '2026-01-31',
      type: 'manual',
      description: 'Payroll entry - January 2026',
      referenceId: null,
      referenceType: null,
      reversedBy: null,
      reversalOf: null,
      isPosted: true,
      postedBy: USER_1_ID,
      postedAt,
      periodId: 1,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: JE_4_ID,
      tenantId: TENANT_ID,
      entryNumber: 'JE-0004',
      date: '2026-01-28',
      type: 'manual',
      description: 'VAT payment to ZATCA',
      referenceId: null,
      referenceType: null,
      reversedBy: null,
      reversalOf: null,
      isPosted: true,
      postedBy: USER_1_ID,
      postedAt,
      periodId: 1,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: JE_5_ID,
      tenantId: TENANT_ID,
      entryNumber: 'JE-0005',
      date: '2026-02-05',
      type: 'manual',
      description: 'Inventory purchase from vendor',
      referenceId: null,
      referenceType: null,
      reversedBy: null,
      reversalOf: null,
      isPosted: true,
      postedBy: USER_1_ID,
      postedAt,
      periodId: 2,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);

  // Journal Lines
  await qi.bulkInsert('journal_lines', [
    // JE-0001: Cash sale - Debit Cash 1150, Credit Revenue 1150
    {
      entryId: JE_1_ID,
      accountId: COA_CASH_ID,
      debit: 1150.0,
      credit: 0,
      description: 'Cash received from sale',
      costCenterId: COST_CENTER_1_ID,
      currency: 'SAR',
      exchangeRate: 1,
      createdAt: now,
    },
    {
      entryId: JE_1_ID,
      accountId: COA_REVENUE_ID,
      debit: 0,
      credit: 1150.0,
      description: 'Sales revenue recognized',
      costCenterId: COST_CENTER_1_ID,
      currency: 'SAR',
      exchangeRate: 1,
      createdAt: now,
    },
    // JE-0002: Expense payment - Debit Expense 500, Credit Cash 500
    {
      entryId: JE_2_ID,
      accountId: COA_EXPENSE_ID,
      debit: 500.0,
      credit: 0,
      description: 'Office supplies expense',
      costCenterId: COST_CENTER_1_ID,
      currency: 'SAR',
      exchangeRate: 1,
      createdAt: now,
    },
    {
      entryId: JE_2_ID,
      accountId: COA_CASH_ID,
      debit: 0,
      credit: 500.0,
      description: 'Cash paid for office supplies',
      costCenterId: null,
      currency: 'SAR',
      exchangeRate: 1,
      createdAt: now,
    },
    // JE-0003: Payroll - Debit Salaries 40500, Credit Cash 38000, Credit GOSI 2500
    {
      entryId: JE_3_ID,
      accountId: COA_SALARY_ID,
      debit: 40500.0,
      credit: 0,
      description: 'Salaries and wages expense for January 2026',
      costCenterId: COST_CENTER_1_ID,
      currency: 'SAR',
      exchangeRate: 1,
      createdAt: now,
    },
    {
      entryId: JE_3_ID,
      accountId: COA_CASH_ID,
      debit: 0,
      credit: 38000.0,
      description: 'Cash paid for salaries',
      costCenterId: COST_CENTER_1_ID,
      currency: 'SAR',
      exchangeRate: 1,
      createdAt: now,
    },
    {
      entryId: JE_3_ID,
      accountId: COA_GOSI_ID,
      debit: 0,
      credit: 2500.0,
      description: 'GOSI contributions payable',
      costCenterId: COST_CENTER_1_ID,
      currency: 'SAR',
      exchangeRate: 1,
      createdAt: now,
    },
    // JE-0004: VAT payment - Debit VAT Payable 5000, Credit Bank 5000
    {
      entryId: JE_4_ID,
      accountId: COA_VAT_ID,
      debit: 5000.0,
      credit: 0,
      description: 'VAT payment to ZATCA',
      costCenterId: null,
      currency: 'SAR',
      exchangeRate: 1,
      createdAt: now,
    },
    {
      entryId: JE_4_ID,
      accountId: COA_BANK_ID,
      debit: 0,
      credit: 5000.0,
      description: 'Bank transfer for VAT payment',
      costCenterId: null,
      currency: 'SAR',
      exchangeRate: 1,
      createdAt: now,
    },
    // JE-0005: Inventory purchase - Debit Inventory 15000, Credit AP 15000
    {
      entryId: JE_5_ID,
      accountId: COA_INVENTORY_ID,
      debit: 15000.0,
      credit: 0,
      description: 'Inventory purchased from vendor',
      costCenterId: COST_CENTER_2_ID,
      currency: 'SAR',
      exchangeRate: 1,
      createdAt: now,
    },
    {
      entryId: JE_5_ID,
      accountId: COA_AP_ID,
      debit: 0,
      credit: 15000.0,
      description: 'Accounts payable for inventory purchase',
      costCenterId: COST_CENTER_2_ID,
      currency: 'SAR',
      exchangeRate: 1,
      createdAt: now,
    },
  ]);

  // Treasury Transactions
  const treasuryTx1Id = uuidv7();
  const treasuryTx2Id = uuidv7();
  const treasuryTx3Id = uuidv7();
  const treasuryTx4Id = uuidv7();

  await qi.bulkInsert('treasury_transactions', [
    {
      id: treasuryTx1Id,
      tenantId: TENANT_ID,
      accountId: TREASURY_2_ID,
      type: 'deposit',
      amount: 10000.0,
      currency: 'SAR',
      exchangeRate: 1,
      reference: 'DEP-2026-001',
      contactId: null,
      date: '2026-01-05',
      description: 'Initial deposit to bank account',
      isReconciled: true,
      reconciliationId: RECON_1_ID,
      journalEntryId: null,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: treasuryTx2Id,
      tenantId: TENANT_ID,
      accountId: TREASURY_2_ID,
      type: 'payment',
      amount: 5000.0,
      currency: 'SAR',
      exchangeRate: 1,
      reference: 'PAY-2026-001',
      contactId: CONTACT_1_ID,
      date: '2026-01-20',
      description: 'Vendor payment via bank transfer',
      isReconciled: false,
      reconciliationId: null,
      journalEntryId: null,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: treasuryTx3Id,
      tenantId: TENANT_ID,
      accountId: TREASURY_1_ID,
      type: 'payment',
      amount: 38000.0,
      currency: 'SAR',
      exchangeRate: 1,
      reference: 'PAY-2026-002',
      contactId: null,
      date: '2026-01-31',
      description: 'Salary payment for January 2026',
      isReconciled: false,
      reconciliationId: null,
      journalEntryId: JE_3_ID,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: treasuryTx4Id,
      tenantId: TENANT_ID,
      accountId: TREASURY_2_ID,
      type: 'payment',
      amount: 15000.0,
      currency: 'SAR',
      exchangeRate: 1,
      reference: 'PAY-2026-003',
      contactId: CONTACT_1_ID,
      date: '2026-02-05',
      description: 'Vendor payment for inventory purchase',
      isReconciled: false,
      reconciliationId: null,
      journalEntryId: JE_5_ID,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);

  // Bank Reconciliations
  await qi.bulkInsert('bank_reconciliations', [
    {
      id: RECON_1_ID,
      accountId: TREASURY_2_ID,
      statementDate: '2026-01-31',
      openingBalance: 0,
      closingBalance: 5000.0,
      systemBalance: 5000.0,
      difference: 0,
      status: 'completed',
      reconciledBy: USER_1_ID,
      completedAt: new Date('2026-02-01T09:00:00Z'),
      notes: 'January 2026 bank reconciliation completed',
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
  ]);

  console.log(
    '[10-accounting] Seeded 10 COA accounts, 2 cost centers, 2 treasury accounts, 2 fiscal periods, 5 journal entries, 11 journal lines, 4 treasury transactions, and 1 bank reconciliation.',
  );
}
