import { Sequelize } from 'sequelize';
import { v7 as uuidv7 } from 'uuid';

const TENANT_ID = '10000000-0000-4000-a000-000000000001';
const USER_1_ID = '20000000-0000-4000-a000-000000000001';
const USER_3_ID = '20000000-0000-4000-a000-000000000003';
const PROJECT_1_ID = 'E0000000-0000-4000-a000-000000000001';
const PROJECT_2_ID = 'E0000000-0000-4000-a000-000000000002';
const PROJECT_3_ID = 'E0000000-0000-4000-a000-000000000003';

export async function seed(sequelize: Sequelize): Promise<void> {
  const qi = sequelize.getQueryInterface();
  const now = new Date();

  // Project
  await qi.bulkInsert('projects', [
    {
      id: PROJECT_1_ID,
      tenantId: TENANT_ID,
      nameEn: 'ERP Implementation',
      nameAr: 'تطبيق نظام ERP',
      descriptionEn: 'Full ERP system implementation project',
      descriptionAr: 'مشروع تطبيق نظام تخطيط موارد المؤسسات الكامل',
      status: 'in_progress',
      startDate: '2026-01-01',
      endDate: '2026-06-30',
      budget: 100000,
      managerId: USER_1_ID,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: PROJECT_2_ID,
      tenantId: TENANT_ID,
      nameEn: 'Website Redesign',
      nameAr: 'إعادة تصميم الموقع',
      descriptionEn: 'Complete redesign of the company website',
      descriptionAr: 'إعادة تصميم كاملة لموقع الشركة الإلكتروني',
      status: 'planning',
      startDate: '2026-02-01',
      endDate: '2026-05-31',
      budget: 50000,
      managerId: USER_1_ID,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: PROJECT_3_ID,
      tenantId: TENANT_ID,
      nameEn: 'Mobile App Development',
      nameAr: 'تطوير تطبيق الجوال',
      descriptionEn: 'Development of the company mobile application',
      descriptionAr: 'تطوير تطبيق الجوال الخاص بالشركة',
      status: 'not_started',
      startDate: '2026-04-01',
      endDate: '2026-12-31',
      budget: 150000,
      managerId: USER_1_ID,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);

  // Project Member (BIGINT PK)
  await qi.bulkInsert('project_members', [
    {
      tenantId: TENANT_ID,
      projectId: PROJECT_1_ID,
      userId: USER_3_ID,
      role: 'member',
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      tenantId: TENANT_ID,
      projectId: PROJECT_1_ID,
      userId: USER_1_ID,
      role: 'lead',
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      tenantId: TENANT_ID,
      projectId: PROJECT_2_ID,
      userId: USER_3_ID,
      role: 'member',
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
  ]);

  // Tasks
  await qi.bulkInsert('tasks', [
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      projectId: PROJECT_1_ID,
      titleEn: 'Setup Development Environment',
      titleAr: 'إعداد بيئة التطوير',
      descriptionEn: 'Install and configure all development tools and dependencies',
      descriptionAr: 'تثبيت وتكوين جميع أدوات ومتطلبات التطوير',
      status: 'completed',
      priority: 'high',
      assignedTo: USER_3_ID,
      dueDate: '2026-01-31',
      estimatedHours: 16,
      loggedHours: 14,
      parentTaskId: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      projectId: PROJECT_1_ID,
      titleEn: 'Database Migration',
      titleAr: 'ترحيل قاعدة البيانات',
      descriptionEn: 'Migrate legacy database to the new ERP schema',
      descriptionAr: 'ترحيل قاعدة البيانات القديمة إلى مخطط ERP الجديد',
      status: 'in_progress',
      priority: 'high',
      assignedTo: USER_3_ID,
      dueDate: '2026-03-31',
      estimatedHours: 40,
      loggedHours: 12,
      parentTaskId: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      projectId: PROJECT_1_ID,
      titleEn: 'API Integration Testing',
      titleAr: 'اختبار تكامل الواجهة البرمجية',
      descriptionEn: 'Test all API integrations with external systems',
      descriptionAr: 'اختبار جميع تكاملات الواجهة البرمجية مع الأنظمة الخارجية',
      status: 'in_progress',
      priority: 'medium',
      assignedTo: USER_3_ID,
      dueDate: '2026-04-15',
      estimatedHours: 24,
      loggedHours: 0,
      parentTaskId: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      projectId: PROJECT_1_ID,
      titleEn: 'User Training',
      titleAr: 'تدريب المستخدمين',
      descriptionEn: 'Conduct training sessions for end users on the new ERP system',
      descriptionAr: 'إجراء جلسات تدريبية للمستخدمين النهائيين على نظام ERP الجديد',
      status: 'todo',
      priority: 'low',
      assignedTo: USER_1_ID,
      dueDate: '2026-05-31',
      estimatedHours: 32,
      loggedHours: 0,
      parentTaskId: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      projectId: PROJECT_2_ID,
      titleEn: 'UI/UX Mockups',
      titleAr: 'نماذج واجهة المستخدم',
      descriptionEn: 'Create UI/UX mockups and wireframes for the new website design',
      descriptionAr: 'إنشاء نماذج وإطارات سلكية لتصميم الموقع الجديد',
      status: 'in_progress',
      priority: 'high',
      assignedTo: USER_3_ID,
      dueDate: '2026-02-28',
      estimatedHours: 20,
      loggedHours: 0,
      parentTaskId: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      projectId: PROJECT_3_ID,
      titleEn: 'Requirements Gathering',
      titleAr: 'جمع المتطلبات',
      descriptionEn: 'Gather and document all requirements for the mobile application',
      descriptionAr: 'جمع وتوثيق جميع متطلبات تطبيق الجوال',
      status: 'todo',
      priority: 'high',
      assignedTo: USER_1_ID,
      dueDate: '2026-04-30',
      estimatedHours: 16,
      loggedHours: 0,
      parentTaskId: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);

  console.log('[12-projects] Seeded 3 projects, 3 members, and 6 tasks.');
}
