import { Sequelize } from 'sequelize';
import { v7 as uuidv7 } from 'uuid';

const TENANT_ID = '10000000-0000-0000-0000-000000000001';
const BRANCH_1_ID = '30000000-0000-0000-0000-000000000001';
const BRANCH_2_ID = '30000000-0000-0000-0000-000000000002';

export async function seed(sequelize: Sequelize): Promise<void> {
  const qi = sequelize.getQueryInterface();
  const now = new Date();

  await qi.bulkInsert('sequences', [
    // ── Company-wide sequences ──────────────────────────────────────────────
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      branchId: null,
      entity: 'sales_order',
      prefix: 'SO',
      lastValue: 3,
      padding: 5,
      resetCycle: 'never',
      fiscalYear: null,
      fiscalMonth: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      branchId: null,
      entity: 'purchase_order',
      prefix: 'PO',
      lastValue: 2,
      padding: 5,
      resetCycle: 'never',
      fiscalYear: null,
      fiscalMonth: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      branchId: null,
      entity: 'employee',
      prefix: 'EMP',
      lastValue: 3,
      padding: 3,
      resetCycle: 'never',
      fiscalYear: null,
      fiscalMonth: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      branchId: null,
      entity: 'lead',
      prefix: 'LD',
      lastValue: 5,
      padding: 5,
      resetCycle: 'never',
      fiscalYear: null,
      fiscalMonth: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      branchId: null,
      entity: 'project',
      prefix: 'PRJ',
      lastValue: 3,
      padding: 4,
      resetCycle: 'never',
      fiscalYear: null,
      fiscalMonth: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      branchId: null,
      entity: 'journal_entry',
      prefix: 'JE',
      lastValue: 5,
      padding: 4,
      resetCycle: 'yearly',
      fiscalYear: 2026,
      fiscalMonth: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      branchId: null,
      entity: 'pos_order',
      prefix: 'POS',
      lastValue: 5,
      padding: 5,
      resetCycle: 'never',
      fiscalYear: null,
      fiscalMonth: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      branchId: null,
      entity: 'invoice',
      prefix: 'INV',
      lastValue: 0,
      padding: 5,
      resetCycle: 'yearly',
      fiscalYear: 2026,
      fiscalMonth: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      branchId: null,
      entity: 'payment',
      prefix: 'PAY',
      lastValue: 0,
      padding: 5,
      resetCycle: 'yearly',
      fiscalYear: 2026,
      fiscalMonth: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      branchId: null,
      entity: 'delivery',
      prefix: 'OUT',
      lastValue: 2,
      padding: 5,
      resetCycle: 'never',
      fiscalYear: null,
      fiscalMonth: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      branchId: null,
      entity: 'receipt',
      prefix: 'IN',
      lastValue: 1,
      padding: 5,
      resetCycle: 'never',
      fiscalYear: null,
      fiscalMonth: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      branchId: null,
      entity: 'payslip',
      prefix: 'SLIP',
      lastValue: 0,
      padding: 5,
      resetCycle: 'monthly',
      fiscalYear: 2026,
      fiscalMonth: 3,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },

    // ── Branch-level sequences ──────────────────────────────────────────────
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      branchId: BRANCH_1_ID,
      entity: 'pos_order',
      prefix: 'POS',
      lastValue: 5,
      padding: 5,
      resetCycle: 'never',
      fiscalYear: null,
      fiscalMonth: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      branchId: BRANCH_2_ID,
      entity: 'pos_order',
      prefix: 'POS',
      lastValue: 0,
      padding: 5,
      resetCycle: 'never',
      fiscalYear: null,
      fiscalMonth: null,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
  ]);

  console.log('[13-sequences] Seeded 14 sequence definitions (12 company-wide + 2 branch-level).');
}
