import { Sequelize } from 'sequelize';

const TENANT_ID = '10000000-0000-4000-a000-000000000001';
const TENANT_SLUG = 'demo-company';

export async function seed(sequelize: Sequelize): Promise<void> {
  const qi = sequelize.getQueryInterface();
  const now = new Date();

  // Notification Templates (BIGINT PK)
  await qi.bulkInsert('notification_templates', [
    {
      tenantId: TENANT_ID,
      tenantSlug: TENANT_SLUG,
      eventType: 'ORDER_COMPLETED',
      channel: 'push',
      subjectEn: 'Order Completed',
      subjectAr: 'تم إكمال الطلب',
      bodyEn: 'Order {{orderNumber}} has been completed',
      bodyAr: 'تم إكمال الطلب {{orderNumber}}',
      isDefault: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      tenantId: TENANT_ID,
      tenantSlug: TENANT_SLUG,
      eventType: 'LOW_STOCK',
      channel: 'push',
      subjectEn: 'Low Stock Alert',
      subjectAr: 'تنبيه مخزون منخفض',
      bodyEn: 'Product {{productName}} is running low',
      bodyAr: 'المنتج {{productName}} مخزونه منخفض',
      isDefault: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      tenantId: TENANT_ID,
      tenantSlug: TENANT_SLUG,
      eventType: 'LEAVE_APPROVED',
      channel: 'push',
      subjectEn: 'Leave Request Approved',
      subjectAr: 'تمت الموافقة على طلب الإجازة',
      bodyEn: 'Your {{leaveType}} leave from {{startDate}} to {{endDate}} has been approved',
      bodyAr: 'تمت الموافقة على إجازتك {{leaveType}} من {{startDate}} إلى {{endDate}}',
      isDefault: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      tenantId: TENANT_ID,
      tenantSlug: TENANT_SLUG,
      eventType: 'LEAVE_REJECTED',
      channel: 'push',
      subjectEn: 'Leave Request Rejected',
      subjectAr: 'تم رفض طلب الإجازة',
      bodyEn: 'Your {{leaveType}} leave from {{startDate}} to {{endDate}} has been rejected',
      bodyAr: 'تم رفض إجازتك {{leaveType}} من {{startDate}} إلى {{endDate}}',
      isDefault: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      tenantId: TENANT_ID,
      tenantSlug: TENANT_SLUG,
      eventType: 'PAYROLL_PROCESSED',
      channel: 'push',
      subjectEn: 'Salary Processed',
      subjectAr: 'تمت معالجة الراتب',
      bodyEn: 'Your salary for {{period}} has been processed. Net amount: {{netPay}} SAR',
      bodyAr: 'تمت معالجة راتبك لفترة {{period}}. صافي المبلغ: {{netPay}} ريال',
      isDefault: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      tenantId: TENANT_ID,
      tenantSlug: TENANT_SLUG,
      eventType: 'SALES_ORDER_CONFIRMED',
      channel: 'push',
      subjectEn: 'Sales Order Confirmed',
      subjectAr: 'تم تأكيد أمر البيع',
      bodyEn: 'Sales order {{orderNumber}} for {{contactName}} has been confirmed',
      bodyAr: 'تم تأكيد أمر البيع {{orderNumber}} للعميل {{contactName}}',
      isDefault: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      tenantId: TENANT_ID,
      tenantSlug: TENANT_SLUG,
      eventType: 'CONTRACT_EXPIRING',
      channel: 'push',
      subjectEn: 'Contract Expiring Soon',
      subjectAr: 'العقد ينتهي قريباً',
      bodyEn: 'Employee {{employeeName}} contract expires on {{expiryDate}}',
      bodyAr: 'عقد الموظف {{employeeName}} ينتهي في {{expiryDate}}',
      isDefault: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      tenantId: TENANT_ID,
      tenantSlug: TENANT_SLUG,
      eventType: 'SESSION_CLOSED',
      channel: 'push',
      subjectEn: 'POS Session Closed',
      subjectAr: 'تم إغلاق جلسة نقطة البيع',
      bodyEn: 'Session on {{terminalName}} closed. Float difference: {{floatDifference}} SAR',
      bodyAr: 'تم إغلاق الجلسة على {{terminalName}}. فرق الرصيد: {{floatDifference}} ريال',
      isDefault: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      tenantId: TENANT_ID,
      tenantSlug: TENANT_SLUG,
      eventType: 'PO_RECEIVED',
      channel: 'push',
      subjectEn: 'Purchase Order Received',
      subjectAr: 'تم استلام أمر الشراء',
      bodyEn: 'Purchase order {{orderNumber}} from {{vendorName}} has been received',
      bodyAr: 'تم استلام أمر الشراء {{orderNumber}} من {{vendorName}}',
      isDefault: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      tenantId: TENANT_ID,
      tenantSlug: TENANT_SLUG,
      eventType: 'LEAD_WON',
      channel: 'push',
      subjectEn: 'Lead Won',
      subjectAr: 'تم كسب العميل المحتمل',
      bodyEn: 'Lead "{{leadTitle}}" has been won. Value: {{leadValue}} SAR',
      bodyAr: 'تم كسب العميل المحتمل "{{leadTitle}}". القيمة: {{leadValue}} ريال',
      isDefault: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      tenantId: TENANT_ID,
      tenantSlug: TENANT_SLUG,
      eventType: 'LEAD_LOST',
      channel: 'push',
      subjectEn: 'Lead Lost',
      subjectAr: 'تم خسارة العميل المحتمل',
      bodyEn: 'Lead "{{leadTitle}}" has been lost. Reason: {{lostReason}}',
      bodyAr: 'تم خسارة العميل المحتمل "{{leadTitle}}". السبب: {{lostReason}}',
      isDefault: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      tenantId: TENANT_ID,
      tenantSlug: TENANT_SLUG,
      eventType: 'STOCK_ADJUSTMENT',
      channel: 'push',
      subjectEn: 'Stock Adjustment',
      subjectAr: 'تعديل مخزون',
      bodyEn:
        'Stock adjustment for {{productName}} in {{warehouseName}}: {{adjustmentQuantity}} units',
      bodyAr: 'تعديل مخزون {{productName}} في {{warehouseName}}: {{adjustmentQuantity}} وحدة',
      isDefault: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      tenantId: TENANT_ID,
      tenantSlug: TENANT_SLUG,
      eventType: 'STOCK_TRANSFER',
      channel: 'push',
      subjectEn: 'Stock Transfer',
      subjectAr: 'تحويل مخزون',
      bodyEn:
        'Stock transfer of {{productName}}: {{quantity}} units from {{fromWarehouse}} to {{toWarehouse}}',
      bodyAr:
        'تحويل مخزون {{productName}}: {{quantity}} وحدة من {{fromWarehouse}} إلى {{toWarehouse}}',
      isDefault: true,
      createdBy: null,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
  ]);

  console.log('[14-notification-templates] Seeded 14 notification templates.');
}
