import { Sequelize } from 'sequelize';
import { v7 as uuidv7 } from 'uuid';

const TENANT_ID = '10000000-0000-4000-a000-000000000001';
const DEPT_1_ID = '50000000-0000-4000-a000-000000000001';
const DEPT_2_ID = '50000000-0000-4000-a000-000000000002';
const DEPT_3_ID = '50000000-0000-4000-a000-000000000003';
const USER_1_ID = '20000000-0000-4000-a000-000000000001';
const USER_2_ID = '20000000-0000-4000-a000-000000000002';
const USER_3_ID = '20000000-0000-4000-a000-000000000003';
const BRANCH_1_ID = '30000000-0000-4000-a000-000000000001';
const BRANCH_2_ID = '30000000-0000-4000-a000-000000000002';
const BRANCH_3_ID = '30000000-0000-4000-a000-000000000003';

export async function seed(sequelize: Sequelize): Promise<void> {
  const qi = sequelize.getQueryInterface();
  const now = new Date();

  // ═══════════════════════════════════════════════════════════════════════════
  // HR DEFINITIONS
  // ═══════════════════════════════════════════════════════════════════════════

  // ── Job Titles ──────────────────────────────────────────────────────────
  await qi.bulkInsert('job_titles', [
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Software Engineer',
      nameAr: 'مهندس برمجيات',
      departmentId: DEPT_1_ID,
      grade: 'L4',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Senior Software Engineer',
      nameAr: 'مهندس برمجيات أول',
      departmentId: DEPT_1_ID,
      grade: 'L5',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Accountant',
      nameAr: 'محاسب',
      departmentId: DEPT_2_ID,
      grade: 'L3',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Senior Accountant',
      nameAr: 'محاسب أول',
      departmentId: DEPT_2_ID,
      grade: 'L4',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'HR Manager',
      nameAr: 'مدير الموارد البشرية',
      departmentId: DEPT_3_ID,
      grade: 'L6',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Sales Representative',
      nameAr: 'مندوب مبيعات',
      departmentId: null,
      grade: 'L3',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Warehouse Supervisor',
      nameAr: 'مشرف مستودع',
      departmentId: null,
      grade: 'L4',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Cashier',
      nameAr: 'كاشير',
      departmentId: null,
      grade: 'L2',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);
  console.log('[18-definitions] Seeded 8 job titles.');

  // ── Employment Types ────────────────────────────────────────────────────
  await qi.bulkInsert('employment_types', [
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Full-Time',
      nameAr: 'دوام كامل',
      descriptionEn: 'Standard full-time employment',
      descriptionAr: 'توظيف بدوام كامل',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Part-Time',
      nameAr: 'دوام جزئي',
      descriptionEn: 'Part-time employment',
      descriptionAr: 'توظيف بدوام جزئي',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Contract',
      nameAr: 'عقد',
      descriptionEn: 'Fixed-term contract',
      descriptionAr: 'عقد محدد المدة',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Intern',
      nameAr: 'متدرب',
      descriptionEn: 'Internship program',
      descriptionAr: 'برنامج تدريب',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Seasonal',
      nameAr: 'موسمي',
      descriptionEn: 'Seasonal employment',
      descriptionAr: 'توظيف موسمي',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);
  console.log('[18-definitions] Seeded 5 employment types.');

  // ── Leave Types Config ──────────────────────────────────────────────────
  await qi.bulkInsert('leave_types_config', [
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Annual Leave',
      nameAr: 'إجازة سنوية',
      descriptionEn: 'Paid annual leave',
      descriptionAr: 'إجازة سنوية مدفوعة',
      daysPerYear: 21,
      isPaid: true,
      requiresApproval: true,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Sick Leave',
      nameAr: 'إجازة مرضية',
      descriptionEn: 'Paid sick leave',
      descriptionAr: 'إجازة مرضية مدفوعة',
      daysPerYear: 30,
      isPaid: true,
      requiresApproval: true,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Personal Leave',
      nameAr: 'إجازة شخصية',
      descriptionEn: 'Personal leave',
      descriptionAr: 'إجازة شخصية',
      daysPerYear: 5,
      isPaid: true,
      requiresApproval: true,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Unpaid Leave',
      nameAr: 'إجازة بدون راتب',
      descriptionEn: 'Unpaid leave of absence',
      descriptionAr: 'إجازة بدون راتب',
      daysPerYear: 0,
      isPaid: false,
      requiresApproval: true,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Maternity Leave',
      nameAr: 'إجازة أمومة',
      descriptionEn: 'Maternity leave (70 days)',
      descriptionAr: 'إجازة أمومة (70 يوم)',
      daysPerYear: 70,
      isPaid: true,
      requiresApproval: true,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Paternity Leave',
      nameAr: 'إجازة أبوة',
      descriptionEn: 'Paternity leave (3 days)',
      descriptionAr: 'إجازة أبوة (3 أيام)',
      daysPerYear: 3,
      isPaid: true,
      requiresApproval: true,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Emergency Leave',
      nameAr: 'إجازة طوارئ',
      descriptionEn: 'Emergency leave',
      descriptionAr: 'إجازة طوارئ',
      daysPerYear: 5,
      isPaid: true,
      requiresApproval: false,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);
  console.log('[18-definitions] Seeded 7 leave types.');

  // ── Public Holidays ─────────────────────────────────────────────────────
  await qi.bulkInsert('public_holidays', [
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Saudi National Day',
      nameAr: 'اليوم الوطني السعودي',
      date: '2026-09-23',
      isRecurring: true,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Eid Al-Fitr',
      nameAr: 'عيد الفطر',
      date: '2026-03-20',
      isRecurring: false,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Eid Al-Adha',
      nameAr: 'عيد الأضحى',
      date: '2026-05-27',
      isRecurring: false,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Founding Day',
      nameAr: 'يوم التأسيس',
      date: '2026-02-22',
      isRecurring: true,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);
  console.log('[18-definitions] Seeded 4 public holidays.');

  // ── Termination Reasons ─────────────────────────────────────────────────
  await qi.bulkInsert('termination_reasons', [
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Resignation',
      nameAr: 'استقالة',
      type: 'voluntary',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'End of Contract',
      nameAr: 'انتهاء العقد',
      type: 'end_of_contract',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Termination for Cause',
      nameAr: 'فصل لسبب',
      type: 'involuntary',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Layoff',
      nameAr: 'تسريح',
      type: 'involuntary',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Retirement',
      nameAr: 'تقاعد',
      type: 'retirement',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);
  console.log('[18-definitions] Seeded 5 termination reasons.');

  // ═══════════════════════════════════════════════════════════════════════════
  // INVENTORY DEFINITIONS
  // ═══════════════════════════════════════════════════════════════════════════

  // ── Units of Measure ────────────────────────────────────────────────────
  await qi.bulkInsert('units_of_measure', [
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Piece',
      nameAr: 'قطعة',
      symbol: 'pc',
      uomType: 'unit',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Kilogram',
      nameAr: 'كيلوغرام',
      symbol: 'kg',
      uomType: 'weight',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Gram',
      nameAr: 'غرام',
      symbol: 'g',
      uomType: 'weight',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Liter',
      nameAr: 'لتر',
      symbol: 'L',
      uomType: 'volume',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Milliliter',
      nameAr: 'مليلتر',
      symbol: 'mL',
      uomType: 'volume',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Meter',
      nameAr: 'متر',
      symbol: 'm',
      uomType: 'length',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Box',
      nameAr: 'صندوق',
      symbol: 'box',
      uomType: 'unit',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Dozen',
      nameAr: 'دزينة',
      symbol: 'dz',
      uomType: 'unit',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Hour',
      nameAr: 'ساعة',
      symbol: 'hr',
      uomType: 'time',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);
  console.log('[18-definitions] Seeded 9 units of measure.');

  // ── Adjustment Reasons ──────────────────────────────────────────────────
  await qi.bulkInsert('adjustment_reasons', [
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Physical Count Correction',
      nameAr: 'تصحيح الجرد الفعلي',
      type: 'increase',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Damaged Goods',
      nameAr: 'بضائع تالفة',
      type: 'decrease',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Expired Products',
      nameAr: 'منتجات منتهية الصلاحية',
      type: 'decrease',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Received Donation',
      nameAr: 'تبرع مستلم',
      type: 'increase',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Theft / Shrinkage',
      nameAr: 'سرقة / انكماش',
      type: 'decrease',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Opening Balance',
      nameAr: 'رصيد افتتاحي',
      type: 'increase',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);
  console.log('[18-definitions] Seeded 6 adjustment reasons.');

  // ═══════════════════════════════════════════════════════════════════════════
  // SALES & POS DEFINITIONS
  // ═══════════════════════════════════════════════════════════════════════════

  // ── Voucher Types ───────────────────────────────────────────────────────
  await qi.bulkInsert('voucher_types', [
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Welcome Discount',
      nameAr: 'خصم ترحيبي',
      descriptionEn: 'First-time customer discount',
      descriptionAr: 'خصم العميل الجديد',
      discountType: 'percentage',
      discountValue: 10,
      minOrderAmount: 50,
      validDays: 30,
      maxUses: 1,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Seasonal Sale',
      nameAr: 'تخفيضات موسمية',
      descriptionEn: 'Seasonal promotional voucher',
      descriptionAr: 'قسيمة ترويجية موسمية',
      discountType: 'percentage',
      discountValue: 20,
      minOrderAmount: 100,
      validDays: 14,
      maxUses: null,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Fixed Discount Coupon',
      nameAr: 'قسيمة خصم ثابت',
      descriptionEn: 'Fixed amount discount',
      descriptionAr: 'خصم بمبلغ ثابت',
      discountType: 'fixed',
      discountValue: 25,
      minOrderAmount: 150,
      validDays: 60,
      maxUses: 1,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);
  console.log('[18-definitions] Seeded 3 voucher types.');

  // ── Receipt Templates ───────────────────────────────────────────────────
  await qi.bulkInsert('receipt_templates', [
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Standard Receipt',
      nameAr: 'إيصال قياسي',
      headerTextEn: 'Thank you for shopping with us',
      headerTextAr: 'شكراً لتسوقكم معنا',
      footerTextEn: 'No returns after 14 days',
      footerTextAr: 'لا يقبل الإرجاع بعد 14 يوم',
      showLogo: true,
      showTaxDetails: true,
      showBarcode: true,
      copies: 1,
      isDefault: true,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Kitchen Copy',
      nameAr: 'نسخة المطبخ',
      headerTextEn: 'KITCHEN ORDER',
      headerTextAr: 'طلب المطبخ',
      footerTextEn: null,
      footerTextAr: null,
      showLogo: false,
      showTaxDetails: false,
      showBarcode: false,
      copies: 1,
      isDefault: false,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);
  console.log('[18-definitions] Seeded 2 receipt templates.');

  // ── Cancellation Reasons ────────────────────────────────────────────────
  await qi.bulkInsert('cancellation_reasons', [
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Customer Request',
      nameAr: 'طلب العميل',
      requiresApproval: false,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Out of Stock',
      nameAr: 'نفاد المخزون',
      requiresApproval: false,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Duplicate Order',
      nameAr: 'طلب مكرر',
      requiresApproval: false,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Price Error',
      nameAr: 'خطأ في السعر',
      requiresApproval: true,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);
  console.log('[18-definitions] Seeded 4 cancellation reasons.');

  // ── Void/Refund Reasons ─────────────────────────────────────────────────
  await qi.bulkInsert('void_refund_reasons', [
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Wrong Item',
      nameAr: 'منتج خاطئ',
      type: 'both',
      requiresManager: false,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Defective Product',
      nameAr: 'منتج معيب',
      type: 'refund',
      requiresManager: false,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Customer Changed Mind',
      nameAr: 'غيّر العميل رأيه',
      type: 'refund',
      requiresManager: false,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Cashier Error',
      nameAr: 'خطأ الكاشير',
      type: 'void',
      requiresManager: true,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'System Error',
      nameAr: 'خطأ في النظام',
      type: 'void',
      requiresManager: true,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);
  console.log('[18-definitions] Seeded 5 void/refund reasons.');

  // ── Discount Reasons ────────────────────────────────────────────────────
  await qi.bulkInsert('discount_reasons', [
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Loyalty Customer',
      nameAr: 'عميل دائم',
      maxPercent: 15,
      requiresApproval: false,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Bulk Purchase',
      nameAr: 'شراء بالجملة',
      maxPercent: 25,
      requiresApproval: true,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Damaged Packaging',
      nameAr: 'تغليف تالف',
      maxPercent: 30,
      requiresApproval: true,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Employee Discount',
      nameAr: 'خصم الموظفين',
      maxPercent: 20,
      requiresApproval: false,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);
  console.log('[18-definitions] Seeded 4 discount reasons.');

  // ── Hold Reasons ────────────────────────────────────────────────────────
  await qi.bulkInsert('hold_reasons', [
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Customer Browsing',
      nameAr: 'العميل يتصفح',
      maxHoldMinutes: 30,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Awaiting Payment',
      nameAr: 'في انتظار الدفع',
      maxHoldMinutes: 60,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Manager Approval Needed',
      nameAr: 'يحتاج موافقة المدير',
      maxHoldMinutes: 120,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Item Out of Stock - Checking',
      nameAr: 'نفاد المخزون - جاري الفحص',
      maxHoldMinutes: null,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);
  console.log('[18-definitions] Seeded 4 hold reasons.');

  // ═══════════════════════════════════════════════════════════════════════════
  // PURCHASES DEFINITIONS
  // ═══════════════════════════════════════════════════════════════════════════

  // ── Payment Terms ───────────────────────────────────────────────────────
  await qi.bulkInsert('payment_terms', [
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Immediate Payment',
      nameAr: 'دفع فوري',
      descriptionEn: 'Payment due upon receipt',
      descriptionAr: 'الدفع عند الاستلام',
      daysDue: 0,
      penaltyPercentage: 0,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Net 15',
      nameAr: 'صافي 15 يوم',
      descriptionEn: 'Payment due in 15 days',
      descriptionAr: 'الدفع خلال 15 يوم',
      daysDue: 15,
      penaltyPercentage: 0,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Net 30',
      nameAr: 'صافي 30 يوم',
      descriptionEn: 'Payment due in 30 days',
      descriptionAr: 'الدفع خلال 30 يوم',
      daysDue: 30,
      penaltyPercentage: 0,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Net 60',
      nameAr: 'صافي 60 يوم',
      descriptionEn: 'Payment due in 60 days',
      descriptionAr: 'الدفع خلال 60 يوم',
      daysDue: 60,
      penaltyPercentage: 2,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Net 90',
      nameAr: 'صافي 90 يوم',
      descriptionEn: 'Payment due in 90 days',
      descriptionAr: 'الدفع خلال 90 يوم',
      daysDue: 90,
      penaltyPercentage: 5,
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);
  console.log('[18-definitions] Seeded 5 payment terms.');

  // ── Rejection Reasons ───────────────────────────────────────────────────
  await qi.bulkInsert('rejection_reasons', [
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Quality Not Met',
      nameAr: 'الجودة غير مطابقة',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Wrong Specifications',
      nameAr: 'مواصفات خاطئة',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Late Delivery',
      nameAr: 'تأخر التسليم',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Price Mismatch',
      nameAr: 'اختلاف في السعر',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Damaged on Arrival',
      nameAr: 'تلف عند الوصول',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);
  console.log('[18-definitions] Seeded 5 rejection reasons.');

  // ═══════════════════════════════════════════════════════════════════════════
  // TREASURY DEFINITIONS
  // ═══════════════════════════════════════════════════════════════════════════

  // ── Transfer Reasons ────────────────────────────────────────────────────
  await qi.bulkInsert('transfer_reasons', [
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Branch Cash Supply',
      nameAr: 'تزويد الفرع بالنقد',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Bank Deposit',
      nameAr: 'إيداع بنكي',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Petty Cash Replenishment',
      nameAr: 'تجديد الصندوق النثري',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      nameEn: 'Inter-branch Settlement',
      nameAr: 'تسوية بين الفروع',
      isActive: true,
      version: 0,
      createdBy: null,
      updatedBy: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);
  console.log('[18-definitions] Seeded 4 transfer reasons.');

  // ═══════════════════════════════════════════════════════════════════════════
  // USER BRANCHES
  // Manager (USER_1) → all 3 branches, default = Main
  // Cashier (USER_2) → Main + East, default = Main
  // Employee (USER_3) → Main only, default = Main
  // ═══════════════════════════════════════════════════════════════════════════

  await qi.bulkInsert('user_branches', [
    // Manager — all branches
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      userId: USER_1_ID,
      branchId: BRANCH_1_ID,
      isDefault: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      userId: USER_1_ID,
      branchId: BRANCH_2_ID,
      isDefault: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      userId: USER_1_ID,
      branchId: BRANCH_3_ID,
      isDefault: false,
      createdAt: now,
      updatedAt: now,
    },
    // Cashier — Main + East
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      userId: USER_2_ID,
      branchId: BRANCH_1_ID,
      isDefault: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      userId: USER_2_ID,
      branchId: BRANCH_2_ID,
      isDefault: false,
      createdAt: now,
      updatedAt: now,
    },
    // Employee — Main only
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      userId: USER_3_ID,
      branchId: BRANCH_1_ID,
      isDefault: true,
      createdAt: now,
      updatedAt: now,
    },
  ]);
  console.log('[18-definitions] Seeded 6 user-branch assignments.');

  console.log('[18-definitions] All definition seed data completed.');
}
