import { Sequelize } from 'sequelize';
import { v7 as uuidv7 } from 'uuid';

const TENANT_ID = '10000000-0000-0000-0000-000000000001';
const USER_1_ID = '20000000-0000-0000-0000-000000000001';
const USER_2_ID = '20000000-0000-0000-0000-000000000002';

// Partner IDs from 07-crm
const PARTNER_1_ID = '80000000-0000-0000-0000-000000000001';
const PARTNER_2_ID = '80000000-0000-0000-0000-000000000002';
const PARTNER_3_ID = '80000000-0000-0000-0000-000000000003';
const PARTNER_10_ID = '80000000-0000-0000-0000-00000000000A';
const PARTNER_11_ID = '80000000-0000-0000-0000-00000000000B';

// Lead IDs from 07-crm
const LEAD_1_ID = '84000000-0000-0000-0000-000000000001';
const LEAD_2_ID = '84000000-0000-0000-0000-000000000002';
const LEAD_3_ID = '84000000-0000-0000-0000-000000000003';
const LEAD_7_ID = '84000000-0000-0000-0000-000000000007';

// Sales Order IDs from 07-crm
const SO_1_ID = '83000000-0000-0000-0000-000000000001';
const SO_3_ID = '83000000-0000-0000-0000-000000000003';

export async function seed(sequelize: Sequelize): Promise<void> {
  const qi = sequelize.getQueryInterface();
  const now = new Date();

  await qi.bulkInsert('activities', [
    // ── Lead Activities ─────────────────────────────────────────────────────
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      model: 'lead',
      recordId: LEAD_1_ID,
      recordName: 'Enterprise Software Deal',
      activityType: 'call',
      icon: 'phone',
      summary: 'Schedule follow-up call with Khalid Al-Saud about pricing',
      note: 'Discuss enterprise tier pricing and custom integrations requirements',
      scheduledDate: '2026-03-20',
      assignedTo: USER_1_ID,
      isDone: false,
      doneAt: null,
      doneByUserId: null,
      feedbackNote: null,
      createdBy: USER_1_ID,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      model: 'lead',
      recordId: LEAD_2_ID,
      recordName: 'POS System Sale',
      activityType: 'meeting',
      icon: 'calendar',
      summary: 'On-site demo at Harbi Trading office',
      note: 'Prepare demo with full POS flow including payment methods and inventory',
      scheduledDate: '2026-03-22',
      assignedTo: USER_1_ID,
      isDone: false,
      doneAt: null,
      doneByUserId: null,
      feedbackNote: null,
      createdBy: USER_1_ID,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      model: 'lead',
      recordId: LEAD_3_ID,
      recordName: 'Cloud Infrastructure Upgrade',
      activityType: 'email',
      icon: 'mail',
      summary: 'Send revised technical proposal to CTO',
      note: 'Include updated migration timeline and cost breakdown for cloud ERP',
      scheduledDate: '2026-03-18',
      assignedTo: USER_1_ID,
      isDone: true,
      doneAt: new Date('2026-03-18T10:30:00Z'),
      doneByUserId: USER_1_ID,
      feedbackNote: 'Proposal sent, awaiting CTO review',
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 1,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      model: 'lead',
      recordId: LEAD_7_ID,
      recordName: 'Logistics Software Integration',
      activityType: 'todo',
      icon: 'check-square',
      summary: 'Prepare final contract for Gulf Logistics',
      note: 'Legal review needed before sending final contract to partner',
      scheduledDate: '2026-03-25',
      assignedTo: USER_2_ID,
      isDone: false,
      doneAt: null,
      doneByUserId: null,
      feedbackNote: null,
      createdBy: USER_2_ID,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },

    // ── Partner Activities ───────────────────────────────────────────────────
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      model: 'partner',
      recordId: PARTNER_1_ID,
      recordName: 'Saudi Enterprises',
      activityType: 'call',
      icon: 'phone',
      summary: 'Quarterly account review call',
      note: 'Review Q1 performance and discuss expansion plans',
      scheduledDate: '2026-04-01',
      assignedTo: USER_1_ID,
      isDone: false,
      doneAt: null,
      doneByUserId: null,
      feedbackNote: null,
      createdBy: USER_1_ID,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      model: 'partner',
      recordId: PARTNER_10_ID,
      recordName: 'Al Rajhi Group',
      activityType: 'meeting',
      icon: 'calendar',
      summary: 'Annual strategic partnership review',
      note: 'Discuss renewal terms and potential scope expansion for IT services',
      scheduledDate: '2026-04-15',
      assignedTo: USER_1_ID,
      isDone: false,
      doneAt: null,
      doneByUserId: null,
      feedbackNote: null,
      createdBy: USER_1_ID,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      model: 'partner',
      recordId: PARTNER_2_ID,
      recordName: 'Harbi Trading',
      activityType: 'upload_document',
      icon: 'file-up',
      summary: 'Upload signed NDA from Harbi Trading',
      note: null,
      scheduledDate: '2026-03-19',
      assignedTo: USER_2_ID,
      isDone: true,
      doneAt: new Date('2026-03-19T14:00:00Z'),
      doneByUserId: USER_2_ID,
      feedbackNote: 'NDA uploaded to partner documents',
      createdBy: USER_2_ID,
      updatedBy: USER_2_ID,
      version: 1,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },

    // ── Sales Order Activities ───────────────────────────────────────────────
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      model: 'sale_order',
      recordId: SO_1_ID,
      recordName: 'SO-MAIN-00001',
      activityType: 'todo',
      icon: 'check-square',
      summary: 'Prepare shipment for confirmed order',
      note: 'Coordinate with warehouse team for delivery within 3 business days',
      scheduledDate: '2026-03-20',
      assignedTo: USER_2_ID,
      isDone: false,
      doneAt: null,
      doneByUserId: null,
      feedbackNote: null,
      createdBy: USER_1_ID,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      model: 'sale_order',
      recordId: SO_3_ID,
      recordName: 'SO-MAIN-00003',
      activityType: 'email',
      icon: 'mail',
      summary: 'Send delivery confirmation to Dosari Retail',
      note: 'Include tracking number and expected delivery date',
      scheduledDate: '2026-03-21',
      assignedTo: USER_1_ID,
      isDone: false,
      doneAt: null,
      doneByUserId: null,
      feedbackNote: null,
      createdBy: USER_1_ID,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },

    // ── Invoice Activity ────────────────────────────────────────────────────
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      model: 'invoice',
      recordId: uuidv7(), // placeholder invoice ID
      recordName: 'INV-2026-00015',
      activityType: 'call',
      icon: 'phone',
      summary: 'Follow up on overdue payment from Qahtani Group',
      note: 'Invoice overdue by 7 days, call CFO to discuss payment schedule',
      scheduledDate: '2026-03-18',
      assignedTo: USER_1_ID,
      isDone: false,
      doneAt: null,
      doneByUserId: null,
      feedbackNote: null,
      createdBy: USER_1_ID,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },

    // ── Deadline Activities ──────────────────────────────────────────────────
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      model: 'partner',
      recordId: PARTNER_3_ID,
      recordName: 'Qahtani Group',
      activityType: 'deadline',
      icon: 'clock',
      summary: 'Contract renewal deadline for Qahtani Group',
      note: 'Annual support contract expires on April 30. Initiate renewal talks.',
      scheduledDate: '2026-04-15',
      assignedTo: USER_1_ID,
      isDone: false,
      doneAt: null,
      doneByUserId: null,
      feedbackNote: null,
      createdBy: USER_1_ID,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      model: 'partner',
      recordId: PARTNER_11_ID,
      recordName: 'Gulf Logistics',
      activityType: 'deadline',
      icon: 'clock',
      summary: 'Proposal expiry for logistics integration project',
      note: 'Proposal valid until March 31. Need commitment before expiry.',
      scheduledDate: '2026-03-28',
      assignedTo: USER_2_ID,
      isDone: false,
      doneAt: null,
      doneByUserId: null,
      feedbackNote: null,
      createdBy: USER_2_ID,
      updatedBy: null,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
  ]);

  console.log(
    '[22-activities] Seeded 12 activities across lead, partner, sale_order, and invoice models.',
  );
}
