import { Sequelize } from 'sequelize';
import { v7 as uuidv7 } from 'uuid';

const TENANT_ID = '10000000-0000-4000-a000-000000000001';
const BRANCH_1_ID = '30000000-0000-4000-a000-000000000001';
const USER_1_ID = '20000000-0000-4000-a000-000000000001';
const CURRENCY_SAR_ID = '60000000-0000-4000-a000-000000000001';

// Customers (partners 1-5)
const PARTNER_1_ID = '80000000-0000-4000-a000-000000000001'; // Khalid Al-Saud
const PARTNER_3_ID = '80000000-0000-4000-a000-000000000003'; // Omar Al-Qahtani
const PARTNER_4_ID = '80000000-0000-4000-a000-000000000004'; // Nora Al-Dosari
const PARTNER_5_ID = '80000000-0000-4000-a000-000000000005'; // Youssef Mansour

// Products
const PRODUCT_1_ID = '71000000-0000-4000-a000-000000000001'; // Shawarma, 25 SAR
const PRODUCT_2_ID = '71000000-0000-4000-a000-000000000002'; // Coffee, 15 SAR
const PRODUCT_3_ID = '71000000-0000-4000-a000-000000000003'; // Laptop, 3999 SAR
const PRODUCT_4_ID = '71000000-0000-4000-a000-000000000004'; // Accessories, 89 SAR
const PRODUCT_5_ID = '71000000-0000-4000-a000-000000000005'; // Consulting, 500 SAR

// Sales Orders
const SO_1_ID = '83000000-0000-4000-a000-000000000001';
const SO_2_ID = '83000000-0000-4000-a000-000000000002';
const SO_3_ID = '83000000-0000-4000-a000-000000000003';
const SO_4_ID = '83000000-0000-4000-a000-000000000004';
const SO_5_ID = '83000000-0000-4000-a000-000000000005';

// Deliveries
const DELIVERY_1_ID = '88000000-0000-4000-a000-000000000001';
const DELIVERY_2_ID = '88000000-0000-4000-a000-000000000002';

// Down Payments
const DOWN_PAYMENT_1_ID = '86000000-0000-4000-a000-000000000001';
const DOWN_PAYMENT_2_ID = '86000000-0000-4000-a000-000000000002';

export async function seed(sequelize: Sequelize): Promise<void> {
  const qi = sequelize.getQueryInterface();
  const now = new Date();
  const oneWeekAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
  const twoDaysAgo = new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000);

  // ─── Sales Orders ─────────────────────────────────────────────────────────
  //
  // SO-1: Confirmed, partially delivered — 2x Laptop + 5x Consulting
  //   subtotal = 7998 + 2500 = 10498.00
  //   tax = 10498 * 0.15 = 1574.70
  //   total = 12072.70
  //   invoiceStatus = to_invoice, deliveryStatus = partial
  //
  // SO-2: Draft — 10x Accessories + 3x Consulting
  //   subtotal = 890 + 1500 = 2390.00
  //   tax = 2390 * 0.15 = 358.50
  //   total = 2748.50
  //   invoiceStatus = nothing, deliveryStatus = pending
  //
  // SO-3: Done — 500x Shawarma + 300x Coffee + 10x Accessories (5% discount line)
  //   Shawarma: 500 * 25 = 12500
  //   Coffee: 300 * 15 = 4500
  //   Accessories: 10 * 89 = 890, 5% disc = 44.50, net = 845.50
  //   subtotal = 12500 + 4500 + 845.50 = 17845.50
  //   tax = 17845.50 * 0.15 = 2676.83
  //   total = 17845.50 + 2676.83 = 20522.33
  //   invoiceStatus = invoiced, deliveryStatus = done
  //
  // SO-4: Confirmed — 1x Laptop + 20x Coffee (10% discount line)
  //   Laptop: 1 * 3999 = 3999
  //   Coffee: 20 * 15 = 300, 10% disc = 30, net = 270
  //   subtotal = 3999 + 270 = 4269.00
  //   tax = 4269 * 0.15 = 640.35
  //   total = 4269 + 640.35 = 4909.35
  //   invoiceStatus = nothing, deliveryStatus = pending
  //
  // SO-5: Cancelled — 5x Consulting
  //   subtotal = 2500, tax = 375, total = 2875

  await qi.bulkInsert('sales_orders', [
    {
      id: SO_1_ID,
      tenantId: TENANT_ID,
      orderNumber: 'SO-MAIN-00001',
      contactId: PARTNER_1_ID,
      partnerId: PARTNER_1_ID,
      branchId: BRANCH_1_ID,
      subtotal: 10498.0,
      discountAmount: 0,
      taxAmount: 1574.7,
      totalAmount: 12072.7,
      currency: 'SAR',
      currencyId: CURRENCY_SAR_ID,
      exchangeRate: 1,
      totalAmountBase: 12072.7,
      discountType: null,
      discountValue: null,
      status: 'confirmed',
      invoiceStatus: 'to_invoice',
      deliveryStatus: 'partial',
      pricelistId: null,
      paymentTermId: null,
      salespersonId: USER_1_ID,
      fiscalPositionId: null,
      internalNotes: null,
      confirmedAt: oneWeekAgo,
      notes: null,
      zatcaUUID: null,
      zatcaInvoiceCounter: null,
      zatcaHash: null,
      zatcaQRCode: null,
      zatcaSignature: null,
      zatcaSubmittedAt: null,
      zatcaClearedAt: null,
      zatcaStatus: null,
      invoiceType: 'standard',
      transactionType: 'invoice',
      supplyType: 'goods',
      taxCategory: 'S',
      taxExemptionCode: null,
      taxExemptionReason: null,
      originalInvoiceId: null,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 1,
      createdAt: oneWeekAgo,
      updatedAt: twoDaysAgo,
      deletedAt: null,
    },
    {
      id: SO_2_ID,
      tenantId: TENANT_ID,
      orderNumber: 'SO-MAIN-00002',
      contactId: PARTNER_3_ID,
      partnerId: PARTNER_3_ID,
      branchId: BRANCH_1_ID,
      subtotal: 2390.0,
      discountAmount: 0,
      taxAmount: 358.5,
      totalAmount: 2748.5,
      currency: 'SAR',
      currencyId: CURRENCY_SAR_ID,
      exchangeRate: 1,
      totalAmountBase: 2748.5,
      discountType: null,
      discountValue: null,
      status: 'draft',
      invoiceStatus: 'nothing',
      deliveryStatus: 'pending',
      pricelistId: null,
      paymentTermId: null,
      salespersonId: USER_1_ID,
      fiscalPositionId: null,
      internalNotes: 'Waiting for customer budget approval',
      confirmedAt: null,
      notes: null,
      zatcaUUID: null,
      zatcaInvoiceCounter: null,
      zatcaHash: null,
      zatcaQRCode: null,
      zatcaSignature: null,
      zatcaSubmittedAt: null,
      zatcaClearedAt: null,
      zatcaStatus: null,
      invoiceType: 'standard',
      transactionType: 'invoice',
      supplyType: 'goods',
      taxCategory: 'S',
      taxExemptionCode: null,
      taxExemptionReason: null,
      originalInvoiceId: null,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    },
    {
      id: SO_3_ID,
      tenantId: TENANT_ID,
      orderNumber: 'SO-MAIN-00003',
      contactId: PARTNER_4_ID,
      partnerId: PARTNER_4_ID,
      branchId: BRANCH_1_ID,
      subtotal: 17845.5,
      discountAmount: 44.5,
      taxAmount: 2676.83,
      totalAmount: 20522.33,
      currency: 'SAR',
      currencyId: CURRENCY_SAR_ID,
      exchangeRate: 1,
      totalAmountBase: 20522.33,
      discountType: null,
      discountValue: null,
      status: 'done',
      invoiceStatus: 'invoiced',
      deliveryStatus: 'done',
      pricelistId: null,
      paymentTermId: null,
      salespersonId: USER_1_ID,
      fiscalPositionId: null,
      internalNotes: null,
      confirmedAt: oneWeekAgo,
      notes: null,
      zatcaUUID: null,
      zatcaInvoiceCounter: null,
      zatcaHash: null,
      zatcaQRCode: null,
      zatcaSignature: null,
      zatcaSubmittedAt: null,
      zatcaClearedAt: null,
      zatcaStatus: null,
      invoiceType: 'standard',
      transactionType: 'invoice',
      supplyType: 'goods',
      taxCategory: 'S',
      taxExemptionCode: null,
      taxExemptionReason: null,
      originalInvoiceId: null,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 2,
      createdAt: oneWeekAgo,
      updatedAt: twoDaysAgo,
      deletedAt: null,
    },
    {
      id: SO_4_ID,
      tenantId: TENANT_ID,
      orderNumber: 'SO-MAIN-00004',
      contactId: PARTNER_5_ID,
      partnerId: PARTNER_5_ID,
      branchId: BRANCH_1_ID,
      subtotal: 4269.0,
      discountAmount: 30.0,
      taxAmount: 640.35,
      totalAmount: 4909.35,
      currency: 'SAR',
      currencyId: CURRENCY_SAR_ID,
      exchangeRate: 1,
      totalAmountBase: 4909.35,
      discountType: null,
      discountValue: null,
      status: 'confirmed',
      invoiceStatus: 'nothing',
      deliveryStatus: 'pending',
      pricelistId: null,
      paymentTermId: null,
      salespersonId: USER_1_ID,
      fiscalPositionId: null,
      internalNotes: 'Down payment received, awaiting stock',
      confirmedAt: twoDaysAgo,
      notes: null,
      zatcaUUID: null,
      zatcaInvoiceCounter: null,
      zatcaHash: null,
      zatcaQRCode: null,
      zatcaSignature: null,
      zatcaSubmittedAt: null,
      zatcaClearedAt: null,
      zatcaStatus: null,
      invoiceType: 'standard',
      transactionType: 'invoice',
      supplyType: 'goods',
      taxCategory: 'S',
      taxExemptionCode: null,
      taxExemptionReason: null,
      originalInvoiceId: null,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 1,
      createdAt: twoDaysAgo,
      updatedAt: twoDaysAgo,
      deletedAt: null,
    },
    {
      id: SO_5_ID,
      tenantId: TENANT_ID,
      orderNumber: 'SO-MAIN-00005',
      contactId: PARTNER_1_ID,
      partnerId: PARTNER_1_ID,
      branchId: BRANCH_1_ID,
      subtotal: 2500.0,
      discountAmount: 0,
      taxAmount: 375.0,
      totalAmount: 2875.0,
      currency: 'SAR',
      currencyId: CURRENCY_SAR_ID,
      exchangeRate: 1,
      totalAmountBase: 2875.0,
      discountType: null,
      discountValue: null,
      status: 'cancelled',
      invoiceStatus: 'nothing',
      deliveryStatus: 'pending',
      pricelistId: null,
      paymentTermId: null,
      salespersonId: USER_1_ID,
      fiscalPositionId: null,
      internalNotes: 'Customer cancelled — project postponed',
      confirmedAt: null,
      notes: null,
      zatcaUUID: null,
      zatcaInvoiceCounter: null,
      zatcaHash: null,
      zatcaQRCode: null,
      zatcaSignature: null,
      zatcaSubmittedAt: null,
      zatcaClearedAt: null,
      zatcaStatus: null,
      invoiceType: 'standard',
      transactionType: 'invoice',
      supplyType: 'services',
      taxCategory: 'S',
      taxExemptionCode: null,
      taxExemptionReason: null,
      originalInvoiceId: null,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 1,
      createdAt: oneWeekAgo,
      updatedAt: twoDaysAgo,
      deletedAt: null,
    },
  ]);

  // ─── Sales Order Lines ────────────────────────────────────────────────────
  // BIGINT auto-increment PK — no id field

  await qi.bulkInsert('sales_order_lines', [
    // ── SO-1 lines ──
    {
      tenantId: TENANT_ID,
      orderId: SO_1_ID,
      productId: PRODUCT_3_ID,
      productVariantId: null,
      description: 'Laptop - Retail Sale',
      quantity: 2,
      unitPrice: 3999.0,
      discountAmount: 0,
      discountPct: 0,
      taxRate: 15,
      taxAmount: 1199.7,
      lineTotal: 9197.7,
      currencyId: CURRENCY_SAR_ID,
      lineTotalBase: 9197.7,
      discountType: null,
      discountValue: null,
      qtyDelivered: 1,
      qtyInvoiced: 0,
      isComboParent: false,
      comboParentLineId: null,
      sequence: 10,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: oneWeekAgo,
      updatedAt: twoDaysAgo,
    },
    {
      tenantId: TENANT_ID,
      orderId: SO_1_ID,
      productId: PRODUCT_5_ID,
      productVariantId: null,
      description: 'Consulting Service',
      quantity: 5,
      unitPrice: 500.0,
      discountAmount: 0,
      discountPct: 0,
      taxRate: 15,
      taxAmount: 375.0,
      lineTotal: 2875.0,
      currencyId: CURRENCY_SAR_ID,
      lineTotalBase: 2875.0,
      discountType: null,
      discountValue: null,
      qtyDelivered: 0,
      qtyInvoiced: 0,
      isComboParent: false,
      comboParentLineId: null,
      sequence: 20,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: oneWeekAgo,
      updatedAt: oneWeekAgo,
    },

    // ── SO-2 lines ──
    {
      tenantId: TENANT_ID,
      orderId: SO_2_ID,
      productId: PRODUCT_4_ID,
      productVariantId: null,
      description: 'Tech Accessories',
      quantity: 10,
      unitPrice: 89.0,
      discountAmount: 0,
      discountPct: 0,
      taxRate: 15,
      taxAmount: 133.5,
      lineTotal: 1023.5,
      currencyId: CURRENCY_SAR_ID,
      lineTotalBase: 1023.5,
      discountType: null,
      discountValue: null,
      qtyDelivered: 0,
      qtyInvoiced: 0,
      isComboParent: false,
      comboParentLineId: null,
      sequence: 10,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      tenantId: TENANT_ID,
      orderId: SO_2_ID,
      productId: PRODUCT_5_ID,
      productVariantId: null,
      description: 'Consulting Service',
      quantity: 3,
      unitPrice: 500.0,
      discountAmount: 0,
      discountPct: 0,
      taxRate: 15,
      taxAmount: 225.0,
      lineTotal: 1725.0,
      currencyId: CURRENCY_SAR_ID,
      lineTotalBase: 1725.0,
      discountType: null,
      discountValue: null,
      qtyDelivered: 0,
      qtyInvoiced: 0,
      isComboParent: false,
      comboParentLineId: null,
      sequence: 20,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: now,
      updatedAt: now,
    },

    // ── SO-3 lines ──
    {
      tenantId: TENANT_ID,
      orderId: SO_3_ID,
      productId: PRODUCT_1_ID,
      productVariantId: null,
      description: 'Shawarma - Wholesale Order',
      quantity: 500,
      unitPrice: 25.0,
      discountAmount: 0,
      discountPct: 0,
      taxRate: 15,
      taxAmount: 1875.0,
      lineTotal: 14375.0,
      currencyId: CURRENCY_SAR_ID,
      lineTotalBase: 14375.0,
      discountType: null,
      discountValue: null,
      qtyDelivered: 500,
      qtyInvoiced: 500,
      isComboParent: false,
      comboParentLineId: null,
      sequence: 10,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: oneWeekAgo,
      updatedAt: twoDaysAgo,
    },
    {
      tenantId: TENANT_ID,
      orderId: SO_3_ID,
      productId: PRODUCT_2_ID,
      productVariantId: null,
      description: 'Coffee - Bulk Retail',
      quantity: 300,
      unitPrice: 15.0,
      discountAmount: 0,
      discountPct: 0,
      taxRate: 15,
      taxAmount: 675.0,
      lineTotal: 5175.0,
      currencyId: CURRENCY_SAR_ID,
      lineTotalBase: 5175.0,
      discountType: null,
      discountValue: null,
      qtyDelivered: 300,
      qtyInvoiced: 300,
      isComboParent: false,
      comboParentLineId: null,
      sequence: 20,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: oneWeekAgo,
      updatedAt: twoDaysAgo,
    },
    {
      tenantId: TENANT_ID,
      orderId: SO_3_ID,
      productId: PRODUCT_4_ID,
      productVariantId: null,
      description: 'Accessories - Discounted',
      quantity: 10,
      unitPrice: 89.0,
      discountAmount: 44.5,
      discountPct: 5.0,
      taxRate: 15,
      taxAmount: 126.83,
      lineTotal: 972.33,
      currencyId: CURRENCY_SAR_ID,
      lineTotalBase: 972.33,
      discountType: null,
      discountValue: null,
      qtyDelivered: 10,
      qtyInvoiced: 10,
      isComboParent: false,
      comboParentLineId: null,
      sequence: 30,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: oneWeekAgo,
      updatedAt: twoDaysAgo,
    },

    // ── SO-4 lines ──
    {
      tenantId: TENANT_ID,
      orderId: SO_4_ID,
      productId: PRODUCT_3_ID,
      productVariantId: null,
      description: 'Laptop',
      quantity: 1,
      unitPrice: 3999.0,
      discountAmount: 0,
      discountPct: 0,
      taxRate: 15,
      taxAmount: 599.85,
      lineTotal: 4598.85,
      currencyId: CURRENCY_SAR_ID,
      lineTotalBase: 4598.85,
      discountType: null,
      discountValue: null,
      qtyDelivered: 0,
      qtyInvoiced: 0,
      isComboParent: false,
      comboParentLineId: null,
      sequence: 10,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: twoDaysAgo,
      updatedAt: twoDaysAgo,
    },
    {
      tenantId: TENANT_ID,
      orderId: SO_4_ID,
      productId: PRODUCT_2_ID,
      productVariantId: null,
      description: 'Coffee - Bulk (10% off)',
      quantity: 20,
      unitPrice: 15.0,
      discountAmount: 30.0,
      discountPct: 10.0,
      taxRate: 15,
      taxAmount: 40.5,
      lineTotal: 310.5,
      currencyId: CURRENCY_SAR_ID,
      lineTotalBase: 310.5,
      discountType: null,
      discountValue: null,
      qtyDelivered: 0,
      qtyInvoiced: 0,
      isComboParent: false,
      comboParentLineId: null,
      sequence: 20,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: twoDaysAgo,
      updatedAt: twoDaysAgo,
    },

    // ── SO-5 lines ──
    {
      tenantId: TENANT_ID,
      orderId: SO_5_ID,
      productId: PRODUCT_5_ID,
      productVariantId: null,
      description: 'Consulting Service',
      quantity: 5,
      unitPrice: 500.0,
      discountAmount: 0,
      discountPct: 0,
      taxRate: 15,
      taxAmount: 375.0,
      lineTotal: 2875.0,
      currencyId: CURRENCY_SAR_ID,
      lineTotalBase: 2875.0,
      discountType: null,
      discountValue: null,
      qtyDelivered: 0,
      qtyInvoiced: 0,
      isComboParent: false,
      comboParentLineId: null,
      sequence: 10,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: oneWeekAgo,
      updatedAt: twoDaysAgo,
    },
  ]);

  // ─── Deliveries ─────────────────────────────────────────────────────────────
  // Delivery 1: Partial delivery for SO-1 — 1 of 2 laptops shipped
  // Delivery 2: Full delivery for SO-3 — all items delivered

  await qi.bulkInsert('deliveries', [
    {
      id: DELIVERY_1_ID,
      tenantId: TENANT_ID,
      branchId: BRANCH_1_ID,
      reference: 'OUT-00001',
      saleOrderId: SO_1_ID,
      partnerId: PARTNER_1_ID,
      status: 'done',
      scheduledDate: oneWeekAgo.toISOString().split('T')[0],
      doneDate: twoDaysAgo,
      responsibleId: USER_1_ID,
      notes: 'Partial shipment — 1 laptop delivered, 1 back-ordered',
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 1,
      createdAt: oneWeekAgo,
      updatedAt: twoDaysAgo,
      deletedAt: null,
    },
    {
      id: DELIVERY_2_ID,
      tenantId: TENANT_ID,
      branchId: BRANCH_1_ID,
      reference: 'OUT-00002',
      saleOrderId: SO_3_ID,
      partnerId: PARTNER_4_ID,
      status: 'done',
      scheduledDate: oneWeekAgo.toISOString().split('T')[0],
      doneDate: twoDaysAgo,
      responsibleId: USER_1_ID,
      notes: null,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 1,
      createdAt: oneWeekAgo,
      updatedAt: twoDaysAgo,
      deletedAt: null,
    },
  ]);

  // ─── Delivery Lines ─────────────────────────────────────────────────────────

  await qi.bulkInsert('delivery_lines', [
    // Delivery 1: 1 laptop out of 2 demanded
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      branchId: BRANCH_1_ID,
      deliveryId: DELIVERY_1_ID,
      productId: PRODUCT_3_ID,
      saleOrderLineId: null,
      stockMoveId: null,
      productVariantId: null,
      qtyDemand: 2,
      qtyDone: 1,
      unitOfMeasureId: null,
      locationId: null,
      lotNumber: null,
      serialNumber: 'LAP-2026-001',
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: oneWeekAgo,
      updatedAt: twoDaysAgo,
      deletedAt: null,
    },
    // Delivery 2: all items fully delivered
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      branchId: BRANCH_1_ID,
      deliveryId: DELIVERY_2_ID,
      productId: PRODUCT_1_ID,
      saleOrderLineId: null,
      stockMoveId: null,
      productVariantId: null,
      qtyDemand: 500,
      qtyDone: 500,
      unitOfMeasureId: null,
      locationId: null,
      lotNumber: 'LOT-SHAW-2026-03',
      serialNumber: null,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: oneWeekAgo,
      updatedAt: twoDaysAgo,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      branchId: BRANCH_1_ID,
      deliveryId: DELIVERY_2_ID,
      productId: PRODUCT_2_ID,
      saleOrderLineId: null,
      stockMoveId: null,
      productVariantId: null,
      qtyDemand: 300,
      qtyDone: 300,
      unitOfMeasureId: null,
      locationId: null,
      lotNumber: 'LOT-COFF-2026-03',
      serialNumber: null,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: oneWeekAgo,
      updatedAt: twoDaysAgo,
      deletedAt: null,
    },
    {
      id: uuidv7(),
      tenantId: TENANT_ID,
      branchId: BRANCH_1_ID,
      deliveryId: DELIVERY_2_ID,
      productId: PRODUCT_4_ID,
      saleOrderLineId: null,
      stockMoveId: null,
      productVariantId: null,
      qtyDemand: 10,
      qtyDone: 10,
      unitOfMeasureId: null,
      locationId: null,
      lotNumber: null,
      serialNumber: null,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: oneWeekAgo,
      updatedAt: twoDaysAgo,
      deletedAt: null,
    },
  ]);

  // ─── Down Payments ────────────────────────────────────────────────────────
  // Down Payment 1: 30% on SO-4 (total 4909.35 * 0.30 = 1472.81)
  // Down Payment 2: Fixed amount 500 SAR on SO-1

  await qi.bulkInsert('down_payments', [
    {
      id: DOWN_PAYMENT_1_ID,
      tenantId: TENANT_ID,
      branchId: BRANCH_1_ID,
      saleOrderId: SO_4_ID,
      invoiceId: null,
      type: 'percentage',
      value: 30.0,
      amount: 1472.81,
      isDeducted: false,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: twoDaysAgo,
      updatedAt: twoDaysAgo,
      deletedAt: null,
    },
    {
      id: DOWN_PAYMENT_2_ID,
      tenantId: TENANT_ID,
      branchId: BRANCH_1_ID,
      saleOrderId: SO_1_ID,
      invoiceId: null,
      type: 'fixed',
      value: 500.0,
      amount: 500.0,
      isDeducted: false,
      createdBy: USER_1_ID,
      updatedBy: USER_1_ID,
      version: 0,
      createdAt: oneWeekAgo,
      updatedAt: oneWeekAgo,
      deletedAt: null,
    },
  ]);

  console.log(
    '[23-sales-orders] Seeded 5 sales orders (11 lines), ' +
      '2 deliveries (4 delivery lines), 2 down payments.',
  );
}
