/**
 * Saudi Chart of Accounts — standard template based on Saudi accounting standards.
 * Data-only export (no DB logic) — imported by AccountsService for per-tenant seeding.
 */

export interface SaudiCoaEntry {
  code: string;
  nameEn: string;
  nameAr: string;
  type: 'asset' | 'liability' | 'equity' | 'revenue' | 'expense';
  normalBalance: 'debit' | 'credit';
  allowDirectPosting: boolean;
  parentCode?: string;
}

export const SAUDI_COA_SEED: SaudiCoaEntry[] = [
  // ── Assets ──────────────────────────────────────────────────────────────────
  {
    code: '1',
    nameEn: 'Assets',
    nameAr: 'الأصول',
    type: 'asset',
    normalBalance: 'debit',
    allowDirectPosting: false,
  },
  {
    code: '11',
    nameEn: 'Current Assets',
    nameAr: 'الأصول المتداولة',
    type: 'asset',
    normalBalance: 'debit',
    allowDirectPosting: false,
    parentCode: '1',
  },
  {
    code: '1101',
    nameEn: 'Cash',
    nameAr: 'النقد',
    type: 'asset',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '11',
  },
  {
    code: '1102',
    nameEn: 'Bank',
    nameAr: 'البنك',
    type: 'asset',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '11',
  },
  {
    code: '1103',
    nameEn: 'Petty Cash',
    nameAr: 'صندوق المصروفات النثرية',
    type: 'asset',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '11',
  },
  {
    code: '12',
    nameEn: 'Receivables',
    nameAr: 'الذمم المدينة',
    type: 'asset',
    normalBalance: 'debit',
    allowDirectPosting: false,
    parentCode: '1',
  },
  {
    code: '1201',
    nameEn: 'Accounts Receivable',
    nameAr: 'ذمم العملاء',
    type: 'asset',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '12',
  },
  {
    code: '1202',
    nameEn: 'Notes Receivable',
    nameAr: 'أوراق القبض',
    type: 'asset',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '12',
  },
  {
    code: '1203',
    nameEn: 'Employee Advances',
    nameAr: 'سلف الموظفين',
    type: 'asset',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '12',
  },
  {
    code: '13',
    nameEn: 'Inventory',
    nameAr: 'المخزون',
    type: 'asset',
    normalBalance: 'debit',
    allowDirectPosting: false,
    parentCode: '1',
  },
  {
    code: '1301',
    nameEn: 'Merchandise Inventory',
    nameAr: 'مخزون البضائع',
    type: 'asset',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '13',
  },
  {
    code: '1302',
    nameEn: 'Raw Materials',
    nameAr: 'المواد الخام',
    type: 'asset',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '13',
  },
  {
    code: '14',
    nameEn: 'Prepaid Expenses',
    nameAr: 'المصاريف المدفوعة مقدماً',
    type: 'asset',
    normalBalance: 'debit',
    allowDirectPosting: false,
    parentCode: '1',
  },
  {
    code: '1401',
    nameEn: 'Prepaid Rent',
    nameAr: 'إيجار مدفوع مقدماً',
    type: 'asset',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '14',
  },
  {
    code: '1402',
    nameEn: 'Prepaid Insurance',
    nameAr: 'تأمين مدفوع مقدماً',
    type: 'asset',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '14',
  },
  {
    code: '15',
    nameEn: 'Fixed Assets',
    nameAr: 'الأصول الثابتة',
    type: 'asset',
    normalBalance: 'debit',
    allowDirectPosting: false,
    parentCode: '1',
  },
  {
    code: '1501',
    nameEn: 'Land',
    nameAr: 'الأراضي',
    type: 'asset',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '15',
  },
  {
    code: '1502',
    nameEn: 'Buildings',
    nameAr: 'المباني',
    type: 'asset',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '15',
  },
  {
    code: '1503',
    nameEn: 'Vehicles',
    nameAr: 'المركبات',
    type: 'asset',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '15',
  },
  {
    code: '1504',
    nameEn: 'Furniture & Fixtures',
    nameAr: 'الأثاث والتجهيزات',
    type: 'asset',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '15',
  },
  {
    code: '1505',
    nameEn: 'Equipment',
    nameAr: 'المعدات',
    type: 'asset',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '15',
  },
  {
    code: '1506',
    nameEn: 'Accumulated Depreciation',
    nameAr: 'مجمع الاستهلاك',
    type: 'asset',
    normalBalance: 'credit',
    allowDirectPosting: true,
    parentCode: '15',
  },

  // ── Liabilities ─────────────────────────────────────────────────────────────
  {
    code: '2',
    nameEn: 'Liabilities',
    nameAr: 'الالتزامات',
    type: 'liability',
    normalBalance: 'credit',
    allowDirectPosting: false,
  },
  {
    code: '21',
    nameEn: 'Current Liabilities',
    nameAr: 'الالتزامات المتداولة',
    type: 'liability',
    normalBalance: 'credit',
    allowDirectPosting: false,
    parentCode: '2',
  },
  {
    code: '2101',
    nameEn: 'Accounts Payable',
    nameAr: 'ذمم الموردين',
    type: 'liability',
    normalBalance: 'credit',
    allowDirectPosting: true,
    parentCode: '21',
  },
  {
    code: '2102',
    nameEn: 'Notes Payable',
    nameAr: 'أوراق الدفع',
    type: 'liability',
    normalBalance: 'credit',
    allowDirectPosting: true,
    parentCode: '21',
  },
  {
    code: '2103',
    nameEn: 'Accrued Expenses',
    nameAr: 'المصاريف المستحقة',
    type: 'liability',
    normalBalance: 'credit',
    allowDirectPosting: true,
    parentCode: '21',
  },
  {
    code: '2104',
    nameEn: 'Salaries Payable',
    nameAr: 'الرواتب المستحقة',
    type: 'liability',
    normalBalance: 'credit',
    allowDirectPosting: true,
    parentCode: '21',
  },
  {
    code: '2105',
    nameEn: 'VAT Payable',
    nameAr: 'ضريبة القيمة المضافة المستحقة',
    type: 'liability',
    normalBalance: 'credit',
    allowDirectPosting: true,
    parentCode: '21',
  },
  {
    code: '2106',
    nameEn: 'GOSI Payable',
    nameAr: 'التأمينات الاجتماعية المستحقة',
    type: 'liability',
    normalBalance: 'credit',
    allowDirectPosting: true,
    parentCode: '21',
  },
  {
    code: '2107',
    nameEn: 'Unearned Revenue',
    nameAr: 'إيرادات غير مكتسبة',
    type: 'liability',
    normalBalance: 'credit',
    allowDirectPosting: true,
    parentCode: '21',
  },
  {
    code: '2108',
    nameEn: 'Loyalty Points Liability',
    nameAr: 'التزام نقاط الولاء',
    type: 'liability',
    normalBalance: 'credit',
    allowDirectPosting: true,
    parentCode: '21',
  },
  {
    code: '2109',
    nameEn: 'Gift Card Liability',
    nameAr: 'التزام بطاقات الهدايا',
    type: 'liability',
    normalBalance: 'credit',
    allowDirectPosting: true,
    parentCode: '21',
  },
  {
    code: '22',
    nameEn: 'Long-term Liabilities',
    nameAr: 'الالتزامات طويلة الأجل',
    type: 'liability',
    normalBalance: 'credit',
    allowDirectPosting: false,
    parentCode: '2',
  },
  {
    code: '2201',
    nameEn: 'Long-term Loans',
    nameAr: 'القروض طويلة الأجل',
    type: 'liability',
    normalBalance: 'credit',
    allowDirectPosting: true,
    parentCode: '22',
  },
  {
    code: '2202',
    nameEn: 'End of Service Benefits',
    nameAr: 'مكافأة نهاية الخدمة',
    type: 'liability',
    normalBalance: 'credit',
    allowDirectPosting: true,
    parentCode: '22',
  },

  // ── Equity ──────────────────────────────────────────────────────────────────
  {
    code: '3',
    nameEn: 'Equity',
    nameAr: 'حقوق الملكية',
    type: 'equity',
    normalBalance: 'credit',
    allowDirectPosting: false,
  },
  {
    code: '31',
    nameEn: "Owner's Equity",
    nameAr: 'رأس المال',
    type: 'equity',
    normalBalance: 'credit',
    allowDirectPosting: false,
    parentCode: '3',
  },
  {
    code: '3101',
    nameEn: 'Capital',
    nameAr: 'رأس المال',
    type: 'equity',
    normalBalance: 'credit',
    allowDirectPosting: true,
    parentCode: '31',
  },
  {
    code: '3102',
    nameEn: 'Retained Earnings',
    nameAr: 'الأرباح المحتجزة',
    type: 'equity',
    normalBalance: 'credit',
    allowDirectPosting: true,
    parentCode: '31',
  },
  {
    code: '3103',
    nameEn: 'Owner Drawings',
    nameAr: 'المسحوبات الشخصية',
    type: 'equity',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '31',
  },

  // ── Revenue ─────────────────────────────────────────────────────────────────
  {
    code: '4',
    nameEn: 'Revenue',
    nameAr: 'الإيرادات',
    type: 'revenue',
    normalBalance: 'credit',
    allowDirectPosting: false,
  },
  {
    code: '41',
    nameEn: 'Operating Revenue',
    nameAr: 'الإيرادات التشغيلية',
    type: 'revenue',
    normalBalance: 'credit',
    allowDirectPosting: false,
    parentCode: '4',
  },
  {
    code: '4101',
    nameEn: 'Sales Revenue',
    nameAr: 'إيرادات المبيعات',
    type: 'revenue',
    normalBalance: 'credit',
    allowDirectPosting: true,
    parentCode: '41',
  },
  {
    code: '4102',
    nameEn: 'Service Revenue',
    nameAr: 'إيرادات الخدمات',
    type: 'revenue',
    normalBalance: 'credit',
    allowDirectPosting: true,
    parentCode: '41',
  },
  {
    code: '4103',
    nameEn: 'Sales Returns',
    nameAr: 'مردودات المبيعات',
    type: 'revenue',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '41',
  },
  {
    code: '4104',
    nameEn: 'Sales Discounts',
    nameAr: 'خصومات المبيعات',
    type: 'revenue',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '41',
  },
  {
    code: '42',
    nameEn: 'Other Revenue',
    nameAr: 'إيرادات أخرى',
    type: 'revenue',
    normalBalance: 'credit',
    allowDirectPosting: false,
    parentCode: '4',
  },
  {
    code: '4201',
    nameEn: 'Interest Income',
    nameAr: 'إيرادات الفوائد',
    type: 'revenue',
    normalBalance: 'credit',
    allowDirectPosting: true,
    parentCode: '42',
  },
  {
    code: '4202',
    nameEn: 'Foreign Exchange Gains',
    nameAr: 'أرباح فروق العملة',
    type: 'revenue',
    normalBalance: 'credit',
    allowDirectPosting: true,
    parentCode: '42',
  },

  // ── Expenses ────────────────────────────────────────────────────────────────
  {
    code: '5',
    nameEn: 'Expenses',
    nameAr: 'المصروفات',
    type: 'expense',
    normalBalance: 'debit',
    allowDirectPosting: false,
  },
  {
    code: '51',
    nameEn: 'Cost of Goods Sold',
    nameAr: 'تكلفة المبيعات',
    type: 'expense',
    normalBalance: 'debit',
    allowDirectPosting: false,
    parentCode: '5',
  },
  {
    code: '5101',
    nameEn: 'COGS - Merchandise',
    nameAr: 'تكلفة البضائع المباعة',
    type: 'expense',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '51',
  },
  {
    code: '5102',
    nameEn: 'Purchase Returns',
    nameAr: 'مردودات المشتريات',
    type: 'expense',
    normalBalance: 'credit',
    allowDirectPosting: true,
    parentCode: '51',
  },
  {
    code: '52',
    nameEn: 'Operating Expenses',
    nameAr: 'المصاريف التشغيلية',
    type: 'expense',
    normalBalance: 'debit',
    allowDirectPosting: false,
    parentCode: '5',
  },
  {
    code: '5201',
    nameEn: 'Salaries & Wages',
    nameAr: 'الرواتب والأجور',
    type: 'expense',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '52',
  },
  {
    code: '5202',
    nameEn: 'Housing Allowance',
    nameAr: 'بدل السكن',
    type: 'expense',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '52',
  },
  {
    code: '5203',
    nameEn: 'Transportation Allowance',
    nameAr: 'بدل النقل',
    type: 'expense',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '52',
  },
  {
    code: '5204',
    nameEn: 'GOSI Expense (Employer)',
    nameAr: 'مصاريف التأمينات الاجتماعية',
    type: 'expense',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '52',
  },
  {
    code: '5205',
    nameEn: 'End of Service Expense',
    nameAr: 'مصاريف مكافأة نهاية الخدمة',
    type: 'expense',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '52',
  },
  {
    code: '5206',
    nameEn: 'Rent Expense',
    nameAr: 'مصاريف الإيجار',
    type: 'expense',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '52',
  },
  {
    code: '5207',
    nameEn: 'Utilities Expense',
    nameAr: 'مصاريف المرافق',
    type: 'expense',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '52',
  },
  {
    code: '5208',
    nameEn: 'Office Supplies',
    nameAr: 'مصاريف اللوازم المكتبية',
    type: 'expense',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '52',
  },
  {
    code: '5209',
    nameEn: 'Depreciation Expense',
    nameAr: 'مصاريف الاستهلاك',
    type: 'expense',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '52',
  },
  {
    code: '5210',
    nameEn: 'Insurance Expense',
    nameAr: 'مصاريف التأمين',
    type: 'expense',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '52',
  },
  {
    code: '5211',
    nameEn: 'Maintenance & Repairs',
    nameAr: 'مصاريف الصيانة والإصلاح',
    type: 'expense',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '52',
  },
  {
    code: '5212',
    nameEn: 'Marketing & Advertising',
    nameAr: 'مصاريف التسويق والإعلان',
    type: 'expense',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '52',
  },
  {
    code: '5213',
    nameEn: 'Communication Expense',
    nameAr: 'مصاريف الاتصالات',
    type: 'expense',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '52',
  },
  {
    code: '5214',
    nameEn: 'Travel & Entertainment',
    nameAr: 'مصاريف السفر والضيافة',
    type: 'expense',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '52',
  },
  {
    code: '5215',
    nameEn: 'Professional Fees',
    nameAr: 'أتعاب مهنية',
    type: 'expense',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '52',
  },
  {
    code: '5216',
    nameEn: 'Government Fees & Licenses',
    nameAr: 'رسوم حكومية وتراخيص',
    type: 'expense',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '52',
  },
  {
    code: '5217',
    nameEn: 'Bank Charges',
    nameAr: 'عمولات بنكية',
    type: 'expense',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '52',
  },
  {
    code: '53',
    nameEn: 'Other Expenses',
    nameAr: 'مصروفات أخرى',
    type: 'expense',
    normalBalance: 'debit',
    allowDirectPosting: false,
    parentCode: '5',
  },
  {
    code: '5301',
    nameEn: 'Foreign Exchange Losses',
    nameAr: 'خسائر فروق العملة',
    type: 'expense',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '53',
  },
  {
    code: '5302',
    nameEn: 'Miscellaneous Expense',
    nameAr: 'مصروفات متنوعة',
    type: 'expense',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '53',
  },
  {
    code: '5303',
    nameEn: 'Inventory Adjustment',
    nameAr: 'تسوية المخزون',
    type: 'expense',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '53',
  },
  {
    code: '5304',
    nameEn: 'Foreign Exchange Gain/Loss',
    nameAr: 'أرباح/خسائر فروق العملة',
    type: 'expense',
    normalBalance: 'debit',
    allowDirectPosting: true,
    parentCode: '53',
  },
];
