import { Module, Global } from '@nestjs/common';
import { SequelizeModule } from '@nestjs/sequelize';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { TenantSequelizeService } from './tenant-sequelize.service';
import { UmzugService } from './umzug.service';
import {
  Admin,
  AdminNotification,
  Tenant,
  User,
  Branch,
  UserFcmToken,
  RefreshToken,
  ApiKey,
  Role,
  Permission,
  RolePermission,
  UserRole,
  Notification,
  NotificationPreference,
  NotificationTemplate,
  Employee,
  Department,
  LeaveRequest,
  Product,
  ProductCategory,
  Warehouse,
  StockLevel,
  StockMovement,
  Contact,
  Lead,
  LeadActivity,
  SalesOrder,
  SalesOrderLine,
  Vendor,
  PurchaseOrder,
  PurchaseOrderLine,
  Project,
  Task,
  TaskTimeEntry,
  Plan,
  Subscription,
  PaymentTransaction,
  AuditLog,
  OutboxEvent,
  SecurityEvent,
  RetentionLog,
  ConsentRecord,
  ErasureRequest,
  TenantMetric,
  TenantNote,
  TenantOnboarding,
  ImpersonationLog,
  Sequence,
  ProjectMember,
  PosTerminal,
  PosSession,
  CashMovement,
  PosCashier,
  ManagerOverride,
  LoyaltyProgram,
  LoyaltyTier,
  LoyaltyAccount,
  LoyaltyTransaction,
  Voucher,
  VoucherRedemption,
  GiftCard,
  GiftCardTransaction,
  PosOrder,
  PosOrderItem,
  PosPayment,
  PosHeldOrder,
  PosRefund,
  Currency,
  ExchangeRate,
  TreasuryAccount,
  TreasuryTransaction,
  BankReconciliation,
  RestaurantSection,
  RestaurantTable,
  TableSession,
  KitchenTicket,
  ChartOfAccount,
  CostCenter,
  FiscalPeriod,
  JournalEntry,
  JournalLine,
  Shift,
  AttendanceRecord,
  PayrollRun,
  PayrollItem,
  TrainingRecord,
  EmployeeContract,
  UserAppearance,
  UserPreference,
  UserBranch,
  JobTitle,
  EmploymentTypeConfig,
  LeaveTypeConfig,
  PublicHoliday,
  TerminationReason,
  UnitOfMeasure,
  AdjustmentReason,
  VoucherTypeConfig,
  ReceiptTemplate,
  CancellationReason,
  VoidRefundReason,
  DiscountReason,
  HoldReason,
  PaymentTerm,
  RejectionReason,
  TransferReason,
  // New entities (schema restructure)
  Partner,
  PartnerContact,
  Invoice,
  InvoiceLine,
  InvoiceLineTax,
  PaymentNew,
  InvoicePayment,
  AccountGroup,
  TaxGroup,
  Tax,
  Journal,
  PaymentTermLine,
  StockLocation,
  Delivery,
  DeliveryLine,
  Receipt,
  ReceiptLine,
  SalaryStructure,
  SalaryRule,
  Payslip,
  PayslipLine,
  LeaveType,
  LeaveAllocation,
  JobPosition,
  ShiftWorkingDay,
  ProductAttribute,
  ProductAttributeValue,
  ProductTemplateAttribute,
  ProductTemplateAttributeValue,
  ProductVariant,
  ProductVariantAttributeValue,
  ProductTax,
  ComboProduct,
  ComboGroup,
  ComboGroupItem,
  Activity,
  EmailTemplate,
  BankStatement,
  BankStatementLine,
  FiscalPosition,
  FiscalPositionTax,
  FiscalPositionAccount,
  CrmStage,
  CompanySetting,
  BranchSetting,
  Pricelist,
  PricelistItem,
  SupplierProduct,
  BranchProduct,
  DownPayment,
} from './entities';
import { SystemSetting } from '../../modules/settings/entities/system-setting.entity';
import { TenantSetting } from '../../modules/settings/entities/tenant-setting.entity';
import { Ticket } from '../../modules/tickets/entities/ticket.entity';
import { TicketReply } from '../../modules/tickets/entities/ticket-reply.entity';
import { Release } from '../../infrastructure/releases/entities/release.entity';
import {
  AdminNotificationsRepository,
  AdminsRepository,
  ApiKeysRepository,
  AuthRepository,
  BranchesRepository,
  CategoriesRepository,
  ContactsRepository,
  DepartmentsRepository,
  EmployeesRepository,
  LeadActivitiesRepository,
  LeadsRepository,
  LeavesRepository,
  NotificationPreferencesRepository,
  NotificationsRepository,
  NotificationTemplatesRepository,
  PaymentTransactionsRepository,
  PermissionsRepository,
  PlansRepository,
  ProductsRepository,
  ProjectMembersRepository,
  ProjectsRepository,
  PurchaseOrderLinesRepository,
  PurchaseOrdersRepository,
  ReportingRepository,
  RolesRepository,
  SalesOrderLinesRepository,
  SalesOrdersRepository,
  SequencesRepository,
  SystemSettingsRepository,
  TenantSettingsRepository,
  StockLevelsRepository,
  StockMovementsRepository,
  SubscriptionsRepository,
  TasksRepository,
  TaskTimeEntriesRepository,
  TenantNotesRepository,
  TenantsRepository,
  TicketRepliesRepository,
  TicketsRepository,
  UsersRepository,
  VendorsRepository,
  WarehousesRepository,
  PosTerminalsRepository,
  PosSessionsRepository,
  CashMovementsRepository,
  PosCashiersRepository,
  ManagerOverridesRepository,
  LoyaltyProgramsRepository,
  LoyaltyTiersRepository,
  LoyaltyAccountsRepository,
  LoyaltyTransactionsRepository,
  VouchersRepository,
  VoucherRedemptionsRepository,
  GiftCardsRepository,
  GiftCardTransactionsRepository,
  CurrenciesRepository,
  ExchangeRatesRepository,
  PosOrdersRepository,
  PosOrderItemsRepository,
  PosPaymentsRepository,
  PosHeldOrdersRepository,
  PosRefundsRepository,
  TreasuryAccountsRepository,
  TreasuryTransactionsRepository,
  BankReconciliationsRepository,
  RestaurantSectionsRepository,
  RestaurantTablesRepository,
  TableSessionsRepository,
  KitchenTicketsRepository,
  ChartOfAccountsRepository,
  CostCentersRepository,
  FiscalPeriodsRepository,
  JournalEntriesRepository,
  JournalLinesRepository,
  ShiftsRepository,
  AttendanceRecordsRepository,
  PayrollRunsRepository,
  PayrollItemsRepository,
  TrainingRecordsRepository,
  EmployeeContractsRepository,
  AuditLogsRepository,
  ReleasesRepository,
  JobTitlesRepository,
  EmploymentTypesRepository,
  LeaveTypesConfigRepository,
  PublicHolidaysRepository,
  TerminationReasonsRepository,
  UnitsOfMeasureRepository,
  AdjustmentReasonsRepository,
  VoucherTypesRepository,
  ReceiptTemplatesRepository,
  CancellationReasonsRepository,
  VoidRefundReasonsRepository,
  DiscountReasonsRepository,
  HoldReasonsRepository,
  PaymentTermsRepository,
  RejectionReasonsRepository,
  TransferReasonsRepository,
  UserPreferencesRepository,
  UserBranchesRepository,
  // New repositories (schema restructure)
  PartnersRepository,
  PartnerContactsRepository,
  InvoicesRepository,
  InvoiceLinesRepository,
  InvoiceLineTaxesRepository,
  PaymentsNewRepository,
  InvoicePaymentsRepository,
  AccountGroupsRepository,
  TaxGroupsRepository,
  TaxesRepository,
  JournalsRepository,
  PaymentTermLinesRepository,
  StockLocationsRepository,
  DeliveriesRepository,
  DeliveryLinesRepository,
  ReceiptsRepository,
  ReceiptLinesRepository,
  SalaryStructuresRepository,
  SalaryRulesRepository,
  PayslipsRepository,
  PayslipLinesRepository,
  LeaveTypesRepository,
  LeaveAllocationsRepository,
  JobPositionsRepository,
  ShiftWorkingDaysRepository,
  ProductAttributesRepository,
  ProductAttributeValuesRepository,
  ProductTemplateAttributesRepository,
  ProductTemplateAttributeValuesRepository,
  ProductVariantsRepository,
  ProductVariantAttributeValuesRepository,
  ProductTaxesRepository,
  ComboProductsRepository,
  ComboGroupsRepository,
  ComboGroupItemsRepository,
  ActivitiesRepository,
  EmailTemplatesRepository,
  BankStatementsRepository,
  BankStatementLinesRepository,
  FiscalPositionsRepository,
  FiscalPositionTaxesRepository,
  FiscalPositionAccountsRepository,
  CrmStagesRepository,
  CompanySettingsRepository,
  BranchSettingsRepository,
  PricelistsRepository,
  PricelistItemsRepository,
  SupplierProductsRepository,
  BranchProductsRepository,
  DownPaymentsRepository,
} from './repositories';

const models = [
  // Auth
  Admin,
  AdminNotification,
  Tenant,
  User,
  Branch,
  UserFcmToken,
  RefreshToken,
  ApiKey,
  // RBAC
  Role,
  Permission,
  RolePermission,
  UserRole,
  // Notifications
  Notification,
  NotificationPreference,
  NotificationTemplate,
  // HR
  Employee,
  Department,
  LeaveRequest,
  // Inventory
  Product,
  ProductCategory,
  Warehouse,
  StockLevel,
  StockMovement,
  // CRM
  Contact,
  Lead,
  LeadActivity,
  SalesOrder,
  SalesOrderLine,
  // Purchasing
  Vendor,
  PurchaseOrder,
  PurchaseOrderLine,
  // Sequences
  Sequence,
  // Projects
  Project,
  ProjectMember,
  Task,
  TaskTimeEntry,
  // Subscriptions
  Plan,
  Subscription,
  PaymentTransaction,
  // System
  AuditLog,
  OutboxEvent,
  SecurityEvent,
  RetentionLog,
  ConsentRecord,
  ErasureRequest,
  TenantMetric,
  TenantNote,
  TenantOnboarding,
  ImpersonationLog,
  // POS
  PosTerminal,
  PosSession,
  CashMovement,
  PosCashier,
  ManagerOverride,
  PosOrder,
  PosOrderItem,
  PosPayment,
  PosHeldOrder,
  PosRefund,
  // Loyalty
  LoyaltyProgram,
  LoyaltyTier,
  LoyaltyAccount,
  LoyaltyTransaction,
  // Vouchers & Gift Cards
  Voucher,
  VoucherRedemption,
  GiftCard,
  GiftCardTransaction,
  // Currency
  Currency,
  ExchangeRate,
  // Treasury
  TreasuryAccount,
  TreasuryTransaction,
  BankReconciliation,
  // Restaurant
  RestaurantSection,
  RestaurantTable,
  TableSession,
  KitchenTicket,
  // Accounting
  ChartOfAccount,
  CostCenter,
  FiscalPeriod,
  JournalEntry,
  JournalLine,
  // HR Extensions
  Shift,
  AttendanceRecord,
  PayrollRun,
  PayrollItem,
  TrainingRecord,
  EmployeeContract,
  // User Settings
  UserAppearance,
  UserPreference,
  UserBranch,
  // HR Definitions
  JobTitle,
  EmploymentTypeConfig,
  LeaveTypeConfig,
  PublicHoliday,
  TerminationReason,
  // Inventory Definitions
  UnitOfMeasure,
  AdjustmentReason,
  // Sales & POS Definitions
  VoucherTypeConfig,
  ReceiptTemplate,
  CancellationReason,
  VoidRefundReason,
  DiscountReason,
  HoldReason,
  // Purchases Definitions
  PaymentTerm,
  RejectionReason,
  // Treasury Definitions
  TransferReason,
  // Partners
  Partner,
  PartnerContact,
  // Invoices & Payments
  Invoice,
  InvoiceLine,
  InvoiceLineTax,
  PaymentNew,
  InvoicePayment,
  // Accounting Setup
  AccountGroup,
  TaxGroup,
  Tax,
  Journal,
  PaymentTermLine,
  // Stock Locations & Shipping
  StockLocation,
  Delivery,
  DeliveryLine,
  Receipt,
  ReceiptLine,
  // HR & Payroll Restructure
  SalaryStructure,
  SalaryRule,
  Payslip,
  PayslipLine,
  LeaveType,
  LeaveAllocation,
  JobPosition,
  ShiftWorkingDay,
  // Product Variants & Combos
  ProductAttribute,
  ProductAttributeValue,
  ProductTemplateAttribute,
  ProductTemplateAttributeValue,
  ProductVariant,
  ProductVariantAttributeValue,
  ProductTax,
  ComboProduct,
  ComboGroup,
  ComboGroupItem,
  // Activities
  Activity,
  // Email Templates
  EmailTemplate,
  // Bank Statements
  BankStatement,
  BankStatementLine,
  // Fiscal Positions
  FiscalPosition,
  FiscalPositionTax,
  FiscalPositionAccount,
  // CRM Stages
  CrmStage,
  // Company & Branch Settings
  CompanySetting,
  BranchSetting,
  // Pricelists
  Pricelist,
  PricelistItem,
  // Supplier & Branch Products
  SupplierProduct,
  BranchProduct,
  // Down Payments
  DownPayment,
  // Module-local entities
  SystemSetting,
  TenantSetting,
  Ticket,
  TicketReply,
  Release,
];

const repositories = [
  AdminNotificationsRepository,
  AdminsRepository,
  ApiKeysRepository,
  AuthRepository,
  BranchesRepository,
  CategoriesRepository,
  ContactsRepository,
  DepartmentsRepository,
  EmployeesRepository,
  LeadActivitiesRepository,
  LeadsRepository,
  LeavesRepository,
  NotificationPreferencesRepository,
  NotificationsRepository,
  NotificationTemplatesRepository,
  PaymentTransactionsRepository,
  PermissionsRepository,
  PlansRepository,
  ProductsRepository,
  ProjectMembersRepository,
  ProjectsRepository,
  PurchaseOrderLinesRepository,
  PurchaseOrdersRepository,
  ReportingRepository,
  RolesRepository,
  SalesOrderLinesRepository,
  SalesOrdersRepository,
  SequencesRepository,
  SystemSettingsRepository,
  TenantSettingsRepository,
  StockLevelsRepository,
  StockMovementsRepository,
  SubscriptionsRepository,
  TasksRepository,
  TenantNotesRepository,
  TaskTimeEntriesRepository,
  TenantsRepository,
  TicketRepliesRepository,
  TicketsRepository,
  UsersRepository,
  VendorsRepository,
  WarehousesRepository,
  PosTerminalsRepository,
  PosSessionsRepository,
  CashMovementsRepository,
  PosCashiersRepository,
  ManagerOverridesRepository,
  LoyaltyProgramsRepository,
  LoyaltyTiersRepository,
  LoyaltyAccountsRepository,
  LoyaltyTransactionsRepository,
  VouchersRepository,
  VoucherRedemptionsRepository,
  GiftCardsRepository,
  GiftCardTransactionsRepository,
  CurrenciesRepository,
  ExchangeRatesRepository,
  PosOrdersRepository,
  PosOrderItemsRepository,
  PosPaymentsRepository,
  PosHeldOrdersRepository,
  PosRefundsRepository,
  TreasuryAccountsRepository,
  TreasuryTransactionsRepository,
  BankReconciliationsRepository,
  RestaurantSectionsRepository,
  RestaurantTablesRepository,
  TableSessionsRepository,
  KitchenTicketsRepository,
  ChartOfAccountsRepository,
  CostCentersRepository,
  FiscalPeriodsRepository,
  JournalEntriesRepository,
  JournalLinesRepository,
  ShiftsRepository,
  AttendanceRecordsRepository,
  PayrollRunsRepository,
  PayrollItemsRepository,
  TrainingRecordsRepository,
  EmployeeContractsRepository,
  AuditLogsRepository,
  ReleasesRepository,
  // HR Definitions
  JobTitlesRepository,
  EmploymentTypesRepository,
  LeaveTypesConfigRepository,
  PublicHolidaysRepository,
  TerminationReasonsRepository,
  // Inventory Definitions
  UnitsOfMeasureRepository,
  AdjustmentReasonsRepository,
  // Sales & POS Definitions
  VoucherTypesRepository,
  ReceiptTemplatesRepository,
  CancellationReasonsRepository,
  VoidRefundReasonsRepository,
  DiscountReasonsRepository,
  HoldReasonsRepository,
  // Purchases Definitions
  PaymentTermsRepository,
  RejectionReasonsRepository,
  // Treasury Definitions
  TransferReasonsRepository,
  // User
  UserPreferencesRepository,
  UserBranchesRepository,
  // Partners
  PartnersRepository,
  PartnerContactsRepository,
  // Invoices & Payments
  InvoicesRepository,
  InvoiceLinesRepository,
  InvoiceLineTaxesRepository,
  PaymentsNewRepository,
  InvoicePaymentsRepository,
  // Accounting Setup
  AccountGroupsRepository,
  TaxGroupsRepository,
  TaxesRepository,
  JournalsRepository,
  PaymentTermLinesRepository,
  // Stock Locations & Shipping
  StockLocationsRepository,
  DeliveriesRepository,
  DeliveryLinesRepository,
  ReceiptsRepository,
  ReceiptLinesRepository,
  // HR & Payroll Restructure
  SalaryStructuresRepository,
  SalaryRulesRepository,
  PayslipsRepository,
  PayslipLinesRepository,
  LeaveTypesRepository,
  LeaveAllocationsRepository,
  JobPositionsRepository,
  ShiftWorkingDaysRepository,
  // Product Variants & Combos
  ProductAttributesRepository,
  ProductAttributeValuesRepository,
  ProductTemplateAttributesRepository,
  ProductTemplateAttributeValuesRepository,
  ProductVariantsRepository,
  ProductVariantAttributeValuesRepository,
  ProductTaxesRepository,
  ComboProductsRepository,
  ComboGroupsRepository,
  ComboGroupItemsRepository,
  // Activities
  ActivitiesRepository,
  // Email Templates
  EmailTemplatesRepository,
  // Bank Statements
  BankStatementsRepository,
  BankStatementLinesRepository,
  // Fiscal Positions
  FiscalPositionsRepository,
  FiscalPositionTaxesRepository,
  FiscalPositionAccountsRepository,
  // CRM Stages
  CrmStagesRepository,
  // Company & Branch Settings
  CompanySettingsRepository,
  BranchSettingsRepository,
  // Pricelists
  PricelistsRepository,
  PricelistItemsRepository,
  // Supplier & Branch Products
  SupplierProductsRepository,
  BranchProductsRepository,
  // Down Payments
  DownPaymentsRepository,
];

@Global()
@Module({
  imports: [
    SequelizeModule.forRootAsync({
      imports: [ConfigModule],
      useFactory: (configService: ConfigService) => {
        const db = configService.get('database');
        const isDev = configService.get('app.nodeEnv') === 'development';

        const writeHost = {
          host: db.host,
          port: db.port,
          username: db.username,
          password: db.password,
        };
        const readHost = db.readHost
          ? { host: db.readHost, port: db.readPort, username: db.username, password: db.password }
          : null;

        return {
          dialect: 'postgres',
          database: db.database,
          ...(readHost
            ? { replication: { write: writeHost, read: [readHost] } }
            : { host: db.host, port: db.port, username: db.username, password: db.password }),
          models,
          autoLoadModels: true,
          synchronize: false,
          logging: isDev ? console.log : false,
          pool: {
            min: 2,
            max: 10,
            acquire: 30000,
            idle: 10000,
            evict: 1000,
          },
          define: {
            paranoid: true,
            timestamps: true,
          },
        };
      },
      inject: [ConfigService],
    }),
  ],
  providers: [TenantSequelizeService, UmzugService, ...repositories],
  exports: [TenantSequelizeService, UmzugService, ...repositories],
})
export class DatabaseModule {}
