import { Injectable } from '@nestjs/common';
import * as PDFDocument from 'pdfkit';

export interface PdfTableColumn {
  key: string;
  label: string;
  align?: 'left' | 'right';
  format?: 'currency' | 'number' | 'text';
}

export interface PdfGenerateOptions {
  title: string;
  tenantName: string;
  period?: { from: string; to: string };
  columns: PdfTableColumn[];
  rows: Record<string, unknown>[];
  totals?: Record<string, unknown>;
}

@Injectable()
export class PdfGeneratorService {
  generateTable(options: PdfGenerateOptions): Buffer {
    const { title, tenantName, period, columns, rows, totals } = options;

    const doc = new PDFDocument({ size: 'A4', margin: 40, bufferPages: true });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk: Buffer) => chunks.push(chunk));

    // ── Header ──────────────────────────────────────────────────────────
    doc.fontSize(18).font('Helvetica-Bold').text(tenantName, { align: 'center' });
    doc.moveDown(0.3);
    doc.fontSize(14).text(title, { align: 'center' });
    doc.moveDown(0.3);

    if (period) {
      doc
        .fontSize(9)
        .font('Helvetica')
        .text(`Period: ${period.from} — ${period.to}`, { align: 'center' });
    }

    doc
      .fontSize(8)
      .font('Helvetica')
      .text(`Generated: ${new Date().toISOString().split('T')[0]}`, { align: 'center' });

    doc.moveDown(1);

    // ── Table ───────────────────────────────────────────────────────────
    const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
    const colWidth = pageWidth / columns.length;
    const startX = doc.page.margins.left;
    let y = doc.y;

    // Column headers
    doc.fontSize(8).font('Helvetica-Bold');
    const headerHeight = 20;
    doc.rect(startX, y, pageWidth, headerHeight).fill('#1F4E79');

    columns.forEach((col, i) => {
      const x = startX + i * colWidth + 4;
      doc.fillColor('#FFFFFF').text(col.label, x, y + 5, {
        width: colWidth - 8,
        align: col.align ?? 'left',
      });
    });
    y += headerHeight;
    doc.fillColor('#000000');

    // Data rows
    doc.font('Helvetica').fontSize(7);
    const rowHeight = 16;

    rows.forEach((row, rowIdx) => {
      // Check for page break
      if (y + rowHeight > doc.page.height - doc.page.margins.bottom - 30) {
        doc.addPage();
        y = doc.page.margins.top;
      }

      // Alternating row shading
      if (rowIdx % 2 === 1) {
        doc.rect(startX, y, pageWidth, rowHeight).fill('#F2F2F2');
        doc.fillColor('#000000');
      }

      columns.forEach((col, i) => {
        const x = startX + i * colWidth + 4;
        const rawValue = row[col.key];
        const displayValue = this.formatCellValue(rawValue, col.format);
        doc.text(displayValue, x, y + 4, {
          width: colWidth - 8,
          align:
            col.align ?? (col.format === 'currency' || col.format === 'number' ? 'right' : 'left'),
        });
      });

      y += rowHeight;
    });

    // Totals row
    if (totals) {
      if (y + rowHeight > doc.page.height - doc.page.margins.bottom - 30) {
        doc.addPage();
        y = doc.page.margins.top;
      }

      doc.rect(startX, y, pageWidth, rowHeight).fill('#E8E8E8');
      doc.fillColor('#000000').font('Helvetica-Bold').fontSize(7);

      columns.forEach((col, i) => {
        const x = startX + i * colWidth + 4;
        const rawValue = totals[col.key];
        const displayValue = rawValue != null ? this.formatCellValue(rawValue, col.format) : '';
        doc.text(displayValue, x, y + 4, {
          width: colWidth - 8,
          align:
            col.align ?? (col.format === 'currency' || col.format === 'number' ? 'right' : 'left'),
        });
      });
    }

    // ── Footer — page numbers ───────────────────────────────────────────
    const range = doc.bufferedPageRange();
    for (let i = range.start; i < range.start + range.count; i++) {
      doc.switchToPage(i);
      doc
        .fontSize(7)
        .font('Helvetica')
        .text(
          `Generated by Tatweer ERP — Page ${i + 1} of ${range.count}`,
          doc.page.margins.left,
          doc.page.height - doc.page.margins.bottom - 10,
          { align: 'center', width: pageWidth },
        );
    }

    doc.end();

    return Buffer.concat(chunks);
  }

  private formatCellValue(value: unknown, format?: 'currency' | 'number' | 'text'): string {
    if (value == null) return '';

    if (format === 'currency') {
      const num = typeof value === 'number' ? value : parseFloat(String(value));
      if (isNaN(num)) return String(value);
      return `${num.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} SAR`;
    }

    if (format === 'number') {
      const num = typeof value === 'number' ? value : parseFloat(String(value));
      if (isNaN(num)) return String(value);
      return num.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
    }

    return String(value);
  }
}
